// storybook-angular/src/components/ids-footer/ids-footer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
} from "@angular/core";
import {
  FOOTER_SPEC_ACCURATE_DEFAULTS,
} from "@component-contracts/ids/footer.contract";
import { IdsIconComponent } from "../ids-icon/ids-icon.component";

async function copyTextToClipboard(text: string): Promise<void> {
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.setAttribute("readonly", "");
  textarea.style.position = "fixed";
  textarea.style.left = "-9999px";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  document.body.removeChild(textarea);
}

@Component({
  selector: "ids-footer",
  standalone: true,
  imports: [IdsIconComponent],
  templateUrl: "./ids-footer.component.html",
  styleUrl: "./ids-footer.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "ids-footer-host",
  },
})
export class IdsFooterComponent {
  @Input() hostname: string = FOOTER_SPEC_ACCURATE_DEFAULTS.hostname;
  @Input() swid: string = FOOTER_SPEC_ACCURATE_DEFAULTS.swid;
  @Input() currentDateTime: string = FOOTER_SPEC_ACCURATE_DEFAULTS.currentDateTime;
  @Input() timeZoneLabel: string = FOOTER_SPEC_ACCURATE_DEFAULTS.timeZoneLabel;
  @Input() showHostname = FOOTER_SPEC_ACCURATE_DEFAULTS.showHostname;
  @Input() showCurrentDateAndTime = FOOTER_SPEC_ACCURATE_DEFAULTS.showCurrentDateAndTime;
  @Input() showTimeZone = FOOTER_SPEC_ACCURATE_DEFAULTS.showTimeZone;
  @Input() copyDisabled = FOOTER_SPEC_ACCURATE_DEFAULTS.copyDisabled;
  @Input() timeZoneDisabled = FOOTER_SPEC_ACCURATE_DEFAULTS.timeZoneDisabled;

  @Output() readonly copySwid = new EventEmitter<string>();
  @Output() readonly timeZoneClick = new EventEmitter<void>();

  get canCopy(): boolean {
    return Boolean(this.swid) && !this.copyDisabled;
  }

  get resolvedTimeZoneLabel(): string {
    return this.timeZoneLabel || "Time zone";
  }

  get showSwidGroup(): boolean {
    return this.swid != null && this.swid !== "";
  }

  get showTimeGroup(): boolean {
    return (
      this.showCurrentDateAndTime &&
      this.currentDateTime != null &&
      this.currentDateTime !== ""
    );
  }

  async onCopyClick(): Promise<void> {
    if (!this.canCopy || !this.swid) {
      return;
    }
    try {
      await copyTextToClipboard(this.swid);
    } catch {
      /* host may surface errors via copySwid */
    }
    this.copySwid.emit(this.swid);
  }

  onTimeZoneButtonClick(): void {
    if (this.timeZoneDisabled) {
      return;
    }
    this.timeZoneClick.emit();
  }
}

<footer class="ids-footer" aria-label="Application status">
  <div class="ids-footer__left">
    @if (showHostname) {
      <div class="ids-footer__field">
        <span class="ids-footer__label">Host Name: </span>
        <span class="ids-footer__value">{{ hostname }}</span>
      </div>
    }
    @if (showSwidGroup) {
      <div class="ids-footer__swid-group">
        <div class="ids-footer__field">
          <span class="ids-footer__label">SWID: </span>
          <span class="ids-footer__value">{{ swid }}</span>
        </div>
        <button
          type="button"
          class="ids-footer__copy-button"
          aria-label="Copy SWID"
          [disabled]="!canCopy"
          [attr.aria-disabled]="!canCopy ? 'true' : null"
          (click)="onCopyClick()"
        >
          <ids-icon
            className="ids-footer__copy-icon"
            shapeName="copy"
            variant="mask"
            [size]="14"
          />
        </button>
      </div>
    }
  </div>
  @if (showTimeGroup) {
    <div class="ids-footer__time-group">
      <ids-icon
        className="ids-footer__time-icon"
        shapeName="time-clock"
        variant="mask"
        [size]="16"
      />
      <span class="ids-footer__datetime">{{ currentDateTime }}</span>
    </div>
  }
  @if (showTimeZone) {
    <div class="ids-footer__timezone-group">
      <ids-icon
        className="ids-footer__globe-icon"
        shapeName="world-globe"
        variant="mask"
        [size]="16"
      />
      <button
        type="button"
        class="ids-footer__timezone-button"
        [disabled]="timeZoneDisabled"
        (click)="onTimeZoneButtonClick()"
      >
        {{ resolvedTimeZoneLabel }}
      </button>
    </div>
  }
</footer>

// lib/react/ids/footer/IdsFooter.tsx
/**
 * IDS Footer — React implementation generated from design-spec.
 *
 * Path: `lib/react/ids/footer`
 * Source: `components/ids/footer/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * Anatomy:
 *   FooterRoot
 *     FooterLeftRegion
 *       FooterHostName?
 *       FooterSwidGroup? (label + value + FooterCopyControl)
 *     FooterTimeGroup?
 *     FooterTimeZoneGroup? (IdsButton tertiary small + world-globe)
 *
 * Composition: `IdsIcon`, `IdsButton` (+ LeadingIcon/Label), `IdsTooltip` for
 * hostname truncation tooltip. No @base-ui-components dependency.
 */

import React, {
  useEffect,
  useState,
  type ComponentProps,
  type ReactElement,
} from "react";
import {
  IdsButton,
  IdsButtonLabel,
  IdsButtonLeadingIcon,
} from "../button";
import { IdsIcon } from "../icon";
import {
  IdsTooltip,
  TooltipBody,
  TooltipPanel,
  TooltipTrigger,
} from "../tooltip";
import styles from "./IdsFooter.module.css";

const HOSTNAME_MAX_CHARS = 48;

export interface IdsFooterProps
  extends Omit<ComponentProps<"footer">, "children"> {
  hostname?: string;
  swid?: string;
  currentDateTime?: string;
  timeZoneLabel?: string;
  showHostname?: boolean;
  showCurrentDateAndTime?: boolean;
  showTimeZone?: boolean;
  copyDisabled?: boolean;
  timeZoneDisabled?: boolean;
  onCopySwid?: (swid: string) => void;
  onTimeZoneClick?: () => void;
}

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

/** Visibility toggles: non-boolean → `true` (design-spec fallback). */
function resolveShowFlag(value: unknown): boolean {
  if (typeof value === "boolean") return value;
  return true;
}

async function copyTextToClipboard(text: string): Promise<void> {
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.setAttribute("readonly", "");
  textarea.style.position = "fixed";
  textarea.style.left = "-9999px";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  document.body.removeChild(textarea);
}

function truncateHostname(value: string): string {
  if (value.length <= HOSTNAME_MAX_CHARS) return value;
  return `${value.slice(0, HOSTNAME_MAX_CHARS)}...`;
}

export function IdsFooter({
  hostname,
  swid,
  currentDateTime,
  timeZoneLabel,
  showHostname: showHostnameProp = true,
  showCurrentDateAndTime: showCurrentDateAndTimeProp = true,
  showTimeZone: showTimeZoneProp = true,
  copyDisabled = false,
  timeZoneDisabled = false,
  onCopySwid,
  onTimeZoneClick,
  className,
  ...rest
}: IdsFooterProps): ReactElement {
  const showHostname = resolveShowFlag(showHostnameProp);
  const showCurrentDateAndTime = resolveShowFlag(showCurrentDateAndTimeProp);
  const showTimeZone = resolveShowFlag(showTimeZoneProp);

  const hostnameText = hostname ?? "";
  const truncatedHostname = truncateHostname(hostnameText);
  const hasSwid = swid != null && swid !== "";
  const canCopy = hasSwid && !copyDisabled;
  const zoneLabel =
    timeZoneLabel != null && timeZoneLabel !== ""
      ? timeZoneLabel
      : "Time zone";

  const [valueEl, setValueEl] = useState<HTMLSpanElement | null>(null);
  const [isOverflowed, setIsOverflowed] = useState(false);

  useEffect(() => {
    if (!valueEl) return;

    const updateOverflow = () => {
      setIsOverflowed(valueEl.scrollWidth > valueEl.clientWidth);
    };

    updateOverflow();

    const ro =
      typeof ResizeObserver !== "undefined"
        ? new ResizeObserver(updateOverflow)
        : null;
    if (ro) ro.observe(valueEl);

    return () => {
      if (ro) ro.disconnect();
    };
  }, [valueEl, truncatedHostname]);

  const showHostnameTooltip =
    isOverflowed || hostnameText.length >= HOSTNAME_MAX_CHARS;

  const handleCopy = async () => {
    if (!canCopy || !swid) return;
    try {
      await copyTextToClipboard(swid);
    } catch {
      /* Clipboard failure still notifies host via onCopySwid (spec fallback). */
    }
    onCopySwid?.(swid);
  };

  const hostnameValueNode = (
    <span ref={setValueEl} className={styles["ids-footer-hostname-text"]}>
      {truncatedHostname}
    </span>
  );

  return (
    <footer
      {...rest}
      className={cx(styles["ids-footer"], className)}
      aria-label="Application status"
      data-ids="ids-footer"
    >
      <div className={styles["ids-footer-left"]} data-ids="ids-footer-left">
        {showHostname ? (
          <div
            className={cx(
              styles["ids-footer-field"],
              styles["ids-footer-hostname"],
            )}
            data-ids="ids-footer-hostname"
          >
            <span className={styles["ids-footer-label"]}>Host Name:</span>
            <span className={styles["ids-footer-hostname-value"]}>
              {showHostnameTooltip ? (
                <IdsTooltip hugContent side="top">
                  <TooltipTrigger display="block" tabIndex={0}>
                    {hostnameValueNode}
                  </TooltipTrigger>
                  <TooltipPanel>
                    <TooltipBody>
                      <span className={styles["ids-footer-hostname-tooltip"]}>
                        {hostnameText}
                      </span>
                    </TooltipBody>
                  </TooltipPanel>
                </IdsTooltip>
              ) : (
                hostnameValueNode
              )}
            </span>
          </div>
        ) : null}

        {hasSwid ? (
          <div
            className={styles["ids-footer-swid-group"]}
            data-ids="ids-footer-swid-group"
          >
            <div className={styles["ids-footer-field"]}>
              <span className={styles["ids-footer-label"]}>SWID:</span>
              <span className={styles["ids-footer-value"]}>{swid}</span>
            </div>
            <button
              type="button"
              className={styles["ids-footer-copy"]}
              data-ids="ids-footer-copy"
              aria-label="Copy SWID"
              aria-disabled={!canCopy || undefined}
              disabled={!canCopy}
              onClick={() => void handleCopy()}
            >
              <IdsIcon
                shape="copy"
                variant="mask"
                size={14}
                color="currentColor"
              />
            </button>
          </div>
        ) : null}
      </div>

      {showCurrentDateAndTime ? (
        <div
          className={styles["ids-footer-time-group"]}
          data-ids="ids-footer-time-group"
        >
          <IdsIcon
            shape="time-clock"
            variant="mask"
            size={16}
            color="var(--color-icon-gray-neutral-base)"
          />
          <span className={styles["ids-footer-datetime"]}>
            {currentDateTime ?? ""}
          </span>
        </div>
      ) : null}

      {showTimeZone ? (
        <div
          className={styles["ids-footer-timezone-group"]}
          data-ids="ids-footer-timezone-group"
        >
          <IdsButton
            type="button"
            variant="tertiary"
            size="small"
            disabled={timeZoneDisabled}
            onClick={() => onTimeZoneClick?.()}
          >
            <IdsButtonLeadingIcon>
              <IdsIcon
                shape="world-globe"
                variant="mask"
                size={16}
                color="var(--color-icon-brand-base)"
              />
            </IdsButtonLeadingIcon>
            <IdsButtonLabel>{zoneLabel}</IdsButtonLabel>
          </IdsButton>
        </div>
      ) : null}
    </footer>
  );
}

IdsFooter.displayName = "IdsFooter";

export default IdsFooter;
