// lib/angular/ids/link/ids-link.component.ts
/**
 * IDS Link — Angular implementation from design-spec.
 *
 * Path: `lib/angular/ids/link`
 * Source: `components/ids/link/design-spec.md`
 * Parity: `lib/react/ids/link` (usr/muthu/lib)
 * Theme: `components/ids-theme.css`
 *
 * Anatomy:
 *   root (`<a>` | `<button>`)
 *     label
 *     externalIcon?  — lib `IdsIcon` (`pop-up-square-corner-big`, 16px)
 */
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
  isDevMode,
} from "@angular/core";
import {
  LINK_EXTERNAL_ICON_SHAPE,
  LINK_EXTERNAL_ICON_SIZE,
  LINK_RUNTIME_DEFAULTS,
  LINK_TYPES,
  type IdsLinkDataState,
  type IdsLinkTarget,
  type IdsLinkType,
} from "@component-contracts/ids/link.contract";
import { IdsIconComponent } from "../icon/ids-icon.component";

const LINK_TYPE_SET = new Set<string>(LINK_TYPES);

@Component({
  selector: "ids-link",
  standalone: true,
  imports: [IdsIconComponent],
  templateUrl: "./ids-link.component.html",
  styleUrl: "./ids-link.component.scss",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    style: "display: contents",
  },
})
export class IdsLinkComponent {
  readonly externalIconShape = LINK_EXTERNAL_ICON_SHAPE;
  readonly externalIconSize = LINK_EXTERNAL_ICON_SIZE;

  /** Required visible label. Empty → `"Link"` + development warning. */
  @Input() label: string = LINK_RUNTIME_DEFAULTS.label;

  /** Variant axis `Type`. Unknown → `standalone`. */
  @Input() type: IdsLinkType | string = LINK_RUNTIME_DEFAULTS.type;

  /** When set (non-empty), renders native `<a>`; otherwise button semantics. */
  @Input() href?: string;

  @Input() showExternalLinkIcon = LINK_RUNTIME_DEFAULTS.showExternalLinkIcon;

  @Input() target: IdsLinkTarget = LINK_RUNTIME_DEFAULTS.target;

  /** When `target="_blank"`, defaults to `noopener noreferrer` unless set. */
  @Input() rel?: string;

  @Input() disabled = LINK_RUNTIME_DEFAULTS.disabled;

  /** Demo/testing visual override only — does not replace interaction logic. */
  @Input() dataState?: IdsLinkDataState;

  /** Angular mapping of design-spec / React `onClick`. */
  @Output() readonly clicked = new EventEmitter<MouseEvent>();

  get resolvedType(): IdsLinkType {
    if (typeof this.type === "string" && LINK_TYPE_SET.has(this.type)) {
      return this.type as IdsLinkType;
    }
    return "standalone";
  }

  get resolvedLabel(): string {
    if (this.label == null || String(this.label).trim() === "") {
      if (isDevMode()) {
        console.warn('IdsLink: empty `label` — rendering fallback text "Link".');
      }
      return "Link";
    }
    return String(this.label);
  }

  get isAnchor(): boolean {
    return this.href != null && this.href !== "";
  }

  get resolvedHref(): string | undefined {
    if (!this.isAnchor || this.disabled) {
      return undefined;
    }
    return this.href;
  }

  get resolvedTarget(): string | undefined {
    return this.target === "_self" ? undefined : this.target;
  }

  get resolvedRel(): string | undefined {
    if (this.rel != null) {
      return this.rel;
    }
    if (this.target === "_blank") {
      return "noopener noreferrer";
    }
    return undefined;
  }

  get stateAttr(): string | undefined {
    return this.dataState && this.dataState !== "default"
      ? this.dataState
      : undefined;
  }

  get rootClass(): string {
    return `ids-link ids-link--${this.resolvedType}`;
  }

  onActivate(event: MouseEvent): void {
    if (this.disabled) {
      event.preventDefault();
      return;
    }
    this.clicked.emit(event);
  }
}

@if (isAnchor) {
  <a
    [class]="rootClass"
    data-ids="ids-link"
    [attr.data-type]="resolvedType"
    [attr.data-state]="stateAttr || null"
    [attr.data-external-icon]="showExternalLinkIcon ? 'true' : null"
    [attr.href]="resolvedHref || null"
    [attr.target]="resolvedTarget || null"
    [attr.rel]="resolvedRel || null"
    [attr.aria-disabled]="disabled ? 'true' : null"
    [attr.tabindex]="disabled ? -1 : null"
    (click)="onActivate($event)"
  >
    <span class="ids-link-label" data-ids="ids-link-label">{{ resolvedLabel }}</span>
    @if (showExternalLinkIcon) {
      <span
        class="ids-link-external-icon"
        data-ids="ids-link-external-icon"
        aria-hidden="true"
      >
        <ids-icon
          [shape]="externalIconShape"
          [size]="externalIconSize"
          variant="mask"
        />
      </span>
    }
  </a>
} @else {
  <button
    type="button"
    [class]="rootClass"
    data-ids="ids-link"
    [attr.data-type]="resolvedType"
    [attr.data-state]="stateAttr || null"
    [attr.data-external-icon]="showExternalLinkIcon ? 'true' : null"
    [disabled]="disabled"
    [attr.aria-disabled]="disabled ? 'true' : null"
    (click)="onActivate($event)"
  >
    <span class="ids-link-label" data-ids="ids-link-label">{{ resolvedLabel }}</span>
    @if (showExternalLinkIcon) {
      <span
        class="ids-link-external-icon"
        data-ids="ids-link-external-icon"
        aria-hidden="true"
      >
        <ids-icon
          [shape]="externalIconShape"
          [size]="externalIconSize"
          variant="mask"
        />
      </span>
    }
  </button>
}

// lib/react/ids/link/IdsLink.tsx
/**
 * IDS Link — React implementation generated from design-spec.
 *
 * Path: `lib/react/ids/link`
 * Source: `components/ids/link/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * Anatomy:
 *   root (`<a>` | `<button>`)
 *     label
 *     externalIcon?  — lib `IdsIcon` (`pop-up-square-corner-big`, 16px)
 *
 * No @base-ui-components dependency.
 */

import React, {
  forwardRef,
  type AnchorHTMLAttributes,
  type ButtonHTMLAttributes,
  type MouseEvent,
  type ReactElement,
} from "react";
import { IdsIcon } from "../icon";
import styles from "./IdsLink.module.css";

export type IdsLinkType = "standalone" | "inline" | "dark-bg";

export type IdsLinkDataState =
  | "default"
  | "hover"
  | "press"
  | "focus-visible";

export type IdsLinkTarget = "_self" | "_blank" | "_parent" | "_top";

const LINK_TYPES = new Set<IdsLinkType>(["standalone", "inline", "dark-bg"]);

const EXTERNAL_ICON_SHAPE = "pop-up-square-corner-big";

type SharedProps = {
  /** Required visible label. Empty → `"Link"` + development warning. */
  label: string;
  /** Variant axis `Type`. Unknown → `standalone`. */
  type?: IdsLinkType | string;
  /** When set, renders native `<a>`; otherwise button semantics. */
  href?: string;
  showExternalLinkIcon?: boolean;
  target?: IdsLinkTarget;
  /** When `target="_blank"`, defaults to `noopener noreferrer` unless set. */
  rel?: string;
  disabled?: boolean;
  /** Demo/testing visual override only — does not replace interaction logic. */
  dataState?: IdsLinkDataState;
  className?: string;
  onClick?: (
    event: MouseEvent<HTMLAnchorElement | HTMLButtonElement>,
  ) => void;
};

export type IdsLinkProps = SharedProps &
  Omit<
    AnchorHTMLAttributes<HTMLAnchorElement> &
      ButtonHTMLAttributes<HTMLButtonElement>,
    keyof SharedProps | "children" | "type" | "href" | "target" | "rel"
  >;

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

function resolveType(value: unknown): IdsLinkType {
  if (typeof value === "string" && LINK_TYPES.has(value as IdsLinkType)) {
    return value as IdsLinkType;
  }
  return "standalone";
}

function resolveLabel(label: string): string {
  if (label == null || String(label).trim() === "") {
    if (import.meta.env?.DEV) {
      console.warn('IdsLink: empty `label` — rendering fallback text "Link".');
    }
    return "Link";
  }
  return String(label);
}

function resolveRel(
  target: IdsLinkTarget | undefined,
  rel: string | undefined,
): string | undefined {
  if (rel != null) return rel;
  if (target === "_blank") return "noopener noreferrer";
  return undefined;
}

function typeClass(type: IdsLinkType): string {
  return styles[`ids-link--${type}`];
}

export const IdsLink = forwardRef<
  HTMLAnchorElement | HTMLButtonElement,
  IdsLinkProps
>(function IdsLink(
  {
    label: labelProp,
    type: typeProp = "standalone",
    href,
    showExternalLinkIcon = false,
    target = "_self",
    rel: relProp,
    disabled = false,
    dataState,
    className,
    onClick,
    ...rest
  },
  ref,
): ReactElement {
  const type = resolveType(typeProp);
  const label = resolveLabel(labelProp);
  const rel = resolveRel(target, relProp);
  const stateAttr =
    dataState && dataState !== "default" ? dataState : undefined;

  const classNames = cx(
    styles["ids-link"],
    typeClass(type),
    className,
  );

  const handleClick = (
    event: MouseEvent<HTMLAnchorElement | HTMLButtonElement>,
  ) => {
    if (disabled) {
      event.preventDefault();
      return;
    }
    onClick?.(event);
  };

  const icon =
    showExternalLinkIcon ? (
      <span
        className={styles["ids-link-external-icon"]}
        data-ids="ids-link-external-icon"
        aria-hidden="true"
      >
        <IdsIcon shape={EXTERNAL_ICON_SHAPE} size={16} />
      </span>
    ) : null;

  const content = (
    <>
      <span className={styles["ids-link-label"]} data-ids="ids-link-label">
        {label}
      </span>
      {icon}
    </>
  );

  const shared = {
    className: classNames,
    "data-ids": "ids-link" as const,
    "data-type": type,
    "data-state": stateAttr,
    "data-external-icon": showExternalLinkIcon ? ("true" as const) : undefined,
    onClick: handleClick,
  };

  if (href != null && href !== "") {
    return (
      <a
        {...(rest as AnchorHTMLAttributes<HTMLAnchorElement>)}
        {...shared}
        ref={ref as React.Ref<HTMLAnchorElement>}
        href={disabled ? undefined : href}
        target={target === "_self" ? undefined : target}
        rel={rel}
        aria-disabled={disabled || undefined}
        tabIndex={disabled ? -1 : undefined}
      >
        {content}
      </a>
    );
  }

  return (
    <button
      {...(rest as ButtonHTMLAttributes<HTMLButtonElement>)}
      {...shared}
      ref={ref as React.Ref<HTMLButtonElement>}
      type="button"
      disabled={disabled}
      aria-disabled={disabled || undefined}
    >
      {content}
    </button>
  );
});

IdsLink.displayName = "IdsLink";

export default IdsLink;
