// lib/react/ids/date-picker/IdsDatePicker.tsx
/**
 * IDS Date Picker — React implementation from design-spec.
 *
 * Path: `lib/react/ids/date-picker`
 * Source: `components/ids/date-picker/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * No @base-ui-components dependency.
 */

import React, {
  useCallback,
  useEffect,
  useLayoutEffect,
  useMemo,
  useRef,
  useState,
  type CSSProperties,
} from "react";
import { createPortal } from "react-dom";
import { IdsIcon } from "../icon";
import styles from "./IdsDatePicker.module.css";

/** Above DataGrid column filter shell (`filterMenuLayer` z-index 10000). */
const CALENDAR_PORTAL_Z_INDEX = 10050;

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];
const WEEKDAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function getDaysInMonth(year: number, month: number) {
  return new Date(year, month + 1, 0).getDate();
}

function getFirstDayOfWeek(year: number, month: number) {
  return new Date(year, month, 1).getDay();
}

function isSameDay(a: Date | null, b: Date | null) {
  if (!a || !b) return false;
  return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate();
}

function formatDate(d: Date, format: string = "MM-DD-YYYY") {
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  const yyyy = d.getFullYear();

  if (format === "DD/MM/YYYY") {
    return `${dd}/${mm}/${yyyy}`;
  }
  if (format === "YYYY-MM-DD") {
    return `${yyyy}-${mm}-${dd}`;
  }
  // Default: MM-DD-YYYY
  return `${mm}-${dd}-${yyyy}`;
}

function parseDate(s: string, format: string = "MM-DD-YYYY"): Date | null {
  let m: RegExpMatchArray | null;

  if (format === "DD/MM/YYYY") {
    m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
    if (!m) return null;
    const d = new Date(+m[3], +m[2] - 1, +m[1]);
    if (isNaN(d.getTime())) return null;
    return d;
  }
  if (format === "YYYY-MM-DD") {
    m = s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);
    if (!m) return null;
    const d = new Date(+m[1], +m[2] - 1, +m[3]);
    if (isNaN(d.getTime())) return null;
    return d;
  }

  // Default: MM-DD-YYYY
  m = s.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/);
  if (!m) return null;
  const d = new Date(+m[3], +m[1] - 1, +m[2]);
  if (isNaN(d.getTime())) return null;
  return d;
}

export interface IdsDatePickerProps {
  value?: Date | null;
  onChange?: (d: Date | null) => void;
  size?: "large" | "small";
  placeholder?: string;
  label?: string;
  required?: boolean;
  /** Date format for input text display/parsing (e.g., "MM-DD-YYYY", "DD/MM/YYYY", "YYYY-MM-DD"). Default: "MM-DD-YYYY". */
  dateFormat?: string;
  /** Date format hint displayed below the input (e.g. "MM-DD-YYYY"). Always shown unless empty string. */
  formatHint?: string;
  helperText?: string;
  disabled?: boolean;
  error?: boolean;
  errorMessage?: string;
  minDate?: Date;
  maxDate?: Date;
  disabledDates?: Date[];
  /** Enable date range selection (two-click model) */
  rangeMode?: boolean;
  /** Controlled range start date */
  rangeStart?: Date | null;
  /** Controlled range end date */
  rangeEnd?: Date | null;
  /** Callback when range start or end changes */
  onRangeChange?: (start: Date | null, end: Date | null) => void;
  /** Force-open state for Storybook demos */
  forceOpen?: boolean;
  /** Force selected-with-dropdown visual (demo only) */
  forceState?: string;
  /**
   * Render the calendar in `document.body` with fixed positioning so it is not clipped
   * by overflow/stacking contexts (e.g. DataGrid filter panels). Default: true.
   */
  popupPortal?: boolean;
}

export function IdsDatePicker({
  value = null,
  onChange,
  size = "large",
  placeholder,
  label,
  required = false,
  dateFormat = "MM-DD-YYYY",
  formatHint = "MM-DD-YYYY",
  helperText,
  disabled = false,
  error = false,
  errorMessage,
  minDate,
  maxDate,
  disabledDates = [],
  rangeMode = false,
  rangeStart: controlledRangeStart,
  rangeEnd: controlledRangeEnd,
  onRangeChange,
  forceOpen,
  forceState,
  popupPortal = true,
}: IdsDatePickerProps) {
  const today = useMemo(() => new Date(), []);
  const [internalValue, setInternalValue] = useState<Date | null>(value);
  const [open, setOpen] = useState(forceOpen ?? false);
  const [inputText, setInputText] = useState(value ? formatDate(value, dateFormat) : "");
  const [viewMonth, setViewMonth] = useState(value?.getMonth() ?? today.getMonth());
  const [viewYear, setViewYear] = useState(value?.getFullYear() ?? today.getFullYear());
  const effectivePlaceholder = placeholder ?? dateFormat;
  const [monthDropdownOpen, setMonthDropdownOpen] = useState(false);
  const [yearDropdownOpen, setYearDropdownOpen] = useState(false);

  const [internalRangeStart, setInternalRangeStart] = useState<Date | null>(controlledRangeStart ?? null);
  const [internalRangeEnd, setInternalRangeEnd] = useState<Date | null>(controlledRangeEnd ?? null);
  const [hoverDate, setHoverDate] = useState<Date | null>(null);

  const rangeStart = controlledRangeStart !== undefined ? controlledRangeStart : internalRangeStart;
  const rangeEnd = controlledRangeEnd !== undefined ? controlledRangeEnd : internalRangeEnd;

  const rootRef = useRef<HTMLDivElement>(null);
  const anchorRef = useRef<HTMLDivElement>(null);
  const calendarPopupRef = useRef<HTMLDivElement>(null);
  const [calendarPos, setCalendarPos] = useState<{ top: number; left: number } | null>(null);
  const [mouseActivated, setMouseActivated] = useState(false);

  useEffect(() => {
    if (value !== undefined) {
      setInternalValue(value);
      setInputText(value ? formatDate(value, dateFormat) : "");
    }
  }, [value, dateFormat]);

  useEffect(() => {
    if (forceOpen !== undefined) setOpen(forceOpen);
  }, [forceOpen]);

  const selectedDate = internalValue;

  const selectDate = useCallback(
    (d: Date) => {
      if (rangeMode) {
        if (!rangeStart || (rangeStart && rangeEnd)) {
          setInternalRangeStart(d);
          setInternalRangeEnd(null);
          setHoverDate(null);
          onRangeChange?.(d, null);
        } else {
          setInternalRangeEnd(d);
          setHoverDate(null);
          onRangeChange?.(rangeStart, d);
        }
        return;
      }
      setInternalValue(d);
      setInputText(formatDate(d, dateFormat));
      setOpen(false);
      onChange?.(d);
    },
    [onChange, rangeMode, rangeStart, rangeEnd, onRangeChange, dateFormat],
  );

  const isInRange = useCallback(
    (d: Date) => {
      if (!rangeMode || !rangeStart) return false;
      const effectiveEnd = rangeEnd || hoverDate;
      if (!effectiveEnd) return false;
      const start = rangeStart.getTime();
      const end = effectiveEnd.getTime();
      const t = d.getTime();
      const lo = Math.min(start, end);
      const hi = Math.max(start, end);
      return t >= lo && t <= hi;
    },
    [rangeMode, rangeStart, rangeEnd, hoverDate],
  );

  const isRangeEndpoint = useCallback(
    (d: Date, which: "start" | "end") => {
      if (!rangeMode || !rangeStart) return false;
      const effectiveEnd = rangeEnd || hoverDate;
      if (!effectiveEnd) return which === "start" && isSameDay(d, rangeStart);
      const lo = rangeStart.getTime() <= effectiveEnd.getTime() ? rangeStart : effectiveEnd;
      const hi = rangeStart.getTime() <= effectiveEnd.getTime() ? effectiveEnd : rangeStart;
      if (which === "start") return isSameDay(d, lo);
      return isSameDay(d, hi);
    },
    [rangeMode, rangeStart, rangeEnd, hoverDate],
  );

  const isDateDisabled = useCallback(
    (d: Date) => {
      if (minDate && d < minDate) return true;
      if (maxDate && d > maxDate) return true;
      return disabledDates.some((dd) => isSameDay(dd, d));
    },
    [minDate, maxDate, disabledDates],
  );

  const computeRangeBar = useCallback(
    (row: { day: number; month: number; year: number }[]) => {
      if (!rangeMode || !rangeStart) return null;
      const effectiveEnd = rangeEnd || hoverDate;
      if (!effectiveEnd) return null;

      const lo = Math.min(rangeStart.getTime(), effectiveEnd.getTime());
      const hi = Math.max(rangeStart.getTime(), effectiveEnd.getTime());

      let firstIdx = -1;
      let lastIdx = -1;
      for (let i = 0; i < row.length; i++) {
        const t = new Date(row[i].year, row[i].month, row[i].day).getTime();
        if (t >= lo && t <= hi) {
          if (firstIdx === -1) firstIdx = i;
          lastIdx = i;
        }
      }
      if (firstIdx === -1) return null;

      const cellSize = 32;
      const gap = 4;
      const count = lastIdx - firstIdx + 1;
      const left = firstIdx * (cellSize + gap);
      const width = count * cellSize + (count - 1) * gap;
      const isForward = rangeStart.getTime() <= (effectiveEnd.getTime());
      const isFullRow = firstIdx === 0 && lastIdx === 6;

      return { left, width, isForward, isFullRow };
    },
    [rangeMode, rangeStart, rangeEnd, hoverDate],
  );

  const calendarGrid = useMemo(() => {
    const daysInMonth = getDaysInMonth(viewYear, viewMonth);
    const firstDay = getFirstDayOfWeek(viewYear, viewMonth);
    const prevMonthDays = getDaysInMonth(viewYear, viewMonth - 1);
    const rows: { day: number; month: number; year: number; type: "prev" | "current" | "next" }[][] = [];
    let row: typeof rows[number] = [];

    for (let i = 0; i < firstDay; i++) {
      const d = prevMonthDays - firstDay + 1 + i;
      const m = viewMonth === 0 ? 11 : viewMonth - 1;
      const y = viewMonth === 0 ? viewYear - 1 : viewYear;
      row.push({ day: d, month: m, year: y, type: "prev" });
    }

    for (let d = 1; d <= daysInMonth; d++) {
      row.push({ day: d, month: viewMonth, year: viewYear, type: "current" });
      if (row.length === 7) {
        rows.push(row);
        row = [];
      }
    }

    if (row.length > 0) {
      let nextDay = 1;
      const nm = viewMonth === 11 ? 0 : viewMonth + 1;
      const ny = viewMonth === 11 ? viewYear + 1 : viewYear;
      while (row.length < 7) {
        row.push({ day: nextDay++, month: nm, year: ny, type: "next" });
      }
      rows.push(row);
    }

    while (rows.length < 6) {
      const lastRow = rows[rows.length - 1];
      const lastCell = lastRow[lastRow.length - 1];
      let startDay = lastCell.day + 1;
      let nm = lastCell.month;
      let ny = lastCell.year;
      const daysInThatMonth = getDaysInMonth(ny, nm);
      if (startDay > daysInThatMonth) {
        startDay = 1;
        nm = nm === 11 ? 0 : nm + 1;
        ny = nm === 0 ? ny + 1 : ny;
      }
      const newRow: typeof rows[number] = [];
      for (let i = 0; i < 7; i++) {
        const ddim = getDaysInMonth(ny, nm);
        if (startDay > ddim) {
          startDay = 1;
          nm = nm === 11 ? 0 : nm + 1;
          ny = nm === 0 ? ny + 1 : ny;
        }
        newRow.push({ day: startDay++, month: nm, year: ny, type: "next" });
      }
      rows.push(newRow);
    }

    return rows;
  }, [viewYear, viewMonth]);

  const handleInputBlur = () => {
    if (inputText.trim()) {
      const d = parseDate(inputText, dateFormat);
      if (d && !isDateDisabled(d)) {
        selectDate(d);
        setViewMonth(d.getMonth());
        setViewYear(d.getFullYear());
      }
    }
  };

  const updateCalendarPosition = useCallback(() => {
    const anchor = anchorRef.current;
    if (!anchor) return;
    const rect = anchor.getBoundingClientRect();
    const popup = calendarPopupRef.current;
    const popupWidth = popup?.offsetWidth ?? 280;
    const popupHeight = popup?.offsetHeight ?? 340;
    const margin = 8;
    let top = rect.bottom - 1;
    let left = rect.right - popupWidth;
    left = Math.max(margin, Math.min(left, window.innerWidth - popupWidth - margin));
    if (top + popupHeight > window.innerHeight - margin) {
      const above = rect.top - popupHeight + 1;
      if (above >= margin) top = above;
    }
    setCalendarPos({ top, left });
  }, []);

  useLayoutEffect(() => {
    if (!open || !popupPortal) {
      setCalendarPos(null);
      return;
    }

    let cancelled = false;
    const run = () => {
      if (cancelled) return;
      updateCalendarPosition();
    };

    run();
    const raf = requestAnimationFrame(() => {
      run();
      requestAnimationFrame(run);
    });

    const onWin = () => run();
    window.addEventListener("resize", onWin);
    window.addEventListener("scroll", onWin, true);

    return () => {
      cancelled = true;
      cancelAnimationFrame(raf);
      window.removeEventListener("resize", onWin);
      window.removeEventListener("scroll", onWin, true);
    };
  }, [open, popupPortal, updateCalendarPosition, viewMonth, viewYear, monthDropdownOpen, yearDropdownOpen]);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      const target = e.target as Node;
      if (rootRef.current?.contains(target)) return;
      if (calendarPopupRef.current?.contains(target)) return;
      setOpen(false);
      setMonthDropdownOpen(false);
      setYearDropdownOpen(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Escape" && open) {
      setOpen(false);
      setMonthDropdownOpen(false);
      setYearDropdownOpen(false);
    }
  };

  const fieldClasses = [
    styles.fieldContainer,
    size === "large" ? styles.sizeLarge : styles.sizeSmall,
    disabled ? styles.disabled : "",
    error ? styles.error : "",
    open ? styles.open : "",
    mouseActivated ? styles.mouseActivated : "",
  ]
    .filter(Boolean)
    .join(" ");

  const yearRange = useMemo(() => {
    const start = viewYear - 3;
    return Array.from({ length: 7 }, (_, i) => start + i);
  }, [viewYear]);

  const calendarPopupClasses = [
    styles.calendarPopup,
    popupPortal ? styles.calendarPopupPortaled : "",
  ]
    .filter(Boolean)
    .join(" ");

  const calendarPopupStyle: CSSProperties | undefined =
    popupPortal && calendarPos
      ? { top: calendarPos.top, left: calendarPos.left, zIndex: CALENDAR_PORTAL_Z_INDEX }
      : popupPortal
        ? { visibility: "hidden" as const }
        : undefined;

  const calendarPopup = open && !disabled && (
    <div
      ref={calendarPopupRef}
      className={calendarPopupClasses}
      style={calendarPopupStyle}
      role="dialog"
      aria-modal="true"
      aria-label="Choose date"
    >
      <div className={styles.calendarHeader}>
        <div className={styles.headerDropdowns}>
          <button
            type="button"
            className={`${styles.dropdownButton}${monthDropdownOpen ? ` ${styles.menuOpen}` : ""}`}
            onClick={() => {
              setMonthDropdownOpen((v) => !v);
              setYearDropdownOpen(false);
            }}
          >
            {MONTH_NAMES[viewMonth]}
            <IdsIcon shape="arrow-drop-tri-caret" className={styles.caretIcon} size={10} />
            {monthDropdownOpen && (
              <div className={styles.overlayDropdown}>
                {MONTH_NAMES.map((name, i) => (
                  <button
                    key={name}
                    type="button"
                    className={`${styles.overlayOption} ${i === viewMonth ? styles.selectedOption : ""}`}
                    onClick={(e) => {
                      e.stopPropagation();
                      setViewMonth(i);
                      setMonthDropdownOpen(false);
                    }}
                  >
                    {name}
                  </button>
                ))}
              </div>
            )}
          </button>
          <button
            type="button"
            className={`${styles.dropdownButton} ${styles.yearBtn}${yearDropdownOpen ? ` ${styles.menuOpen}` : ""}`}
            onClick={() => {
              setYearDropdownOpen((v) => !v);
              setMonthDropdownOpen(false);
            }}
          >
            {viewYear}
            <IdsIcon shape="arrow-drop-tri-caret" className={styles.caretIcon} size={10} />
            {yearDropdownOpen && (
              <div className={styles.overlayDropdown}>
                {yearRange.map((yr) => (
                  <button
                    key={yr}
                    type="button"
                    className={`${styles.overlayOption} ${yr === viewYear ? styles.selectedOption : ""}`}
                    onClick={(e) => {
                      e.stopPropagation();
                      setViewYear(yr);
                      setYearDropdownOpen(false);
                    }}
                  >
                    {yr}
                  </button>
                ))}
              </div>
            )}
          </button>
        </div>

        <div className={styles.navButtons}>
          <button
            type="button"
            className={styles.navBtn}
            onClick={() => {
              if (viewMonth === 0) {
                setViewMonth(11);
                setViewYear((y) => y - 1);
              } else {
                setViewMonth((m) => m - 1);
              }
            }}
            aria-label="Previous month"
          >
            <IdsIcon shape="chev-left-thick" className={styles.navIcon} size={12} />
          </button>
          <button
            type="button"
            className={styles.navBtn}
            onClick={() => {
              if (viewMonth === 11) {
                setViewMonth(0);
                setViewYear((y) => y + 1);
              } else {
                setViewMonth((m) => m + 1);
              }
            }}
            aria-label="Next month"
          >
            <IdsIcon shape="chev-right-thick" className={styles.navIcon} size={12} />
          </button>
        </div>
      </div>

      <div className={styles.dateSection}>
        <div className={styles.dateContent} role="grid" aria-label="Calendar">
          <div className={styles.weekDayRow}>
            {WEEKDAYS.map((d) => (
              <span key={d} className={styles.weekDayLabel}>
                {d}
              </span>
            ))}
          </div>
          <div className={styles.dateGrid}>
            {calendarGrid.map((row, ri) => {
              const bar = computeRangeBar(row);
              return (
                <div key={ri} className={styles.dateRow} role="row">
                  {bar && (
                    <div
                      className={`${styles.rangeBar} ${bar.isFullRow ? styles.fullRow : bar.isForward ? styles.forward : styles.reverse}`}
                      style={{ left: bar.left, width: bar.width }}
                    />
                  )}
                  {row.map((cell, ci) => {
                    const cellDate = new Date(cell.year, cell.month, cell.day);
                    const isUnavailable = isDateDisabled(cellDate);
                    const isSelected =
                      !isUnavailable &&
                      (rangeMode
                        ? isRangeEndpoint(cellDate, "start") || isRangeEndpoint(cellDate, "end")
                        : isSameDay(cellDate, selectedDate));
                    const isToday = isSameDay(cellDate, today);
                    const isAdjacentMonth = cell.type !== "current";
                    const inRange = !isUnavailable && isInRange(cellDate);
                    const cellClasses = [
                      styles.dateCell,
                      isSelected ? styles.selected : "",
                      isUnavailable ? styles.unavailable : "",
                      rangeMode && !isUnavailable && isRangeEndpoint(cellDate, "start")
                        ? styles.rangeStart
                        : "",
                      rangeMode && !isUnavailable && isRangeEndpoint(cellDate, "end")
                        ? styles.rangeEnd
                        : "",
                    ]
                      .filter(Boolean)
                      .join(" ");

                    return (
                      <div
                        key={ci}
                        className={cellClasses}
                        role="gridcell"
                        aria-selected={isSelected || inRange}
                        aria-disabled={isUnavailable}
                        tabIndex={isUnavailable ? -1 : 0}
                        onClick={() => {
                          if (isUnavailable) return;
                          if (isAdjacentMonth) {
                            setViewMonth(cell.month);
                            setViewYear(cell.year);
                          }
                          selectDate(cellDate);
                        }}
                        onMouseEnter={() => {
                          if (rangeMode && rangeStart && !rangeEnd && !isUnavailable) {
                            setHoverDate(cellDate);
                          }
                        }}
                        onMouseLeave={() => {
                          if (rangeMode) setHoverDate(null);
                        }}
                        onKeyDown={(e) => {
                          if ((e.key === "Enter" || e.key === " ") && !isUnavailable) {
                            e.preventDefault();
                            if (isAdjacentMonth) {
                              setViewMonth(cell.month);
                              setViewYear(cell.year);
                            }
                            selectDate(cellDate);
                          }
                        }}
                      >
                        <div
                          className={`${styles.dateCellContainer} ${isToday ? styles.todayType : ""}`}
                        >
                          <span
                            className={`${styles.dateLabel} ${isAdjacentMonth ? styles.adjacentMonth : ""}`}
                          >
                            {cell.day}
                          </span>
                          {isToday && <div className={styles.todayIndicator} />}
                        </div>
                        <div className={styles.focusRing} />
                      </div>
                    );
                  })}
                </div>
              );
            })}
          </div>
        </div>
        <button
          type="button"
          className={styles.todayLink}
          onClick={() => {
            setViewMonth(today.getMonth());
            setViewYear(today.getFullYear());
            selectDate(today);
          }}
        >
          Today
        </button>
      </div>
    </div>
  );

  return (
    <div className={styles.root} ref={rootRef} onKeyDown={handleKeyDown}>
      {label && (
        <div className={`${styles.label}${size === "small" ? ` ${styles.labelSmall}` : ""}`}>
          <div className={styles.labelInner}>
            <span className={styles.labelText}>{label}</span>
            {required && <span className={styles.labelRequired}>*</span>}
          </div>
        </div>
      )}
      <div className={styles.inputGroup}>
        <div className={styles.positionWrapper} ref={anchorRef}>
          <div className={fieldClasses}>
            <input
              type="text"
              className={styles.textInput}
              placeholder={effectivePlaceholder}
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              onMouseDown={() => setMouseActivated(true)}
              onBlur={() => { setMouseActivated(false); handleInputBlur(); }}
              disabled={disabled}
              aria-label={label || "Date"}
            />
            <button
              type="button"
              className={`${styles.calendarIconBtn} ${error ? styles.error : ""}`}
              onClick={() => {
                if (!disabled) setOpen((v) => !v);
              }}
              disabled={disabled}
              aria-label="Open calendar"
              aria-expanded={open}
            >
              <IdsIcon shape="calendar-simple-16" size={16} />
            </button>
          </div>

          {!popupPortal && calendarPopup}
          {popupPortal &&
            open &&
            !disabled &&
            typeof document !== "undefined" &&
            calendarPopup &&
            createPortal(calendarPopup, document.body)}
        </div>
        {formatHint && !error && <span className={styles.formatHint}>{formatHint}</span>}
        {error && errorMessage && (
          <span className={styles.errorMessage}>
            <IdsIcon
              shape="status-critical-square-solid"
              variant="img"
              size={16}
              style={{ flexShrink: 0 }}
            />
            {errorMessage}
          </span>
        )}
      </div>
    </div>
  );
}

export default IdsDatePicker;

// lib/angular/ids/date-picker/ids-date-picker.component.ts
/**
 * IDS Date Picker — Angular port of `lib/react/ids/date-picker`.
 * Source: `components/ids/date-picker/design-spec.md`
 */
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewChild,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { DATE_PICKER_SPEC_ACCURATE_DEFAULTS, type DatePickerSize } from "@component-contracts/ids/date-picker.contract";
import { IdsIconComponent } from "../icon/ids-icon.component";
import { cx } from "../../shared/utils/cx";
import {
  buildCalendarGrid,
  formatDate,
  isSameDay,
  MONTH_NAMES,
  parseDate,
  WEEKDAYS,
  type CalendarCell,
  type RangeBarLayout,
} from "./ids-date-picker.utils";

const CALENDAR_PORTAL_Z_INDEX = 10050;

@Component({
  selector: "ids-date-picker",
  standalone: true,
  imports: [CommonModule, IdsIconComponent],
  templateUrl: "./ids-date-picker.component.html",
  styleUrl: "./ids-date-picker.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsDatePickerComponent implements OnChanges {
  @Input() value: Date | null = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.value;
  @Input() size: DatePickerSize = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.size;
  @Input() placeholder?: string;
  @Input() label?: string;
  @Input() required = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.required;
  @Input() dateFormat: string = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.dateFormat;
  @Input() formatHint: string = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.formatHint;
  @Input() helperText?: string;
  @Input() disabled = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.disabled;
  @Input() error = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.error;
  @Input() errorMessage?: string;
  @Input() minDate?: Date;
  @Input() maxDate?: Date;
  @Input() disabledDates: Date[] = [];
  @Input() rangeMode = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.rangeMode;
  @Input() rangeStart?: Date | null;
  @Input() rangeEnd?: Date | null;
  @Input() forceOpen?: boolean;
  @Input() forceState?: string;
  @Input() popupPortal = DATE_PICKER_SPEC_ACCURATE_DEFAULTS.popupPortal;

  @Output() readonly onChange = new EventEmitter<Date | null>();
  @Output() readonly onRangeChange = new EventEmitter<{ start: Date | null; end: Date | null }>();

  readonly monthNames = MONTH_NAMES;
  readonly weekdays = WEEKDAYS;
  readonly today = new Date();

  internalValue: Date | null = this.value;
  open = this.forceOpen ?? false;
  inputText = this.value ? formatDate(this.value, this.dateFormat) : "";
  viewMonth = this.value?.getMonth() ?? this.today.getMonth();
  viewYear = this.value?.getFullYear() ?? this.today.getFullYear();
  monthDropdownOpen = false;
  yearDropdownOpen = false;
  internalRangeStart: Date | null = this.rangeStart ?? null;
  internalRangeEnd: Date | null = this.rangeEnd ?? null;
  hoverDate: Date | null = null;
  mouseActivated = false;
  calendarPos: { top: number; left: number } | null = null;

  @ViewChild("rootRef") rootRef?: ElementRef<HTMLElement>;
  @ViewChild("anchorRef") anchorRef?: ElementRef<HTMLElement>;
  @ViewChild("calendarPopupRef") calendarPopupRef?: ElementRef<HTMLElement>;

  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"] || changes["dateFormat"]) {
      this.internalValue = this.value;
      this.inputText = this.value ? formatDate(this.value, this.dateFormat) : "";
    }
    if (changes["forceOpen"] && this.forceOpen === true) {
      this.open = true;
    }
    if (changes["rangeStart"] && this.rangeStart !== undefined) {
      this.internalRangeStart = this.rangeStart;
    }
    if (changes["rangeEnd"] && this.rangeEnd !== undefined) {
      this.internalRangeEnd = this.rangeEnd;
    }
  }

  get effectivePlaceholder(): string {
    return this.placeholder ?? this.dateFormat;
  }

  get resolvedRangeStart(): Date | null {
    return this.rangeStart !== undefined ? this.rangeStart : this.internalRangeStart;
  }

  get resolvedRangeEnd(): Date | null {
    return this.rangeEnd !== undefined ? this.rangeEnd : this.internalRangeEnd;
  }

  get calendarGrid(): CalendarCell[][] {
    return buildCalendarGrid(this.viewYear, this.viewMonth);
  }

  get yearRange(): number[] {
    const start = this.viewYear - 3;
    return Array.from({ length: 7 }, (_, i) => start + i);
  }

  get fieldClasses(): string {
    return cx(
      "fieldContainer",
      this.size === "large" ? "sizeLarge" : "sizeSmall",
      this.disabled && "disabled",
      this.error && "error",
      this.open && "open",
      this.mouseActivated && "mouseActivated",
    );
  }

  get calendarPopupClasses(): string {
    return cx("calendarPopup", this.popupPortal && "calendarPopupPortaled");
  }

  get calendarPopupStyle(): Record<string, string> | null {
    if (!this.popupPortal || !this.calendarPos) return null;
    return {
      top: `${this.calendarPos.top}px`,
      left: `${this.calendarPos.left}px`,
      zIndex: String(CALENDAR_PORTAL_Z_INDEX),
    };
  }

  isDateDisabled(d: Date): boolean {
    if (this.minDate && d < this.minDate) return true;
    if (this.maxDate && d > this.maxDate) return true;
    return this.disabledDates.some((dd) => isSameDay(dd, d));
  }

  isInRange(d: Date): boolean {
    if (!this.rangeMode || !this.resolvedRangeStart) return false;
    const effectiveEnd = this.resolvedRangeEnd || this.hoverDate;
    if (!effectiveEnd) return false;
    const start = this.resolvedRangeStart.getTime();
    const end = effectiveEnd.getTime();
    const t = d.getTime();
    return t >= Math.min(start, end) && t <= Math.max(start, end);
  }

  isRangeEndpoint(d: Date, which: "start" | "end"): boolean {
    if (!this.rangeMode || !this.resolvedRangeStart) return false;
    const effectiveEnd = this.resolvedRangeEnd || this.hoverDate;
    if (!effectiveEnd) return which === "start" && isSameDay(d, this.resolvedRangeStart);
    const lo = this.resolvedRangeStart.getTime() <= effectiveEnd.getTime() ? this.resolvedRangeStart : effectiveEnd;
    const hi = this.resolvedRangeStart.getTime() <= effectiveEnd.getTime() ? effectiveEnd : this.resolvedRangeStart;
    if (which === "start") return isSameDay(d, lo);
    return isSameDay(d, hi);
  }

  computeRangeBar(row: CalendarCell[]): RangeBarLayout | null {
    if (!this.rangeMode || !this.resolvedRangeStart) return null;
    const effectiveEnd = this.resolvedRangeEnd || this.hoverDate;
    if (!effectiveEnd) return null;

    const lo = Math.min(this.resolvedRangeStart.getTime(), effectiveEnd.getTime());
    const hi = Math.max(this.resolvedRangeStart.getTime(), effectiveEnd.getTime());

    let firstIdx = -1;
    let lastIdx = -1;
    for (let i = 0; i < row.length; i++) {
      const t = new Date(row[i].year, row[i].month, row[i].day).getTime();
      if (t >= lo && t <= hi) {
        if (firstIdx === -1) firstIdx = i;
        lastIdx = i;
      }
    }
    if (firstIdx === -1) return null;

    const cellSize = 32;
    const gap = 4;
    const count = lastIdx - firstIdx + 1;
    const left = firstIdx * (cellSize + gap);
    const width = count * cellSize + (count - 1) * gap;
    const isForward = this.resolvedRangeStart.getTime() <= effectiveEnd.getTime();
    const isFullRow = firstIdx === 0 && lastIdx === 6;
    return { left, width, isForward, isFullRow };
  }

  cellClasses(cell: CalendarCell): string {
    const cellDate = new Date(cell.year, cell.month, cell.day);
    const unavailable = this.isDateDisabled(cellDate);
    const selected =
      !unavailable &&
      (this.rangeMode
        ? this.isRangeEndpoint(cellDate, "start") || this.isRangeEndpoint(cellDate, "end")
        : isSameDay(cellDate, this.internalValue));
    return cx(
      "dateCell",
      selected && "selected",
      unavailable && "unavailable",
      this.rangeMode && !unavailable && this.isRangeEndpoint(cellDate, "start") && "rangeStart",
      this.rangeMode && !unavailable && this.isRangeEndpoint(cellDate, "end") && "rangeEnd",
    );
  }

  cellDate(cell: CalendarCell): Date {
    return new Date(cell.year, cell.month, cell.day);
  }

  isToday(cell: CalendarCell): boolean {
    return isSameDay(this.cellDate(cell), this.today);
  }

  isAdjacentMonth(cell: CalendarCell): boolean {
    return cell.type !== "current";
  }

  cellAriaSelected(cell: CalendarCell): boolean {
    const d = this.cellDate(cell);
    const unavailable = this.isDateDisabled(d);
    const selected =
      !unavailable &&
      (this.rangeMode
        ? this.isRangeEndpoint(d, "start") || this.isRangeEndpoint(d, "end")
        : isSameDay(d, this.internalValue));
    return selected || (!unavailable && this.isInRange(d));
  }

  selectDate(d: Date): void {
    if (this.rangeMode) {
      if (!this.resolvedRangeStart || (this.resolvedRangeStart && this.resolvedRangeEnd)) {
        this.internalRangeStart = d;
        this.internalRangeEnd = null;
        this.hoverDate = null;
        this.onRangeChange.emit({ start: d, end: null });
      } else {
        this.internalRangeEnd = d;
        this.hoverDate = null;
        this.onRangeChange.emit({ start: this.resolvedRangeStart, end: d });
      }
      this.cdr.markForCheck();
      return;
    }
    this.internalValue = d;
    this.inputText = formatDate(d, this.dateFormat);
    this.open = false;
    this.onChange.emit(d);
    this.cdr.markForCheck();
  }

  onCellClick(cell: CalendarCell): void {
    const cellDate = this.cellDate(cell);
    if (this.isDateDisabled(cellDate)) return;
    if (this.isAdjacentMonth(cell)) {
      this.viewMonth = cell.month;
      this.viewYear = cell.year;
    }
    this.selectDate(cellDate);
  }

  onCellMouseEnter(cell: CalendarCell): void {
    const cellDate = this.cellDate(cell);
    if (this.rangeMode && this.resolvedRangeStart && !this.resolvedRangeEnd && !this.isDateDisabled(cellDate)) {
      this.hoverDate = cellDate;
    }
  }

  onCellMouseLeave(): void {
    if (this.rangeMode) this.hoverDate = null;
  }

  onCellKeyDown(event: KeyboardEvent, cell: CalendarCell): void {
    if ((event.key === "Enter" || event.key === " ") && !this.isDateDisabled(this.cellDate(cell))) {
      event.preventDefault();
      this.onCellClick(cell);
    }
  }

  handleInputBlur(): void {
    this.mouseActivated = false;
    if (this.inputText.trim()) {
      const d = parseDate(this.inputText, this.dateFormat);
      if (d && !this.isDateDisabled(d)) {
        this.selectDate(d);
        this.viewMonth = d.getMonth();
        this.viewYear = d.getFullYear();
      }
    }
  }

  toggleOpen(event?: Event): void {
    event?.stopPropagation();
    if (this.disabled || this.forceOpen === true) return;
    this.open = !this.open;
    if (!this.open) {
      this.monthDropdownOpen = false;
      this.yearDropdownOpen = false;
    } else {
      queueMicrotask(() => this.updateCalendarPosition());
    }
    this.cdr.markForCheck();
  }

  handleRootKeyDown(event: KeyboardEvent): void {
    if (event.key === "Escape" && this.open) {
      this.open = false;
      this.monthDropdownOpen = false;
      this.yearDropdownOpen = false;
    }
  }

  toggleMonthDropdown(): void {
    this.monthDropdownOpen = !this.monthDropdownOpen;
    this.yearDropdownOpen = false;
  }

  toggleYearDropdown(): void {
    this.yearDropdownOpen = !this.yearDropdownOpen;
    this.monthDropdownOpen = false;
  }

  selectMonth(index: number, event: Event): void {
    event.stopPropagation();
    this.viewMonth = index;
    this.monthDropdownOpen = false;
  }

  selectYear(year: number, event: Event): void {
    event.stopPropagation();
    this.viewYear = year;
    this.yearDropdownOpen = false;
  }

  prevMonth(): void {
    if (this.viewMonth === 0) {
      this.viewMonth = 11;
      this.viewYear -= 1;
    } else {
      this.viewMonth -= 1;
    }
  }

  nextMonth(): void {
    if (this.viewMonth === 11) {
      this.viewMonth = 0;
      this.viewYear += 1;
    } else {
      this.viewMonth += 1;
    }
  }

  goToday(): void {
    this.viewMonth = this.today.getMonth();
    this.viewYear = this.today.getFullYear();
    this.selectDate(this.today);
  }

  onInput(event: Event): void {
    this.inputText = (event.target as HTMLInputElement).value;
  }

  updateCalendarPosition(): void {
    const anchor = this.anchorRef?.nativeElement;
    if (!anchor || !this.popupPortal) return;
    const rect = anchor.getBoundingClientRect();
    const popup = this.calendarPopupRef?.nativeElement;
    const popupWidth = popup?.offsetWidth ?? 280;
    const popupHeight = popup?.offsetHeight ?? 340;
    const margin = 8;
    let top = rect.bottom - 1;
    let left = rect.right - popupWidth;
    left = Math.max(margin, Math.min(left, window.innerWidth - popupWidth - margin));
    if (top + popupHeight > window.innerHeight - margin) {
      const above = rect.top - popupHeight + 1;
      if (above >= margin) top = above;
    }
    if (this.calendarPos?.top === top && this.calendarPos?.left === left) return;
    this.calendarPos = { top, left };
    this.cdr.markForCheck();
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMouseDown(event: MouseEvent): void {
    if (!this.open || this.forceOpen === true) return;
    const target = event.target as Node;
    if (this.rootRef?.nativeElement.contains(target)) return;
    if (this.calendarPopupRef?.nativeElement.contains(target)) return;
    this.open = false;
    this.monthDropdownOpen = false;
    this.yearDropdownOpen = false;
    this.cdr.markForCheck();
  }

  @HostListener("window:resize")
  @HostListener("window:scroll")
  onWinChange(): void {
    if (this.open && this.popupPortal) this.updateCalendarPosition();
  }
}

<div class="root" #rootRef (keydown)="handleRootKeyDown($event)">
  @if (label) {
    <div class="label" [class.labelSmall]="size === 'small'">
      <div class="labelInner">
        <span class="labelText">{{ label }}</span>
        @if (required) {
          <span class="labelRequired">*</span>
        }
      </div>
    </div>
  }
  <div class="inputGroup">
    <div class="positionWrapper" #anchorRef>
      <div [class]="fieldClasses">
        <input
          type="text"
          class="textInput"
          [placeholder]="effectivePlaceholder"
          [value]="inputText"
          [disabled]="disabled"
          [attr.aria-label]="label || 'Date'"
          (input)="onInput($event)"
          (mousedown)="mouseActivated = true"
          (blur)="handleInputBlur()"
        />
        <button
          type="button"
          class="calendarIconBtn"
          [class.error]="error"
          [disabled]="disabled"
          aria-label="Open calendar"
          [attr.aria-expanded]="open"
          (mousedown)="$event.stopPropagation()"
          (click)="toggleOpen($event)"
        >
          <ids-icon shape="calendar-simple-16" [size]="16" />
        </button>
      </div>

      @if (open && !disabled) {
        <div
          #calendarPopupRef
          [class]="calendarPopupClasses"
          [ngStyle]="calendarPopupStyle"
          role="dialog"
          aria-modal="true"
          aria-label="Choose date"
        >
          <div class="calendarHeader">
            <div class="headerDropdowns">
              <button
                type="button"
                class="dropdownButton"
                [class.menuOpen]="monthDropdownOpen"
                (click)="toggleMonthDropdown()"
              >
                {{ monthNames[viewMonth] }}
                <ids-icon shape="arrow-drop-tri-caret" className="caretIcon" [size]="10" />
                @if (monthDropdownOpen) {
                  <div class="overlayDropdown">
                    @for (name of monthNames; track name; let i = $index) {
                      <button
                        type="button"
                        class="overlayOption"
                        [class.selectedOption]="i === viewMonth"
                        (click)="selectMonth(i, $event)"
                      >
                        {{ name }}
                      </button>
                    }
                  </div>
                }
              </button>
              <button
                type="button"
                class="dropdownButton yearBtn"
                [class.menuOpen]="yearDropdownOpen"
                (click)="toggleYearDropdown()"
              >
                {{ viewYear }}
                <ids-icon shape="arrow-drop-tri-caret" className="caretIcon" [size]="10" />
                @if (yearDropdownOpen) {
                  <div class="overlayDropdown">
                    @for (yr of yearRange; track yr) {
                      <button
                        type="button"
                        class="overlayOption"
                        [class.selectedOption]="yr === viewYear"
                        (click)="selectYear(yr, $event)"
                      >
                        {{ yr }}
                      </button>
                    }
                  </div>
                }
              </button>
            </div>
            <div class="navButtons">
              <button type="button" class="navBtn" aria-label="Previous month" (click)="prevMonth()">
                <ids-icon shape="chev-left-thick" className="navIcon" [size]="12" />
              </button>
              <button type="button" class="navBtn" aria-label="Next month" (click)="nextMonth()">
                <ids-icon shape="chev-right-thick" className="navIcon" [size]="12" />
              </button>
            </div>
          </div>

          <div class="dateSection">
            <div class="dateContent" role="grid" aria-label="Calendar">
              <div class="weekDayRow">
                @for (d of weekdays; track d) {
                  <span class="weekDayLabel">{{ d }}</span>
                }
              </div>
              <div class="dateGrid">
                @for (row of calendarGrid; track $index) {
                  <div class="dateRow" role="row">
                    @if (computeRangeBar(row); as bar) {
                      <div
                        class="rangeBar"
                        [class.fullRow]="bar.isFullRow"
                        [class.forward]="!bar.isFullRow && bar.isForward"
                        [class.reverse]="!bar.isFullRow && !bar.isForward"
                        [ngStyle]="{ left: bar.left + 'px', width: bar.width + 'px' }"
                      ></div>
                    }
                    @for (cell of row; track cell.year + '-' + cell.month + '-' + cell.day) {
                      <div
                        [class]="cellClasses(cell)"
                        role="gridcell"
                        [attr.aria-selected]="cellAriaSelected(cell)"
                        [attr.aria-disabled]="isDateDisabled(cellDate(cell))"
                        [attr.tabindex]="isDateDisabled(cellDate(cell)) ? -1 : 0"
                        (click)="onCellClick(cell)"
                        (mouseenter)="onCellMouseEnter(cell)"
                        (mouseleave)="onCellMouseLeave()"
                        (keydown)="onCellKeyDown($event, cell)"
                      >
                        <div class="dateCellContainer" [class.todayType]="isToday(cell)">
                          <span class="dateLabel" [class.adjacentMonth]="isAdjacentMonth(cell)">
                            {{ cell.day }}
                          </span>
                          @if (isToday(cell)) {
                            <div class="todayIndicator"></div>
                          }
                        </div>
                        <div class="focusRing"></div>
                      </div>
                    }
                  </div>
                }
              </div>
            </div>
            <button type="button" class="todayLink" (click)="goToday()">Today</button>
          </div>
        </div>
      }
    </div>
    @if (formatHint && !error) {
      <span class="formatHint">{{ formatHint }}</span>
    }
    @if (error && errorMessage) {
      <span class="errorMessage">
        <ids-icon
          shape="status-critical-square-solid"
          variant="img"
          [size]="16"
          [style]="{ flexShrink: '0' }"
        />
        {{ errorMessage }}
      </span>
    }
  </div>
</div>
