// lib/angular/ids/anchor-menu/ids-anchor-menu.component.ts
import {
  AfterContentInit,
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChildren,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  OnDestroy,
  OnInit,
  Output,
  QueryList,
  ViewEncapsulation,
} from "@angular/core";
import {
  ANCHOR_MENU_API_DEFAULTS,
} from "@component-contracts/ids/anchor-menu.contract";
import {
  IDS_ANCHOR_MENU_CONTEXT,
  type IdsAnchorMenuContext,
} from "./ids-anchor-menu-context";
import { IdsAnchorMenuItemComponent } from "./ids-anchor-menu-item.component";

@Component({
  selector: "ids-anchor-menu",
  standalone: true,
  templateUrl: "./ids-anchor-menu.component.html",
  styleUrl: "./ids-anchor-menu.component.scss",
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  providers: [{ provide: IDS_ANCHOR_MENU_CONTEXT, useExisting: IdsAnchorMenuComponent }],
})
export class IdsAnchorMenuComponent
  implements
    OnInit,
    AfterContentInit,
    AfterViewInit,
    OnDestroy,
    IdsAnchorMenuContext
{
  @ContentChildren(IdsAnchorMenuItemComponent) itemQuery!: QueryList<IdsAnchorMenuItemComponent>;

  @Input() title = ANCHOR_MENU_API_DEFAULTS.title;
  @Input() sticky = ANCHOR_MENU_API_DEFAULTS.sticky;
  /**
   * Reveal truncated labels with the browser's native `title` tooltip instead
   * of the branded `IdsTooltip`. Default `false`.
   */
  @Input() nativeTooltip = false;

  @Output() readonly itemClick = new EventEmitter<string>();

  /**
   * Auto-flipped tooltip side: `"left"` when the menu sits in the right half of
   * the viewport (so tooltips open toward the page, not off the right edge).
   */
  tooltipSide: "left" | "right" = "right";
  activeHref: string | undefined;
  private items: IdsAnchorMenuItemComponent[] = [];
  private focusedIndex = 0;
  private scrollSpyBound = false;

  constructor(
    private readonly cdr: ChangeDetectorRef,
    private readonly hostRef: ElementRef<HTMLElement>,
  ) {}

  ngOnInit(): void {
    this.bindScrollSpy();
  }

  ngAfterContentInit(): void {
    this.bindItems();
    this.itemQuery.changes.subscribe(() => this.bindItems());
  }

  ngAfterViewInit(): void {
    this.updateTooltipSide();
  }

  @HostListener("window:resize")
  updateTooltipSide(): void {
    if (typeof window === "undefined") return;
    const rect = this.hostRef.nativeElement.getBoundingClientRect();
    const center = rect.left + rect.width / 2;
    const next: "left" | "right" =
      center > window.innerWidth / 2 ? "left" : "right";
    if (next !== this.tooltipSide) {
      this.tooltipSide = next;
      this.cdr.markForCheck();
    }
  }

  ngOnDestroy(): void {
    this.unbindScrollSpy();
  }

  get activeIndicatorTopPx(): number | null {
    const active = this.items.find((item) => this.isActive(item.href));
    if (!active) {
      return null;
    }
    return active.offsetTopPx;
  }

  registerItems(items: readonly IdsAnchorMenuItemComponent[]): void {
    this.items = [...items];
    if (this.focusedIndex >= this.items.length) {
      this.focusedIndex = Math.max(0, this.items.length - 1);
    }
    if (this.activeHref === undefined) {
      const marked = this.items.find((item) => item.active);
      if (marked && this.canNavigate(marked.href)) {
        this.activeHref = marked.href;
      }
    }
    this.notifyChange();
  }

  isActive(href: string): boolean {
    return this.activeHref !== undefined && this.activeHref === href;
  }

  canNavigate(href: string): boolean {
    return typeof href === "string" && href.trim().length > 0;
  }

  selectItem(item: IdsAnchorMenuItemComponent, event?: Event): void {
    if (!this.canNavigate(item.href)) {
      event?.preventDefault();
      return;
    }
    this.activeHref = item.href;
    const index = this.items.indexOf(item);
    if (index >= 0) {
      this.focusedIndex = index;
    }
    this.itemClick.emit(item.href);
    if (item.href.startsWith("#")) {
      event?.preventDefault();
      document.getElementById(item.href.slice(1))?.scrollIntoView({ behavior: "smooth" });
      window.history.replaceState(null, "", item.href);
    }
    this.notifyChange();
  }

  onItemKeydown(event: KeyboardEvent, item: IdsAnchorMenuItemComponent): void {
    const index = this.items.indexOf(item);
    const enabledIndices = this.items
      .map((row, i) => (this.canNavigate(row.href) ? i : -1))
      .filter((i) => i >= 0);
    if (!enabledIndices.length) {
      return;
    }

    const currentPos = enabledIndices.indexOf(index);
    let targetIndex = index;

    switch (event.key) {
      case "ArrowDown":
        event.preventDefault();
        targetIndex = enabledIndices[(Math.max(currentPos, 0) + 1) % enabledIndices.length];
        break;
      case "ArrowUp":
        event.preventDefault();
        targetIndex =
          enabledIndices[
            (Math.max(currentPos, 0) - 1 + enabledIndices.length) % enabledIndices.length
          ];
        break;
      case "Enter":
        event.preventDefault();
        this.selectItem(item, event);
        return;
      default:
        return;
    }

    this.focusedIndex = targetIndex;
    this.items[targetIndex]?.focusLink();
  }

  onItemFocus(item: IdsAnchorMenuItemComponent): void {
    this.focusedIndex = this.items.indexOf(item);
  }

  itemTabIndex(item: IdsAnchorMenuItemComponent): number {
    return this.canNavigate(item.href) ? 0 : -1;
  }

  notifyChange(): void {
    for (const item of this.items) {
      item.notifyChange();
    }
    this.cdr.markForCheck();
  }

  private bindItems(): void {
    this.registerItems(this.itemQuery.toArray());
  }

  private bindScrollSpy(): void {
    if (this.scrollSpyBound || typeof window === "undefined") {
      return;
    }
    window.addEventListener("scroll", this.onWindowScroll, { passive: true });
    this.scrollSpyBound = true;
  }

  private unbindScrollSpy(): void {
    if (!this.scrollSpyBound || typeof window === "undefined") {
      return;
    }
    window.removeEventListener("scroll", this.onWindowScroll);
    this.scrollSpyBound = false;
  }

  private readonly onWindowScroll = (): void => {
    const hashItems = this.items.filter(
      (item) => this.canNavigate(item.href) && item.href.startsWith("#"),
    );
    if (!hashItems.length) {
      return;
    }
    let current = hashItems[0]?.href;
    for (const item of hashItems) {
      const target = document.getElementById(item.href.slice(1));
      if (!target) {
        continue;
      }
      if (target.getBoundingClientRect().top <= 0) {
        current = item.href;
      }
    }
    if (current && current !== this.activeHref) {
      this.activeHref = current;
      this.notifyChange();
    }
  };
}

<nav
  class="ids-anchor-menu"
  [class.ids-anchor-menu--sticky]="sticky"
  [attr.aria-label]="title"
>
  <ng-content select="ids-anchor-menu-header" />
  <div class="ids-anchor-menu__list" role="list">
    <ng-content select="ids-anchor-menu-item" />
    <ng-content select="ids-anchor-active-indicator" />
  </div>
</nav>

// lib/react/ids/anchor-menu/IdsAnchorMenu.tsx
/**
 * IDS Anchor Menu — React implementation generated from design-spec.
 *
 * Path: `lib/react/ids/anchor-menu`
 * Source: `components/ids/anchor-menu/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * Anatomy / Codegen slots:
 *   AnchorMenuRoot
 *     AnchorMenuHeader?
 *     repeated AnchorMenuItem
 *     AnchorActiveIndicator (left-border indicator on active/hover item)
 *
 * Composition & API (runtime) only — no invented variants/props.
 * No @base-ui-components dependency.
 */

import React, {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ComponentProps,
  type KeyboardEvent,
  type MouseEvent,
  type ReactElement,
} from "react";
import styles from "./IdsAnchorMenu.module.css";
import { IdsTooltip } from "../tooltip";

export interface IdsAnchorMenuItem {
  label: string;
  href: string;
  active?: boolean;
}

export interface IdsAnchorMenuProps
  extends Omit<ComponentProps<"nav">, "children" | "onClick" | "title"> {
  /** Required. Empty array renders empty state without crash. */
  items: IdsAnchorMenuItem[];
  /** Optional section heading. Default `"On this page"`. */
  title?: string;
  /** Show/hide the heading. Default `true`. */
  header?: boolean;
  /** Sticky positioning for long-page usage. Default `true`. */
  sticky?: boolean;
  /**
   * Reveal truncated labels with the browser's built-in `title` tooltip instead
   * of the branded `IdsTooltip`. Default `false` (use `IdsTooltip`).
   */
  nativeTooltip?: boolean;
  onItemClick?: (href: string) => void;
}

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

function hasNavigableHref(href: unknown): href is string {
  return typeof href === "string" && href.trim() !== "";
}

function sectionIdFromHref(href: string): string | null {
  if (!href.startsWith("#") || href.length < 2) return null;
  return href.slice(1);
}

function resolveActiveHref(
  items: IdsAnchorMenuItem[],
  controlled: string | undefined,
): string | undefined {
  if (controlled !== undefined) return controlled;
  const marked = items.find((item) => item.active);
  return marked?.href;
}

export function IdsAnchorMenu({
  items,
  title = "On this page",
  header = true,
  sticky = true,
  nativeTooltip = false,
  onItemClick,
  className,
  ...rest
}: IdsAnchorMenuProps): ReactElement {
  const safeItems = Array.isArray(items) ? items : [];
  const [activeHref, setActiveHref] = useState<string | undefined>(() =>
    resolveActiveHref(safeItems, undefined),
  );
  const itemRefs = useRef<Array<HTMLAnchorElement | null>>([]);
  const labelRefs = useRef<Map<number, HTMLSpanElement>>(new Map());
  const [truncatedIndexes, setTruncatedIndexes] = useState<Set<number>>(new Set());

  // Auto-flip the label tooltip: when the menu sits in the right half of the
  // viewport (e.g. a right-hand rail), anchor tooltips on the left so they open
  // toward the page instead of overflowing off the right edge. IdsTooltip has
  // no built-in collision detection, so the menu picks the side itself.
  const navRef = useRef<HTMLElement>(null);
  const [tooltipSide, setTooltipSide] = useState<"left" | "right">("right");

  useEffect(() => {
    if (nativeTooltip || typeof window === "undefined") return;
    const updateSide = () => {
      const nav = navRef.current;
      if (!nav) return;
      const rect = nav.getBoundingClientRect();
      const center = rect.left + rect.width / 2;
      setTooltipSide(center > window.innerWidth / 2 ? "left" : "right");
    };
    updateSide();
    window.addEventListener("resize", updateSide);
    return () => window.removeEventListener("resize", updateSide);
  }, [nativeTooltip]);

  const hashTargets = useMemo(
    () =>
      safeItems
        .map((item) =>
          hasNavigableHref(item.href) ? sectionIdFromHref(item.href) : null,
        )
        .filter((id): id is string => id != null),
    [safeItems],
  );

  const propsActiveHref = useMemo(
    () => safeItems.find((item) => item.active)?.href,
    [safeItems],
  );

  // Sync when consumer marks a different `active` item.
  useEffect(() => {
    if (propsActiveHref !== undefined) {
      setActiveHref(propsActiveHref);
    }
  }, [propsActiveHref]);

  // Scroll spy — updates active item from section scroll position.
  useEffect(() => {
    if (typeof window === "undefined" || hashTargets.length === 0) return;

    const elements = hashTargets
      .map((id) => document.getElementById(id))
      .filter((el): el is HTMLElement => el != null);

    if (elements.length === 0) return;

    const observer = new IntersectionObserver(
      (entries) => {
        const visible = entries
          .filter((entry) => entry.isIntersecting)
          .sort(
            (a, b) =>
              (a.boundingClientRect.top ?? 0) - (b.boundingClientRect.top ?? 0),
          );
        const top = visible[0];
        if (!top?.target?.id) return;
        setActiveHref(`#${top.target.id}`);
      },
      {
        root: null,
        rootMargin: "0px 0px -60% 0px",
        threshold: [0, 0.25, 0.5, 1],
      },
    );

    for (const el of elements) observer.observe(el);
    return () => observer.disconnect();
  }, [hashTargets]);

  const navigateToHref = useCallback(
    (href: string) => {
      if (!hasNavigableHref(href)) return;

      setActiveHref(href);
      onItemClick?.(href);

      const sectionId = sectionIdFromHref(href);
      if (sectionId != null) {
        document
          .getElementById(sectionId)
          ?.scrollIntoView({ behavior: "smooth" });
        if (typeof window !== "undefined" && window.history?.replaceState) {
          window.history.replaceState(null, "", href);
        }
      } else if (typeof window !== "undefined") {
        window.location.assign(href);
      }
    },
    [onItemClick],
  );

  const handleItemClick = (
    event: MouseEvent<HTMLAnchorElement>,
    href: string,
    navigable: boolean,
  ) => {
    if (!navigable) {
      event.preventDefault();
      return;
    }
    if (href.startsWith("#")) {
      event.preventDefault();
      navigateToHref(href);
      return;
    }
    setActiveHref(href);
    onItemClick?.(href);
  };

  const focusItemAt = (index: number) => {
    const len = safeItems.length;
    if (len === 0) return;
    const next = ((index % len) + len) % len;
    itemRefs.current[next]?.focus();
  };

  const handleItemKeyDown = (
    event: KeyboardEvent<HTMLAnchorElement>,
    index: number,
    href: string,
    navigable: boolean,
  ) => {
    switch (event.key) {
      case "ArrowDown":
        event.preventDefault();
        focusItemAt(index + 1);
        break;
      case "ArrowUp":
        event.preventDefault();
        focusItemAt(index - 1);
        break;
      case "Enter":
        if (!navigable) {
          event.preventDefault();
          return;
        }
        if (href.startsWith("#")) {
          event.preventDefault();
          navigateToHref(href);
        }
        break;
      default:
        break;
    }
  };

  useEffect(() => {
    const nextTruncated = new Set<number>();
    labelRefs.current.forEach((el, index) => {
      if (el.scrollHeight > el.clientHeight) {
        nextTruncated.add(index);
      }
    });
    setTruncatedIndexes(nextTruncated);
  }, [safeItems]);

  return (
    <nav
      {...rest}
      ref={navRef}
      aria-label={title}
      data-ids="ids-anchor-menu"
      data-sticky={sticky ? "true" : "false"}
      className={cx(
        styles["ids-anchor-menu"],
        sticky && styles["ids-anchor-menu--sticky"],
        className,
      )}
    >
      {header ? (
        <span
          className={styles["ids-anchor-menu-header"]}
          data-ids="ids-anchor-menu-header"
        >
          {title}
        </span>
      ) : null}

      <ul className={styles["ids-anchor-menu-list"]} data-ids="ids-anchor-menu-list">
        {safeItems.map((item, index) => {
          const navigable = hasNavigableHref(item.href);
          const href = navigable ? item.href : "";
          const isActive =
            navigable && activeHref !== undefined
              ? activeHref === item.href
              : Boolean(item.active);

          const isTruncated = truncatedIndexes.has(index);
          const useIdsTooltip = isTruncated && !nativeTooltip;
          const nativeTitle =
            isTruncated && nativeTooltip ? item.label : undefined;

          const labelSpan = (
            <span
              ref={(el) => {
                if (el) {
                  labelRefs.current.set(index, el);
                } else {
                  labelRefs.current.delete(index);
                }
              }}
              className={styles["ids-anchor-menu-label"]}
              title={nativeTitle}
            >
              {item.label}
            </span>
          );

          // In `"ids"` mode, anchor the tooltip to the label text (not the
          // padded link) so it sits right beside the text edge.
          const labelContent = useIdsTooltip ? (
            <IdsTooltip side={tooltipSide} arrowAlign="start">
              <IdsTooltip.Trigger display="inline">
                {labelSpan}
              </IdsTooltip.Trigger>
              <IdsTooltip.Panel>
                <IdsTooltip.Body>{item.label}</IdsTooltip.Body>
              </IdsTooltip.Panel>
            </IdsTooltip>
          ) : (
            labelSpan
          );

          const link = (
            <a
              ref={(el) => {
                itemRefs.current[index] = el;
              }}
              href={navigable ? href : undefined}
              className={styles["ids-anchor-menu-link"]}
              data-ids="ids-anchor-menu-link"
              aria-current={isActive ? "page" : undefined}
              aria-disabled={navigable ? undefined : true}
              tabIndex={navigable ? 0 : -1}
              onClick={(event) => handleItemClick(event, href, navigable)}
              onKeyDown={(event) =>
                handleItemKeyDown(event, index, href, navigable)
              }
              onFocus={(event) => event.stopPropagation()}
            >
              {labelContent}
            </a>
          );

          return (
            <li
              key={`${item.href}-${index}`}
              className={styles["ids-anchor-menu-item"]}
              data-ids="ids-anchor-menu-item"
            >
              {link}
            </li>
          );
        })}
      </ul>
    </nav>
  );
}

IdsAnchorMenu.displayName = "IdsAnchorMenu";

export default IdsAnchorMenu;
