// storybook-angular/src/components/ids-datagrid/ids-datagrid-column-visibility-panel.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Input, Output } from "@angular/core";
import { IdsCheckboxComponent } from "../ids-checkbox/ids-checkbox.component";
import { IdsIconComponent } from "../ids-icon/ids-icon.component";
import type { IdsDatagridColumnModel } from "./ids-datagrid-context";

@Component({
  selector: "ids-datagrid-column-visibility-panel",
  standalone: true,
  imports: [IdsCheckboxComponent, IdsIconComponent],
  templateUrl: "./ids-datagrid-column-visibility-panel.component.html",
  styleUrl: "./ids-datagrid-column-visibility-panel.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsDatagridColumnVisibilityPanelComponent {
  @Input({ required: true }) hideableColumns: IdsDatagridColumnModel[] = [];
  @Input() hiddenColumnKeys = new Set<string>();
  @Input() validationMessage: string | null = null;

  @Output() readonly columnVisibilityChange = new EventEmitter<{
    field: string;
    visible: boolean;
  }>();

  onVisibilityChange(field: string, visible: boolean): void {
    this.columnVisibilityChange.emit({ field, visible });
  }
}

<div class="root" role="group" aria-label="Show or hide columns" data-column-visibility-panel>
  <ul class="optionList">
    @for (column of hideableColumns; track column.field) {
      <li class="optionItem">
        <div class="checkboxHost">
          <ids-checkbox
            [id]="'ids-datagrid-col-vis-' + column.field"
            [label]="column.title"
            [checked]="!hiddenColumnKeys.has(column.field)"
            (checkedChange)="onVisibilityChange(column.field, $event)"
          />
        </div>
      </li>
    }
  </ul>
  @if (validationMessage) {
    <div class="validation" role="alert">
      <ids-icon shapeName="status-critical-square-solid" [size]="16" />
      <span class="validationText">{{ validationMessage }}</span>
    </div>
  }
</div>

// lib/react/ids/datagrid/IdsDatagridColumnVisibilityPanel.tsx
import React from "react";
import { IdsCheckbox, IdsCheckboxLabel } from "../checkbox";
import { IdsIcon } from "../icon";
import type { IdsDatagridColumnDef } from "./IdsDatagridSlots";
import styles from "./IdsDatagridColumnVisibility.module.css";

export interface IdsDatagridColumnVisibilityPanelProps {
  hideableColumns: readonly IdsDatagridColumnDef[];
  hiddenColumnKeys: ReadonlySet<string>;
  onColumnVisibilityChange: (columnKey: string, visible: boolean) => void;
  validationMessage?: string | null;
}

export function IdsDatagridColumnVisibilityPanel({
  hideableColumns,
  hiddenColumnKeys,
  onColumnVisibilityChange,
  validationMessage,
}: IdsDatagridColumnVisibilityPanelProps) {
  return (
    <div
      className={styles.root}
      role="group"
      aria-label="Show or hide columns"
      data-column-visibility-panel=""
      data-ids="ids-datagrid-column-visibility"
    >
      <ul className={styles.optionList}>
        {hideableColumns.map((column) => {
          const visible = !hiddenColumnKeys.has(column.key);
          const inputId = `ids-datagrid-col-vis-${column.key}`;
          return (
            <li key={column.key} className={styles.optionItem}>
              <div className={styles.checkboxHost}>
                <IdsCheckbox
                  id={inputId}
                  checked={visible}
                  onChange={(checked) => onColumnVisibilityChange(column.key, checked)}
                >
                  <IdsCheckboxLabel>{column.title}</IdsCheckboxLabel>
                </IdsCheckbox>
              </div>
            </li>
          );
        })}
      </ul>
      {validationMessage ? (
        <div className={styles.validation} role="alert">
          <IdsIcon
            shape="status-critical-square-solid"
            variant="img"
            className={styles.validationIcon}
            style={{ width: 16, height: 16 }}
          />
          <span className={styles.validationText}>{validationMessage}</span>
        </div>
      ) : null}
    </div>
  );
}
