// storybook/src/components/IdsFooter.tsx
import type { ComponentProps } from "react";

import { Icon } from "./Icon";
import styles from "./IdsFooter.module.css";

export interface IdsFooterProps extends Omit<ComponentProps<"footer">, "children"> {
  hostname?: string;
  swid?: string;
  currentDateTime?: string;
  timeZoneLabel?: string;
  showHostname?: boolean;
  showCurrentDateAndTime?: boolean;
  showTimeZone?: boolean;
  copyDisabled?: boolean;
  timeZoneDisabled?: boolean;
  onCopySwid?: (swid: string) => void;
  onTimeZoneClick?: () => void;
}

async function copyTextToClipboard(text: string): Promise<void> {
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.setAttribute("readonly", "");
  textarea.style.position = "fixed";
  textarea.style.left = "-9999px";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  document.body.removeChild(textarea);
}

export function IdsFooter({
  hostname = "short_name_first_domain_name",
  swid = "ELMCR00222GBPB",
  currentDateTime = "Tue, 2023-04-23 12:30 AM",
  timeZoneLabel = "Eastern Time (US & Canada)",
  showHostname = true,
  showCurrentDateAndTime = true,
  showTimeZone = true,
  copyDisabled = false,
  timeZoneDisabled = false,
  onCopySwid,
  onTimeZoneClick,
  className,
  ...rest
}: IdsFooterProps) {
  const canCopy = Boolean(swid) && !copyDisabled;

  const handleCopy = async () => {
    if (!canCopy || !swid) return;
    try {
      await copyTextToClipboard(swid);
    } catch {
      /* host may surface errors via onCopySwid */
    }
    onCopySwid?.(swid);
  };

  return (
    <footer
      className={[styles.root, className].filter(Boolean).join(" ")}
      aria-label="Application status"
      {...rest}
    >
      <div className={styles.left}>
        {showHostname && (
          <div className={styles.field}>
            <span className={styles.label}>Host Name:</span>
            <span className={styles.value}>{hostname}</span>
          </div>
        )}
        {swid != null && swid !== "" && (
          <div className={styles.swidGroup}>
            <div className={styles.field}>
              <span className={styles.label}>SWID:</span>
              <span className={styles.value}>{swid}</span>
            </div>
            <button
              type="button"
              className={styles.copyButton}
              aria-label="Copy SWID"
              disabled={!canCopy}
              onClick={() => void handleCopy()}
            >
              <Icon
                shapeName="copy"
                variant="mask"
                color="var(--color-icon-brand-base)"
                style={{ width: 14, height: 14 }}
              />
            </button>
          </div>
        )}
      </div>
      {showCurrentDateAndTime && currentDateTime != null && currentDateTime !== "" && (
        <div className={styles.timeGroup}>
          <Icon
            shapeName="time-clock"
            variant="mask"
            color="var(--color-icon-neutral)"
            style={{ width: 16, height: 16 }}
          />
          <span className={styles.dateTime}>{currentDateTime}</span>
        </div>
      )}
      {showTimeZone && (
        <div className={styles.timeZoneGroup}>
          <Icon
            shapeName="world-globe"
            variant="mask"
            color="var(--color-icon-brand-base)"
            style={{ width: 16, height: 16 }}
          />
          <button
            type="button"
            className={styles.timeZoneButton}
            disabled={timeZoneDisabled}
            onClick={() => onTimeZoneClick?.()}
          >
            {timeZoneLabel || "Time zone"}
          </button>
        </div>
      )}
    </footer>
  );
}

// storybook-angular/src/components/ids-footer/ids-footer.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  Output,
} from "@angular/core";
import {
  FOOTER_SPEC_ACCURATE_DEFAULTS,
} from "@component-contracts/ids/footer.contract";
import { IdsIconComponent } from "../ids-icon/ids-icon.component";

async function copyTextToClipboard(text: string): Promise<void> {
  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return;
  }
  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.setAttribute("readonly", "");
  textarea.style.position = "fixed";
  textarea.style.left = "-9999px";
  document.body.appendChild(textarea);
  textarea.select();
  document.execCommand("copy");
  document.body.removeChild(textarea);
}

@Component({
  selector: "ids-footer",
  standalone: true,
  imports: [IdsIconComponent],
  templateUrl: "./ids-footer.component.html",
  styleUrl: "./ids-footer.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    class: "ids-footer-host",
  },
})
export class IdsFooterComponent {
  @Input() hostname: string = FOOTER_SPEC_ACCURATE_DEFAULTS.hostname;
  @Input() swid: string = FOOTER_SPEC_ACCURATE_DEFAULTS.swid;
  @Input() currentDateTime: string = FOOTER_SPEC_ACCURATE_DEFAULTS.currentDateTime;
  @Input() timeZoneLabel: string = FOOTER_SPEC_ACCURATE_DEFAULTS.timeZoneLabel;
  @Input() showHostname = FOOTER_SPEC_ACCURATE_DEFAULTS.showHostname;
  @Input() showCurrentDateAndTime = FOOTER_SPEC_ACCURATE_DEFAULTS.showCurrentDateAndTime;
  @Input() showTimeZone = FOOTER_SPEC_ACCURATE_DEFAULTS.showTimeZone;
  @Input() copyDisabled = FOOTER_SPEC_ACCURATE_DEFAULTS.copyDisabled;
  @Input() timeZoneDisabled = FOOTER_SPEC_ACCURATE_DEFAULTS.timeZoneDisabled;

  @Output() readonly copySwid = new EventEmitter<string>();
  @Output() readonly timeZoneClick = new EventEmitter<void>();

  get canCopy(): boolean {
    return Boolean(this.swid) && !this.copyDisabled;
  }

  get resolvedTimeZoneLabel(): string {
    return this.timeZoneLabel || "Time zone";
  }

  get showSwidGroup(): boolean {
    return this.swid != null && this.swid !== "";
  }

  get showTimeGroup(): boolean {
    return (
      this.showCurrentDateAndTime &&
      this.currentDateTime != null &&
      this.currentDateTime !== ""
    );
  }

  async onCopyClick(): Promise<void> {
    if (!this.canCopy || !this.swid) {
      return;
    }
    try {
      await copyTextToClipboard(this.swid);
    } catch {
      /* host may surface errors via copySwid */
    }
    this.copySwid.emit(this.swid);
  }

  onTimeZoneButtonClick(): void {
    if (this.timeZoneDisabled) {
      return;
    }
    this.timeZoneClick.emit();
  }
}

<footer class="ids-footer" aria-label="Application status">
  <div class="ids-footer__left">
    @if (showHostname) {
      <div class="ids-footer__field">
        <span class="ids-footer__label">Host Name: </span>
        <span class="ids-footer__value">{{ hostname }}</span>
      </div>
    }
    @if (showSwidGroup) {
      <div class="ids-footer__swid-group">
        <div class="ids-footer__field">
          <span class="ids-footer__label">SWID: </span>
          <span class="ids-footer__value">{{ swid }}</span>
        </div>
        <button
          type="button"
          class="ids-footer__copy-button"
          aria-label="Copy SWID"
          [disabled]="!canCopy"
          [attr.aria-disabled]="!canCopy ? 'true' : null"
          (click)="onCopyClick()"
        >
          <ids-icon
            className="ids-footer__copy-icon"
            shapeName="copy"
            variant="mask"
            [size]="14"
          />
        </button>
      </div>
    }
  </div>
  @if (showTimeGroup) {
    <div class="ids-footer__time-group">
      <ids-icon
        className="ids-footer__time-icon"
        shapeName="time-clock"
        variant="mask"
        [size]="16"
      />
      <span class="ids-footer__datetime">{{ currentDateTime }}</span>
    </div>
  }
  @if (showTimeZone) {
    <div class="ids-footer__timezone-group">
      <ids-icon
        className="ids-footer__globe-icon"
        shapeName="world-globe"
        variant="mask"
        [size]="16"
      />
      <button
        type="button"
        class="ids-footer__timezone-button"
        [disabled]="timeZoneDisabled"
        (click)="onTimeZoneButtonClick()"
      >
        {{ resolvedTimeZoneLabel }}
      </button>
    </div>
  }
</footer>
