// lib/angular/ids/alert/ids-alert.component.ts
import {
  AfterContentInit,
  Component,
  ContentChild,
  ElementRef,
  EventEmitter,
  Input,
  Output,
  ViewEncapsulation,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  ALERT_GLOBAL_STATUS_ICON,
  ALERT_INLINE_STATUS_ICON,
  ALERT_SPEC_ACCURATE_DEFAULTS,
  type AlertCarouselInput,
  type AlertDensity,
  type AlertDisplay,
  type AlertGlobalSeverity,
  type AlertInlineSeverity,
  type AlertLinkInput,
} from "@component-contracts/ids/alert.contract";
import { IDS_ALERT_CONTEXT, type IdsAlertContext } from "./ids-alert-context";
import { IdsAlertMessageComponent } from "./ids-alert-message.component";
import { IdsAlertTitleComponent } from "./ids-alert-title.component";
import { IdsAlertLinkComponent } from "./ids-alert-link.component";
import { IdsAlertActionComponent } from "./ids-alert-action.component";
import { IdsIconComponent } from "../icon/ids-icon.component";

@Component({
  selector: "ids-alert",
  standalone: true,
  imports: [CommonModule, IdsIconComponent],
  templateUrl: "./ids-alert.component.html",
  styleUrl: "./ids-alert.component.scss",
  encapsulation: ViewEncapsulation.None,
  providers: [{ provide: IDS_ALERT_CONTEXT, useExisting: IdsAlertComponent }],
})
export class IdsAlertComponent implements AfterContentInit, IdsAlertContext {
  @ContentChild(IdsAlertMessageComponent) messageSlot?: IdsAlertMessageComponent;
  @ContentChild(IdsAlertMessageComponent, { read: ElementRef })
  private messageHost?: ElementRef<HTMLElement>;
  @ContentChild(IdsAlertTitleComponent) titleSlot?: IdsAlertTitleComponent;
  @ContentChild(IdsAlertTitleComponent, { read: ElementRef })
  private titleHost?: ElementRef<HTMLElement>;
  @ContentChild(IdsAlertLinkComponent) linkSlot?: IdsAlertLinkComponent;
  @ContentChild(IdsAlertActionComponent) actionSlot?: IdsAlertActionComponent;

  @Input() display: AlertDisplay = ALERT_SPEC_ACCURATE_DEFAULTS.display;
  @Input() severity: AlertGlobalSeverity | AlertInlineSeverity =
    ALERT_SPEC_ACCURATE_DEFAULTS.severity;
  /** Shorthand when `ids-alert-message` is not projected. */
  @Input() message: string = ALERT_SPEC_ACCURATE_DEFAULTS.message;
  /** Shorthand when `ids-alert-title` is not projected. */
  @Input() title = "";
  @Input() density: AlertDensity = ALERT_SPEC_ACCURATE_DEFAULTS.density;
  @Input() link: AlertLinkInput | null = null;
  @Input() linkLabel = "";
  @Input() linkHref = "";
  @Input() actionLabel = "";
  @Input() dismissible: boolean | null = ALERT_SPEC_ACCURATE_DEFAULTS.dismissible;
  @Input() carousel: AlertCarouselInput | null = null;

  @Output() readonly action = new EventEmitter<void>();
  @Output() readonly dismiss = new EventEmitter<void>();
  @Output() readonly linkClick = new EventEmitter<MouseEvent>();
  @Output() readonly carouselPrevious = new EventEmitter<void>();
  @Output() readonly carouselNext = new EventEmitter<void>();

  dismissed = false;
  hasMessageSlot = false;
  hasTitleSlot = false;

  ngAfterContentInit(): void {
    this.hasMessageSlot = Boolean(this.messageSlot);
    this.hasTitleSlot = Boolean(this.titleSlot);
  }

  get isGlobal(): boolean {
    return this.display === "global";
  }

  get resolvedLink(): AlertLinkInput | null {
    if (this.linkSlot) {
      return { label: this.linkSlot.label, href: this.linkSlot.href || undefined };
    }
    if (this.link) {
      return this.link;
    }
    if (this.linkLabel) {
      return { label: this.linkLabel, href: this.linkHref || undefined };
    }
    return null;
  }

  get resolvedActionLabel(): string {
    return this.actionSlot?.label || this.actionLabel;
  }

  get showAction(): boolean {
    return Boolean(this.resolvedActionLabel);
  }

  get showLink(): boolean {
    return Boolean(this.resolvedLink?.label);
  }

  get showCarousel(): boolean {
    return this.isGlobal && Boolean(this.carousel);
  }

  get showDismissGlobal(): boolean {
    const allowed = this.dismissible ?? true;
    const sev = this.severity as AlertGlobalSeverity;
    return allowed && (sev !== "critical" || (this.showCarousel && !this.showAction));
  }

  get showDismissInline(): boolean {
    const allowed = this.dismissible ?? true;
    return allowed && this.severity !== "critical";
  }

  get showTitle(): boolean {
    return !this.isGlobal && this.density === "detailed" && (this.hasTitleSlot || Boolean(this.title));
  }

  get showTitleRow(): boolean {
    return this.showTitle && this.showAction;
  }

  get showActionInTitleRow(): boolean {
    return !this.isGlobal && this.density === "detailed" && this.showTitle && this.showAction;
  }

  get showActionInTrailing(): boolean {
    return this.showAction && !this.showActionInTitleRow;
  }

  get showTrailing(): boolean {
    return !this.isGlobal && (this.showActionInTrailing || this.showDismissInline);
  }

  get useMessageSlot(): boolean {
    return this.hasMessageSlot;
  }

  get resolvedMessage(): string {
    if (this.hasMessageSlot) {
      const slotText = this.messageHost?.nativeElement?.textContent?.trim();
      if (slotText) {
        return slotText;
      }
    }
    return this.message;
  }

  get resolvedTitle(): string {
    if (this.hasTitleSlot) {
      return this.titleHost?.nativeElement?.textContent?.trim() ?? "";
    }
    return this.title;
  }

  get carouselCounter(): string {
    if (!this.carousel) {
      return "";
    }
    const current = Math.max(1, this.carousel.currentItem);
    const total = Math.max(1, this.carousel.totalItems);
    return `${current} of ${total}`;
  }

  get statusIcon() {
    if (this.isGlobal) {
      return ALERT_GLOBAL_STATUS_ICON[this.severity as AlertGlobalSeverity];
    }
    return ALERT_INLINE_STATUS_ICON[this.severity as AlertInlineSeverity];
  }

  /** @deprecated Use `statusIcon.shape` — kept for template/docs compatibility. */
  statusIconSlug(): string {
    return this.statusIcon.shape;
  }

  onDismissClick(): void {
    this.dismissed = true;
    this.dismiss.emit();
  }

  onLinkActivate(event: MouseEvent): void {
    this.linkClick.emit(event);
  }

  linkClass(): string {
    return this.isGlobal ? "ids-alert__link" : "ids-alert__inline-link";
  }

  linkButtonClass(): string {
    return this.isGlobal ? "ids-alert__link-button" : "ids-alert__inline-link-button";
  }
}

@if (!dismissed) {
  @if (isGlobal) {
    <section
      class="ids-alert ids-alert--global"
      [attr.data-severity]="severity"
      [attr.data-carousel]="showCarousel ? 'true' : 'false'"
      role="alert"
      aria-live="assertive"
    >
      @if (showCarousel && carousel) {
        <div class="ids-alert__carousel-rail">
          <button
            type="button"
            class="ids-alert__carousel-button"
            aria-label="Previous alert"
            (click)="carouselPrevious.emit()"
          >
            <ids-icon shape="chev-left-16" variant="img" [size]="12" className="ids-alert__carousel-chevron" />
          </button>
          <span class="ids-alert__carousel-count">{{ carouselCounter }}</span>
          <button
            type="button"
            class="ids-alert__carousel-button"
            aria-label="Next alert"
            (click)="carouselNext.emit()"
          >
            <ids-icon shape="chev-right-16" variant="img" [size]="12" className="ids-alert__carousel-chevron" />
          </button>
        </div>
      }

      <div class="ids-alert__global-content">
        <ids-icon
          [shape]="statusIcon.shape"
          [variant]="statusIcon.variant"
          [color]="statusIcon.color"
          [size]="16"
          className="ids-alert__global-icon"
        />
        <p class="ids-alert__global-message">
          {{ resolvedMessage }}
          @if (showLink) {
            @if (linkSlot) {
              <ng-content select="ids-alert-link" />
            } @else if (resolvedLink; as linkRef) {
              @if (linkRef.href) {
                <a
                  class="ids-alert__link"
                  [href]="linkRef.href"
                  (click)="onLinkActivate($event)"
                >
                  {{ linkRef.label }}
                </a>
              } @else {
                <button
                  type="button"
                  class="ids-alert__link-button"
                  (click)="onLinkActivate($event)"
                >
                  {{ linkRef.label }}
                </button>
              }
            }
          }
        </p>
      </div>

      <div class="ids-alert__global-actions" [attr.data-has-action]="showAction ? 'true' : 'false'">
        @if (showAction) {
          <button type="button" class="ids-alert__global-action" (click)="action.emit()">
            {{ resolvedActionLabel }}
          </button>
        }
        @if (showDismissGlobal) {
          <button
            type="button"
            class="ids-alert__global-dismiss"
            aria-label="Dismiss alert"
            (click)="onDismissClick()"
          >
            <ids-icon shape="shape-x" variant="img" [size]="12" className="ids-alert__global-dismiss-icon" />
          </button>
        }
      </div>
    </section>
  } @else {
    <div
      class="ids-alert ids-alert--inline"
      [class.ids-alert--inline-compact]="density === 'compact'"
      [class.ids-alert--inline-detailed]="density === 'detailed'"
      [attr.data-severity]="severity"
      [attr.data-density]="density"
      [attr.data-action-in-title]="showActionInTitleRow ? 'true' : 'false'"
      role="alert"
    >
      <div class="ids-alert__inline-main">
        <span class="ids-alert__inline-icon-wrap">
          <ids-icon
            [shape]="statusIcon.shape"
            [variant]="statusIcon.variant"
            [color]="statusIcon.color"
            [size]="16"
            className="ids-alert__inline-icon"
          />
        </span>
        <div class="ids-alert__inline-text">
          @if (showTitleRow) {
            <div class="ids-alert__title-row">
              @if (hasTitleSlot) {
                <p class="ids-alert__inline-title">{{ resolvedTitle }}</p>
              } @else {
                <p class="ids-alert__inline-title">{{ title }}</p>
              }
              <button type="button" class="ids-alert__inline-action" (click)="action.emit()">
                {{ resolvedActionLabel }}
              </button>
            </div>
          } @else if (showTitle) {
            @if (hasTitleSlot) {
              <p class="ids-alert__inline-title">{{ resolvedTitle }}</p>
            } @else {
              <p class="ids-alert__inline-title">{{ title }}</p>
            }
          }

          <p class="ids-alert__inline-message">
            {{ resolvedMessage }}
            @if (showLink && !linkSlot && resolvedLink; as linkRef) {
              @if (linkRef.href) {
                <a
                  class="ids-alert__inline-link"
                  [href]="linkRef.href"
                  (click)="onLinkActivate($event)"
                >
                  {{ linkRef.label }}
                </a>
              } @else {
                <button
                  type="button"
                  class="ids-alert__inline-link-button"
                  (click)="onLinkActivate($event)"
                >
                  {{ linkRef.label }}
                </button>
              }
            }
          </p>

          @if (showLink && linkSlot) {
            <ng-content select="ids-alert-link" />
          }
        </div>
      </div>

      @if (showTrailing) {
        <div
          class="ids-alert__inline-trailing"
          [attr.data-has-action]="showActionInTrailing ? 'true' : 'false'"
        >
          @if (showActionInTrailing) {
            <button type="button" class="ids-alert__inline-action" (click)="action.emit()">
              {{ resolvedActionLabel }}
            </button>
          }
          @if (showDismissInline) {
            <button
              type="button"
              class="ids-alert__inline-dismiss"
              aria-label="Dismiss alert"
              (click)="onDismissClick()"
            >
              <ids-icon shape="shape-x" variant="img" [size]="12" />
            </button>
          }
        </div>
      }
    </div>
  }
}

// lib/react/ids/alert/IdsAlert.tsx
/**
 * IDS Alert — React implementation generated from design-spec.
 *
 * Path: `lib/react/ids/alert`
 * Source: `components/ids/alert/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * Unified `display: "global" | "inline"`. Multi-item global carousel: `IdsAlertGroup`.
 * Selectors: ids-alert-global, ids-alert-inline, …
 * No @base-ui-components dependency.
 */

import React, { useState, type MouseEvent } from "react";
import { IdsIcon } from "../icon";
import styles from "./IdsAlert.module.css";

export type IdsAlertDisplay = "global" | "inline";

export type IdsAlertGlobalSeverity =
  | "critical"
  | "warning-major"
  | "warning-minor"
  | "informational";

export type IdsAlertInlineSeverity = IdsAlertGlobalSeverity | "success";

export type IdsAlertSeverityFor<D extends IdsAlertDisplay> = D extends "global"
  ? IdsAlertGlobalSeverity
  : IdsAlertInlineSeverity;

export interface IdsAlertCarouselProps {
  currentItem: number;
  totalItems: number;
  onPrevious?: () => void;
  onNext?: () => void;
}

export interface IdsAlertLink {
  label: string;
  href?: string;
}

export interface IdsAlertBaseProps {
  message: string;
  /** Preferred link contract (design-spec). */
  link?: IdsAlertLink;
  /** Convenience aliases matching Storybook Alert examples. */
  linkLabel?: string;
  linkHref?: string;
  onLinkClick?: (event: MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => void;
  actionLabel?: string;
  onAction?: () => void;
  dismissible?: boolean;
  onDismiss?: () => void;
}

export type IdsAlertProps =
  | (IdsAlertBaseProps & {
      display: "global";
      severity?: IdsAlertGlobalSeverity;
      carousel?: IdsAlertCarouselProps;
      title?: never;
      density?: never;
    })
  | (IdsAlertBaseProps & {
      display: "inline";
      severity?: IdsAlertInlineSeverity;
      title?: string;
      density?: "compact" | "detailed";
      carousel?: never;
    });

const globalSeverityToIcon: Record<
  IdsAlertGlobalSeverity,
  { shape: string; variant: "img" | "mask" | "inline"; color?: string }
> = {
  critical: { shape: "status-critical-square-solid-ko", variant: "img" },
  "warning-major": {
    shape: "status-error-diamond-solid-ko",
    variant: "mask",
    color: "var(--color-icon-gray-white)",
  },
  "warning-minor": { shape: "status-warn-tri-solid", variant: "inline" },
  informational: { shape: "info-circ-solid-ko", variant: "img" },
};

const inlineSeverityToIcon: Record<IdsAlertInlineSeverity, string> = {
  informational: "info-circ-solid",
  success: "status-ok-circ-solid",
  "warning-minor": "status-warn-tri-solid",
  "warning-major": "status-error-diamond-solid",
  critical: "status-critical-square-solid",
};

function resolveLink(props: IdsAlertBaseProps): IdsAlertLink | undefined {
  if (props.link?.label) return props.link;
  if (props.linkLabel) {
    return { label: props.linkLabel, href: props.linkHref };
  }
  return undefined;
}

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

export function IdsAlert(props: IdsAlertProps) {
  const [dismissed, setDismissed] = useState(false);

  if (dismissed) return null;

  if (props.display === "global") {
    return (
      <IdsAlertGlobalView {...props} onInternalDismiss={() => setDismissed(true)} />
    );
  }

  return (
    <IdsAlertInlineView {...props} onInternalDismiss={() => setDismissed(true)} />
  );
}

function IdsAlertGlobalView(
  props: Extract<IdsAlertProps, { display: "global" }> & {
    onInternalDismiss: () => void;
  },
) {
  const {
    severity = "critical",
    message,
    onLinkClick,
    actionLabel,
    onAction,
    dismissible,
    onDismiss,
    carousel,
    onInternalDismiss,
  } = props;

  const link = resolveLink(props);
  const showAction = Boolean(actionLabel);
  const showLink = Boolean(link?.label);
  const showCarousel = Boolean(carousel);
  const showDismiss =
    (dismissible ?? true) &&
    (severity !== "critical" || (showCarousel && !showAction));
  const counterText =
    showCarousel && carousel
      ? `${Math.max(1, carousel.currentItem)} of ${Math.max(1, carousel.totalItems)}`
      : "";
  const icon = globalSeverityToIcon[severity];

  return (
    <section
      className={styles["ids-alert-global"]}
      data-ids="ids-alert"
      data-display="global"
      data-severity={severity}
      role="alert"
      aria-live="assertive"
      data-carousel={showCarousel ? "true" : "false"}
    >
      {showCarousel && carousel ? (
        <div className={styles["ids-alert-global-carousel-rail"]}>
          <button
            type="button"
            className={styles["ids-alert-global-carousel-button"]}
            aria-label="Previous alert"
            onClick={carousel.onPrevious}
          >
            <IdsIcon
              shape="chev-left-16"
              variant="img"
              size={12}
              className={styles["ids-alert-global-carousel-chevron"]}
            />
          </button>
          <span className={styles["ids-alert-global-carousel-count"]}>{counterText}</span>
          <button
            type="button"
            className={styles["ids-alert-global-carousel-button"]}
            aria-label="Next alert"
            onClick={carousel.onNext}
          >
            <IdsIcon
              shape="chev-right-16"
              variant="img"
              size={12}
              className={styles["ids-alert-global-carousel-chevron"]}
            />
          </button>
        </div>
      ) : null}

      <div className={styles["ids-alert-global-content"]}>
        <div className={styles["ids-alert-global-icon-wrap"]}>
          <IdsIcon
            shape={icon.shape}
            variant={icon.variant}
            color={icon.color}
            size={16}
            className={styles["ids-alert-global-icon"]}
          />
        </div>
        <p className={styles["ids-alert-global-message"]}>
          {message}
          {showLink ? " " : null}
          {showLink && link ? (
            link.href ? (
              <a
                href={link.href}
                className={styles["ids-alert-global-link"]}
                onClick={onLinkClick}
              >
                {link.label}
              </a>
            ) : (
              <button
                type="button"
                className={styles["ids-alert-global-link-button"]}
                onClick={onLinkClick}
              >
                {link.label}
              </button>
            )
          ) : null}
        </p>
      </div>

      <div
        className={styles["ids-alert-global-actions"]}
        data-has-action={showAction ? "true" : "false"}
      >
        {showAction ? (
          <button
            type="button"
            className={styles["ids-alert-global-action"]}
            onClick={onAction}
          >
            {actionLabel}
          </button>
        ) : null}
        {showDismiss ? (
          <button
            type="button"
            className={styles["ids-alert-global-dismiss"]}
            aria-label="Dismiss alert"
            onClick={() => {
              onInternalDismiss();
              onDismiss?.();
            }}
          >
            <IdsIcon
              shape="shape-x"
              variant="mask"
              size={12}
              className={styles["ids-alert-global-dismiss-icon"]}
            />
          </button>
        ) : null}
      </div>
    </section>
  );
}

function IdsAlertInlineView(
  props: Extract<IdsAlertProps, { display: "inline" }> & {
    onInternalDismiss: () => void;
  },
) {
  const {
    severity = "informational",
    message,
    title,
    density = "compact",
    onLinkClick,
    actionLabel,
    onAction,
    dismissible,
    onDismiss,
    onInternalDismiss,
  } = props;

  const link = resolveLink(props);
  const showTitle = density === "detailed" && Boolean(title);
  const showLink = Boolean(link?.label);
  const showAction = Boolean(actionLabel);
  const showDismiss = (dismissible ?? true) && severity !== "critical";
  const densityClass =
    density === "detailed"
      ? styles["ids-alert-inline--detailed"]
      : styles["ids-alert-inline--compact"];
  const actionInTitleRow = showTitle && showAction;
  const showTrailing = (!showTitle && showAction) || showDismiss;

  const actionButton = showAction ? (
    <button
      type="button"
      className={styles["ids-alert-inline-action"]}
      onClick={onAction}
    >
      {actionLabel}
    </button>
  ) : null;

  return (
    <div
      className={cx(styles["ids-alert-inline"], densityClass)}
      data-ids="ids-alert"
      data-display="inline"
      data-severity={severity}
      data-density={density}
      role="alert"
    >
      <div className={styles["ids-alert-inline-main"]}>
        <span className={styles["ids-alert-inline-icon-wrap"]}>
          <IdsIcon
            shape={inlineSeverityToIcon[severity]}
            variant="img"
            size={16}
            className={styles["ids-alert-inline-icon"]}
          />
        </span>
        <div className={styles["ids-alert-inline-text"]}>
          {showTitle ? (
            <div className={styles["ids-alert-inline-title-row"]}>
              <p className={styles["ids-alert-inline-title"]}>{title}</p>
              {actionInTitleRow ? actionButton : null}
            </div>
          ) : null}
          <p className={styles["ids-alert-inline-message"]}>
            {message}
            {showLink ? " " : null}
            {showLink && link ? (
              link.href ? (
                <a
                  href={link.href}
                  className={styles["ids-alert-inline-link"]}
                  onClick={onLinkClick}
                >
                  {link.label}
                </a>
              ) : (
                <button
                  type="button"
                  className={styles["ids-alert-inline-link-button"]}
                  onClick={onLinkClick}
                >
                  {link.label}
                </button>
              )
            ) : null}
          </p>
        </div>
      </div>
      {showTrailing ? (
        <div
          className={styles["ids-alert-inline-trailing"]}
          data-has-action={!showTitle && showAction ? "true" : "false"}
        >
          {!showTitle && showAction ? actionButton : null}
          {showDismiss ? (
            <button
              type="button"
              className={styles["ids-alert-inline-dismiss"]}
              onClick={() => {
                onInternalDismiss();
                onDismiss?.();
              }}
              aria-label="Dismiss alert"
            >
              <IdsIcon
                shape="shape-x"
                variant="img"
                size={12}
                className={styles["ids-alert-inline-dismiss-icon"]}
              />
            </button>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

export default IdsAlert;
