// lib/angular/ids/dashboard/ids-dashboard.component.ts
/**
 * IDS Dashboard — Angular implementation generated from design-spec.
 *
 * Path: `lib/angular/ids/dashboard`
 * Source: `components/ids/dashboard/design-spec.md`
 * Theme: `components/ids-theme.css`
 * React parity: `lib/react/ids/dashboard` (branch usr/muthu/lib)
 *
 * Anatomy:
 *   IdsDashboard
 *     IdsDashboardGrid
 *       IdsDashboardItem+ → IdsCard (size span-1|2|3, showDivider=showDividerInCard)
 *
 * Accepted trees (React collectMainSlots parity):
 *   ids-dashboard → ids-card+
 *   ids-dashboard → ids-dashboard-item+
 *   ids-dashboard → ids-dashboard-grid → ids-dashboard-item+|ids-card+
 */

import { CommonModule } from "@angular/common";
import {
  AfterContentInit,
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChild,
  ContentChildren,
  ElementRef,
  EventEmitter,
  HostBinding,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  QueryList,
  SimpleChanges,
  ViewEncapsulation,
} from "@angular/core";
import { Subscription } from "rxjs";
import { cx } from "../../shared/utils/cx";
import {
  IDS_DASHBOARD_CARD_OVERRIDE,
  type IdsDashboardCardHost,
} from "../card/ids-card.context";
import { IdsCardComponent } from "../card/ids-card.component";
import {
  IDS_DASHBOARD_CONTEXT,
  type IdsDashboardRuntimeContext,
} from "./ids-dashboard.context";
import { IdsDashboardGridComponent } from "./ids-dashboard-grid.component";
import { IdsDashboardItemComponent } from "./ids-dashboard-item.component";
import {
  dashboardItemKey,
  resolveBoolean,
} from "./ids-dashboard.utils";

@Component({
  selector: "ids-dashboard",
  standalone: true,
  imports: [CommonModule],
  templateUrl: "./ids-dashboard.component.html",
  styleUrl: "./ids-dashboard.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [
    { provide: IDS_DASHBOARD_CONTEXT, useExisting: IdsDashboardComponent },
    { provide: IDS_DASHBOARD_CARD_OVERRIDE, useExisting: IdsDashboardComponent },
  ],
})
export class IdsDashboardComponent
  implements
    IdsDashboardRuntimeContext,
    IdsDashboardCardHost,
    AfterContentInit,
    AfterViewInit,
    OnChanges,
    OnDestroy
{
  @ContentChild(IdsDashboardGridComponent)
  gridSlot?: IdsDashboardGridComponent;

  @ContentChildren(IdsDashboardItemComponent, { descendants: true })
  private itemQuery?: QueryList<IdsDashboardItemComponent>;

  @ContentChildren(IdsCardComponent, { descendants: true })
  private cardQuery?: QueryList<IdsCardComponent>;

  /**
   * When `true` (default), nested Cards keep body dividers (`showDivider`).
   * When `false`, forces nested Cards to `showDivider=false`.
   * Dashboard injection wins over any `showDivider` on the Card child.
   */
  @Input() showDividerInCard = true;
  /**
   * When `true`, nested Card items are draggable and can be reordered
   * (HTML5 drag-and-drop). Default `false`.
   */
  @Input() enableDragAndDrop = false;
  /** @deprecated Use `enableDragAndDrop` */
  @Input() cardsDraggable?: boolean;
  @Input() className?: string;

  /** Fires after a successful drag reorder with ordered child keys. */
  @Output() readonly cardsReorder = new EventEmitter<string[]>();

  dragKey: string | null = null;
  overKey: string | null = null;

  private order: string[] = [];
  private subs = new Subscription();

  constructor(
    private readonly cdr: ChangeDetectorRef,
    private readonly host: ElementRef<HTMLElement>,
  ) {}

  get dragEnabled(): boolean {
    return resolveBoolean(this.enableDragAndDrop ?? this.cardsDraggable, false);
  }

  get dividerOn(): boolean {
    return resolveBoolean(this.showDividerInCard, true);
  }

  get hasExplicitGrid(): boolean {
    return Boolean(this.gridSlot);
  }

  @HostBinding("class")
  get hostClass(): string {
    return cx("IdsDashboard", this.className);
  }

  @HostBinding("attr.data-ids")
  get dataIds(): string {
    return "IdsDashboard";
  }

  @HostBinding("attr.aria-label")
  get ariaLabel(): string {
    return "Dashboard";
  }

  @HostBinding("attr.role")
  get role(): string {
    return "region";
  }

  @HostBinding("attr.data-show-divider-in-card")
  get dataShowDivider(): string {
    return this.dividerOn ? "true" : "false";
  }

  @HostBinding("attr.data-enable-drag-and-drop")
  get dataDrag(): string {
    return this.dragEnabled ? "true" : "false";
  }

  @HostBinding("attr.data-cards-draggable")
  get dataCardsDraggable(): string {
    return this.dragEnabled ? "true" : "false";
  }

  ngAfterContentInit(): void {
    this.syncProjected();
    if (this.itemQuery) {
      this.subs.add(this.itemQuery.changes.subscribe(() => this.syncProjected()));
    }
    if (this.cardQuery) {
      this.subs.add(this.cardQuery.changes.subscribe(() => this.syncProjected()));
    }
  }

  ngAfterViewInit(): void {
    queueMicrotask(() => this.syncProjected());
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (
      changes["showDividerInCard"] ||
      changes["enableDragAndDrop"] ||
      changes["cardsDraggable"]
    ) {
      this.refreshCards();
      this.syncProjected();
    }
  }

  ngOnDestroy(): void {
    this.subs.unsubscribe();
  }

  onItemDragStart(itemKey: string, event: DragEvent): void {
    if (!this.dragEnabled) return;
    event.dataTransfer?.setData("text/plain", itemKey);
    if (event.dataTransfer) event.dataTransfer.effectAllowed = "move";
    this.dragKey = itemKey;
    this.refreshItems();
  }

  onItemDragOver(itemKey: string, event: DragEvent): void {
    if (!this.dragEnabled || this.dragKey == null) return;
    event.preventDefault();
    if (event.dataTransfer) event.dataTransfer.dropEffect = "move";
    if (this.overKey !== itemKey) {
      this.overKey = itemKey;
      this.refreshItems();
    }
  }

  onItemDrop(itemKey: string, event: DragEvent): void {
    if (!this.dragEnabled) return;
    event.preventDefault();
    const from = event.dataTransfer?.getData("text/plain") || this.dragKey;
    if (from) this.reorder(from, itemKey);
    this.dragKey = null;
    this.overKey = null;
    this.refreshItems();
  }

  onItemDragEnd(): void {
    this.dragKey = null;
    this.overKey = null;
    this.refreshItems();
  }

  private syncProjected(): void {
    const items = this.itemQuery?.toArray() ?? [];
    items.forEach((item, index) => {
      item.resolvedKey = dashboardItemKey(item.itemKey, index);
    });

    if (items.length > 0) {
      const keys = items.map((i) => i.resolvedKey);
      this.order = this.mergeOrder(this.order, keys);
      this.applyOrderStyles(items.map((i) => i.resolvedKey));
    } else {
      this.syncBareCards();
    }
    this.refreshCards();
    this.refreshItems();
    this.cdr.markForCheck();
  }

  private syncBareCards(): void {
    const cards = this.cardQuery?.toArray() ?? [];
    const keys = cards.map((_, index) => dashboardItemKey(undefined, index));
    this.order = this.mergeOrder(this.order, keys);

    cards.forEach((card, index) => {
      const el = card.cardRootEl;
      if (!el) return;
      const key = keys[index]!;
      el.setAttribute("data-dashboard-item", key);
      el.setAttribute(
        "data-card-draggable",
        this.dragEnabled ? "true" : "false",
      );
      if (this.dragEnabled) {
        el.setAttribute("draggable", "true");
        el.ondragstart = (e) => this.onItemDragStart(key, e);
        el.ondragover = (e) => this.onItemDragOver(key, e);
        el.ondrop = (e) => this.onItemDrop(key, e);
        el.ondragend = () => this.onItemDragEnd();
      } else {
        el.removeAttribute("draggable");
        el.ondragstart = null;
        el.ondragover = null;
        el.ondrop = null;
        el.ondragend = null;
      }
      const pos = this.order.indexOf(key);
      el.style.order = String(pos >= 0 ? pos : index);
      el.setAttribute(
        "data-dragging",
        this.dragKey === key ? "true" : "false",
      );
      el.setAttribute(
        "data-drop-target",
        this.overKey === key && this.dragKey !== key ? "true" : "false",
      );
    });
  }

  private applyOrderStyles(keys: string[]): void {
    const root = this.host.nativeElement;
    keys.forEach((key) => {
      const pos = this.order.indexOf(key);
      const el = root.querySelector(
        `[data-dashboard-item="${cssEscape(key)}"]`,
      ) as HTMLElement | null;
      if (el && pos >= 0) el.style.order = String(pos);
    });
  }

  private mergeOrder(prev: string[], defaultOrder: string[]): string[] {
    const nextKeys = new Set(defaultOrder);
    const kept = prev.filter((k) => nextKeys.has(k));
    const added = defaultOrder.filter((k) => !kept.includes(k));
    return [...kept, ...added];
  }

  private reorder(fromKey: string, toKey: string): void {
    if (fromKey === toKey) return;
    const next = [...this.order];
    const from = next.indexOf(fromKey);
    const to = next.indexOf(toKey);
    if (from < 0 || to < 0) return;
    next.splice(from, 1);
    next.splice(to, 0, fromKey);
    this.order = next;
    this.cardsReorder.emit([...next]);
    this.applyOrderStyles(this.order);
    this.syncBareCards();
  }

  private refreshItems(): void {
    this.itemQuery?.forEach((item) => item.markForCheck());
    this.cdr.markForCheck();
  }

  private refreshCards(): void {
    this.cardQuery?.forEach((card) => card.markForCheck());
  }
}

function cssEscape(value: string): string {
  if (typeof CSS !== "undefined" && typeof CSS.escape === "function") {
    return CSS.escape(value);
  }
  return value.replace(/"/g, '\\"');
}

<ng-content select="ids-dashboard-grid" />
<div
  class="IdsDashboardGrid"
  data-ids="IdsDashboardGrid"
  [hidden]="hasExplicitGrid"
>
  <ng-content />
</div>

// lib/react/ids/dashboard/IdsDashboard.tsx
/**
 * IDS Dashboard — React implementation generated from design-spec.
 *
 * Path: `lib/react/ids/dashboard`
 * Source: `components/ids/dashboard/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * Anatomy (deterministic child order — root is Dashboard / IdsDashboard, not DashboardRoot).
 * Public names are Ids camelCase identifiers, not dotted compounds (Dashboard.Grid).
 *   IdsDashboard
 *     IdsDashboardGrid
 *       IdsDashboardItem+ → IdsCard (size span-1|2|3, showDivider=showDividerInCard)
 *
 * Nested Card chrome follows Card design-spec except:
 *   --card-border-color: var(--color-border-gray-neutral-light) on IdsDashboard
 *   showDivider injected from showDividerInCard (Dashboard wins)
 *
 * Prop-driven IdsCard children emit this tree. Compound children fill the same slots.
 * No @base-ui-components dependency.
 */

import React, {
  cloneElement,
  createContext,
  isValidElement,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type DragEvent,
  type HTMLAttributes,
  type ReactElement,
  type ReactNode,
} from "react";
import {
  isIdsCardElement,
  type IdsCardProps,
  type IdsCardSize,
} from "../card";
import {
  childKey,
  collectMainSlots,
  getDashboardSlot,
  markDashboardSlot,
  readCardSize,
  readSizeFromChildren,
  readSizeFromItem,
} from "./IdsDashboard.compose";
import styles from "./IdsDashboard.module.css";

const s = {
  root: styles["IdsDashboard"],
  grid: styles["IdsDashboardGrid"],
  item: styles["IdsDashboardItem"],
};

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

function resolveBoolean(value: unknown, fallback: boolean): boolean {
  return typeof value === "boolean" ? value : fallback;
}

function injectShowDivider(node: ReactNode, showDivider: boolean): ReactNode {
  return React.Children.map(node, (child) => {
    if (!isValidElement(child)) return child;
    if (isIdsCardElement(child)) {
      return cloneElement(child as ReactElement<IdsCardProps>, { showDivider });
    }
    return child;
  });
}

/* -------------------------------------------------------------------------- */
/* Context                                                                    */
/* -------------------------------------------------------------------------- */

interface IdsDashboardContextValue {
  showDividerInCard: boolean;
  dragEnabled: boolean;
  dragKey: string | null;
  overKey: string | null;
  onItemDragStart: (itemKey: string) => (event: DragEvent) => void;
  onItemDragOver: (itemKey: string) => (event: DragEvent) => void;
  onItemDrop: (itemKey: string) => (event: DragEvent) => void;
  onItemDragEnd: () => void;
}

const IdsDashboardContext = createContext<IdsDashboardContextValue | null>(null);

function useDashboard(slot: string): IdsDashboardContextValue {
  const ctx = useContext(IdsDashboardContext);
  if (!ctx) {
    throw new Error(`${slot} must be used within Dashboard.`);
  }
  return ctx;
}

/* -------------------------------------------------------------------------- */
/* Slots                                                                      */
/* -------------------------------------------------------------------------- */

export interface IdsDashboardGridProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
}

export function IdsDashboardGrid({
  children,
  className,
  ...rest
}: IdsDashboardGridProps) {
  useDashboard("IdsDashboardGrid");
  return (
    <div
      className={cx(s.grid, className)}
      data-ids="IdsDashboardGrid"
      {...rest}
    >
      {children}
    </div>
  );
}
IdsDashboardGrid.displayName = "IdsDashboardGrid";
markDashboardSlot(IdsDashboardGrid, "grid");

export interface IdsDashboardItemProps extends HTMLAttributes<HTMLDivElement> {
  children?: ReactNode;
  /** Column span in the Dashboard grid. Inherited from nested IdsCard `size` when omitted. */
  size?: IdsCardSize;
  /** Stable identity for drag reorder. Falls back to React `key` then index. */
  itemKey?: string;
}

export function IdsDashboardItem({
  children,
  className,
  size: sizeProp,
  itemKey,
  ...rest
}: IdsDashboardItemProps) {
  const ctx = useDashboard("IdsDashboardItem");
  const size = readSizeFromChildren(children, sizeProp);
  const resolvedKey = itemKey ?? "dashboard-item";
  const dragging = ctx.dragEnabled && ctx.dragKey === resolvedKey;
  const dropTarget =
    ctx.dragEnabled && ctx.overKey === resolvedKey && ctx.dragKey !== resolvedKey;

  return (
    <div
      className={cx(s.item, className)}
      data-ids="IdsDashboardItem"
      data-card-size={size}
      data-dashboard-item={resolvedKey}
      data-card-draggable={ctx.dragEnabled ? "true" : "false"}
      data-dragging={dragging ? "true" : "false"}
      data-drop-target={dropTarget ? "true" : "false"}
      {...rest}
      draggable={ctx.dragEnabled}
      onDragStart={ctx.onItemDragStart(resolvedKey)}
      onDragOver={ctx.onItemDragOver(resolvedKey)}
      onDrop={ctx.onItemDrop(resolvedKey)}
      onDragEnd={ctx.onItemDragEnd}
    >
      {injectShowDivider(children, ctx.showDividerInCard)}
    </div>
  );
}
IdsDashboardItem.displayName = "IdsDashboardItem";
markDashboardSlot(IdsDashboardItem, "item");

/* -------------------------------------------------------------------------- */
/* Root                                                                       */
/* -------------------------------------------------------------------------- */

export interface IdsDashboardProps {
  children: ReactNode;
  /**
   * When `true` (default), nested Cards keep body dividers (`showDivider`).
   * When `false`, injects `showDivider={false}` onto each nested Card.
   * Dashboard injection wins over any `showDivider` on the JSX Card child.
   */
  showDividerInCard?: boolean;
  /**
   * When `true`, nested Card items are draggable and can be reordered
   * (HTML5 drag-and-drop). Default `false`.
   */
  enableDragAndDrop?: boolean;
  /** @deprecated Use `enableDragAndDrop` */
  cardsDraggable?: boolean;
  /** Fires after a successful drag reorder with ordered child keys. */
  onCardsReorder?: (orderedKeys: string[]) => void;
  className?: string;
}

interface PreparedItem {
  key: string;
  size: IdsCardSize;
  node: ReactElement;
}

function prepareItems(children: ReactNode): PreparedItem[] {
  const slots = collectMainSlots(children);
  const sources: ReactElement[] =
    slots.items.length > 0 ? slots.items : slots.tiles;

  return sources.map((child, index) => {
    const key = childKey(child, index);
    if (getDashboardSlot(child.type) === "item") {
      const size = readSizeFromItem(child);
      const next = cloneElement(child as ReactElement<IdsDashboardItemProps>, {
        itemKey: (child.props as IdsDashboardItemProps).itemKey ?? key,
        size: (child.props as IdsDashboardItemProps).size ?? size,
      });
      return { key, size, node: next };
    }
    const size = isIdsCardElement(child) ? readCardSize(child) : "span-1";
    return {
      key,
      size,
      node: (
        <IdsDashboardItem key={key} itemKey={key} size={size}>
          {child}
        </IdsDashboardItem>
      ),
    };
  });
}

export function IdsDashboard({
  children,
  showDividerInCard,
  enableDragAndDrop,
  cardsDraggable,
  onCardsReorder,
  className,
}: IdsDashboardProps) {
  const dividerOn = resolveBoolean(showDividerInCard, true);
  const dragEnabled = resolveBoolean(enableDragAndDrop ?? cardsDraggable, false);
  const slots = collectMainSlots(children);
  const prepared = useMemo(() => prepareItems(children), [children]);

  const defaultOrder = useMemo(
    () => prepared.map((entry) => entry.key),
    [prepared],
  );

  const [order, setOrder] = useState<string[]>(defaultOrder);
  const [dragKey, setDragKey] = useState<string | null>(null);
  const [overKey, setOverKey] = useState<string | null>(null);

  useEffect(() => {
    setOrder((prev) => {
      const nextKeys = new Set(defaultOrder);
      const kept = prev.filter((k) => nextKeys.has(k));
      const added = defaultOrder.filter((k) => !kept.includes(k));
      return [...kept, ...added];
    });
  }, [defaultOrder]);

  const byKey = useMemo(() => {
    const map = new Map<string, PreparedItem>();
    prepared.forEach((entry) => {
      map.set(entry.key, entry);
    });
    return map;
  }, [prepared]);

  const reorder = useCallback(
    (fromKey: string, toKey: string) => {
      if (fromKey === toKey) return;
      setOrder((prev) => {
        const next = [...prev];
        const from = next.indexOf(fromKey);
        const to = next.indexOf(toKey);
        if (from < 0 || to < 0) return prev;
        next.splice(from, 1);
        next.splice(to, 0, fromKey);
        onCardsReorder?.(next);
        return next;
      });
    },
    [onCardsReorder],
  );

  const onItemDragStart = useCallback(
    (itemKey: string) => (event: DragEvent) => {
      if (!dragEnabled) return;
      event.dataTransfer.effectAllowed = "move";
      event.dataTransfer.setData("text/plain", itemKey);
      setDragKey(itemKey);
    },
    [dragEnabled],
  );

  const onItemDragOver = useCallback(
    (itemKey: string) => (event: DragEvent) => {
      if (!dragEnabled || dragKey == null) return;
      event.preventDefault();
      event.dataTransfer.dropEffect = "move";
      setOverKey(itemKey);
    },
    [dragEnabled, dragKey],
  );

  const onItemDrop = useCallback(
    (itemKey: string) => (event: DragEvent) => {
      if (!dragEnabled) return;
      event.preventDefault();
      const from = event.dataTransfer.getData("text/plain") || dragKey;
      if (from) reorder(from, itemKey);
      setDragKey(null);
      setOverKey(null);
    },
    [dragEnabled, dragKey, reorder],
  );

  const onItemDragEnd = useCallback(() => {
    setDragKey(null);
    setOverKey(null);
  }, []);

  const ctx: IdsDashboardContextValue = {
    showDividerInCard: dividerOn,
    dragEnabled,
    dragKey,
    overKey,
    onItemDragStart,
    onItemDragOver,
    onItemDrop,
    onItemDragEnd,
  };

  const orderedNodes = order.map((key) => {
    const entry = byKey.get(key);
    if (!entry) return null;
    return cloneElement(entry.node, { key });
  });

  const grid =
    slots.grid != null ? (
      cloneElement(slots.grid as ReactElement<IdsDashboardGridProps>, undefined, orderedNodes)
    ) : (
      <IdsDashboardGrid>{orderedNodes}</IdsDashboardGrid>
    );

  return (
    <IdsDashboardContext.Provider value={ctx}>
      <section
        className={cx(s.root, className)}
        aria-label="Dashboard"
        data-ids="IdsDashboard"
        data-show-divider-in-card={dividerOn ? "true" : "false"}
        data-enable-drag-and-drop={dragEnabled ? "true" : "false"}
        data-cards-draggable={dragEnabled ? "true" : "false"}
      >
        {grid}
      </section>
    </IdsDashboardContext.Provider>
  );
}

IdsDashboard.displayName = "IdsDashboard";

export const IdsDashboardCompound = Object.assign(IdsDashboard, {
  Grid: IdsDashboardGrid,
  Item: IdsDashboardItem,
});

/** Anatomy alias — root is Dashboard, not DashboardRoot. */
export const Dashboard = IdsDashboardCompound;

export default IdsDashboardCompound;
