// lib/angular/ids/pagination/ids-pagination.component.ts
import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  ViewChild,
} from "@angular/core";
import { NgClass } from "@angular/common";
import {
  PAGINATION_SPEC_ACCURATE_DEFAULTS,
  type IdsPaginationBackground,
  type IdsPaginationCollapseSlot,
  type IdsPaginationDropdownState,
  type IdsPaginationResponsiveMode,
} from "@component-contracts/ids/pagination.contract";
import { IdsIconComponent } from "../icon/ids-icon.component";

const DEFAULT_COLLAPSE_ORDER: IdsPaginationCollapseSlot[] = ["results-per-page"];
const COLLAPSE_SLOTS = new Set<IdsPaginationCollapseSlot>([
  "results-per-page",
  "page-input",
  "first-last-buttons",
]);

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

function normalizePageSizeOptions(options: number[] | undefined): number[] {
  if (!options || options.length === 0) {
    return [...PAGINATION_SPEC_ACCURATE_DEFAULTS.pageSizeOptions];
  }
  const uniquePositive = Array.from(
    new Set(options.filter((value) => Number.isFinite(value) && value > 0)),
  );
  return uniquePositive.length > 0
    ? uniquePositive
    : [...PAGINATION_SPEC_ACCURATE_DEFAULTS.pageSizeOptions];
}

function resolveResponsiveMode(
  value: IdsPaginationResponsiveMode | string | undefined,
): IdsPaginationResponsiveMode {
  return value === "keep-inline" ? "keep-inline" : "auto";
}

function resolveCollapseOrder(
  value: IdsPaginationCollapseSlot[] | undefined,
): IdsPaginationCollapseSlot[] {
  if (!value || value.length === 0) return [...DEFAULT_COLLAPSE_ORDER];
  const filtered = value.filter((slot) => COLLAPSE_SLOTS.has(slot));
  return filtered.length > 0 ? filtered : [...DEFAULT_COLLAPSE_ORDER];
}

function defaultPageCountText(_currentPage: number, totalPages: number): string {
  if (totalPages <= 1) return "1 page";
  return `of ${totalPages}`;
}

type PerPageMenuPlacement = "below" | "above";
type PaginationMenuPos = { top: number; left: number; width: number };

@Component({
  selector: "ids-pagination",
  standalone: true,
  imports: [NgClass, IdsIconComponent],
  templateUrl: "./ids-pagination.component.html",
  styleUrl: "./ids-pagination.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsPaginationComponent implements OnChanges, AfterViewInit, OnDestroy {
  readonly navIconSize = 16;
  readonly caretIconSize = 10;
  readonly caretIconShape = "arrow-drop-tri-caret";
  readonly firstPageIconShape = "double-chev-left";
  readonly previousPageIconShape = "chev-left";
  readonly nextPageIconShape = "chev-right";
  readonly lastPageIconShape = "double-chev-right";

  @ViewChild("root") rootRef?: ElementRef<HTMLElement>;
  @ViewChild("perPageTrigger") perPageTrigger?: ElementRef<HTMLButtonElement>;
  @ViewChild("perPageMenu") perPageMenu?: ElementRef<HTMLUListElement>;

  @Input() currentPage = PAGINATION_SPEC_ACCURATE_DEFAULTS.currentPage;
  @Input() totalPages = PAGINATION_SPEC_ACCURATE_DEFAULTS.totalPages;
  @Input() pageSize = PAGINATION_SPEC_ACCURATE_DEFAULTS.pageSize;
  @Input() pageSizeOptions: number[] = [
    ...PAGINATION_SPEC_ACCURATE_DEFAULTS.pageSizeOptions,
  ];
  @Input() showPerPage = PAGINATION_SPEC_ACCURATE_DEFAULTS.showPerPage;
  /** When `false`, hides first/last nav buttons (Storybook override; React lib always shows unless responsively collapsed). */
  @Input() showFirstLast = PAGINATION_SPEC_ACCURATE_DEFAULTS.showFirstLast;
  /** Demo/testing only — forces per-page menu open state and placement. */
  @Input() dropdownState: IdsPaginationDropdownState =
    PAGINATION_SPEC_ACCURATE_DEFAULTS.dropdownState;
  @Input() background: IdsPaginationBackground =
    PAGINATION_SPEC_ACCURATE_DEFAULTS.background;
  @Input() embeddedInDatagrid = false;
  @Input() disabled = PAGINATION_SPEC_ACCURATE_DEFAULTS.disabled;
  @Input() responsiveMode: IdsPaginationResponsiveMode =
    PAGINATION_SPEC_ACCURATE_DEFAULTS.responsiveMode;
  @Input() collapseOrder: IdsPaginationCollapseSlot[] = [
    ...PAGINATION_SPEC_ACCURATE_DEFAULTS.collapseOrder,
  ];
  @Input() summaryFormatter?: (currentPage: number, totalPages: number) => string;

  @Output() readonly pageChange = new EventEmitter<number>();
  @Output() readonly pageSizeChange = new EventEmitter<number>();
  @Output() readonly firstPageNavigate = new EventEmitter<void>();
  @Output() readonly previousPageNavigate = new EventEmitter<void>();
  @Output() readonly nextPageNavigate = new EventEmitter<void>();
  @Output() readonly lastPageNavigate = new EventEmitter<void>();

  perPageMenuOpen = false;
  menuPlacement: PerPageMenuPlacement = "below";
  pageInputValue = String(this.currentPage);
  collapseLevel = 0;
  perPageMenuPos: PaginationMenuPos | null = null;

  private resizeObserver?: ResizeObserver;
  private overlayRepositionCleanup: (() => void) | null = null;

  constructor(private readonly cdr: ChangeDetectorRef) {}

  get safeTotalPages(): number {
    return Math.max(1, this.totalPages);
  }

  get safeCurrentPage(): number {
    return clamp(this.currentPage, 1, this.safeTotalPages);
  }

  get safePageSizeOptions(): number[] {
    return normalizePageSizeOptions(this.pageSizeOptions);
  }

  get safePageSize(): number {
    return this.safePageSizeOptions.includes(this.pageSize)
      ? this.pageSize
      : this.safePageSizeOptions[0];
  }

  get atFirstPage(): boolean {
    return this.safeCurrentPage <= 1;
  }

  get atLastPage(): boolean {
    return this.safeCurrentPage >= this.safeTotalPages;
  }

  get isSinglePage(): boolean {
    return this.safeTotalPages <= 1;
  }

  get resolvedResponsiveMode(): IdsPaginationResponsiveMode {
    return resolveResponsiveMode(this.responsiveMode);
  }

  get resolvedCollapseOrder(): IdsPaginationCollapseSlot[] {
    return resolveCollapseOrder(this.collapseOrder);
  }

  get resolvedPerPageDropdownState(): IdsPaginationDropdownState {
    if (this.dropdownState !== "collapsed") {
      return this.dropdownState;
    }
    if (!this.perPageMenuOpen) return "collapsed";
    return this.menuPlacement === "above" ? "expanded-above" : "expanded-below";
  }

  get collapsedSlots(): Set<IdsPaginationCollapseSlot> {
    return new Set(this.resolvedCollapseOrder.slice(0, this.collapseLevel));
  }

  get renderResultsGroup(): boolean {
    return this.showPerPage && !this.collapsedSlots.has("results-per-page");
  }

  get pageInputCollapsed(): boolean {
    return this.collapsedSlots.has("page-input");
  }

  get firstLastCollapsed(): boolean {
    return !this.showFirstLast || this.collapsedSlots.has("first-last-buttons");
  }

  get countText(): string {
    return (
      this.summaryFormatter?.(this.safeCurrentPage, this.safeTotalPages) ??
      defaultPageCountText(this.safeCurrentPage, this.safeTotalPages)
    );
  }

  get caretIconColor(): string {
    return this.disabled
      ? "var(--color-icon-gray-disabled)"
      : "var(--color-icon-gray-neutral-base)";
  }

  get rootClass(): Record<string, boolean> {
    return {
      rootWhite: this.background === "white",
      rootNone: this.background === "none",
      rootGray: this.background === "gray",
      rootEmbedded: this.embeddedInDatagrid,
    };
  }

  ngOnChanges(): void {
    this.pageInputValue = String(this.safeCurrentPage);
    if (this.resolvedPerPageDropdownState !== "collapsed") {
      this.perPageMenuOpen = true;
      this.bindOverlayRepositionListeners();
      this.scheduleOverlayPortalAndPosition();
    }
    this.scheduleResponsiveCheck();
  }

  ngAfterViewInit(): void {
    this.setupResponsiveObserver();
    this.scheduleResponsiveCheck();
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
    this.resizeObserver = undefined;
    this.unbindOverlayRepositionListeners();
  }

  goToPage(nextPage: number): void {
    if (this.disabled) return;
    const clamped = clamp(nextPage, 1, this.safeTotalPages);
    this.pageInputValue = String(clamped);
    this.pageChange.emit(clamped);
  }

  onFirstPage(): void {
    if (this.disabled || this.atFirstPage) return;
    this.firstPageNavigate.emit();
    this.goToPage(1);
  }

  onPreviousPage(): void {
    if (this.disabled || this.atFirstPage) return;
    this.previousPageNavigate.emit();
    this.goToPage(this.safeCurrentPage - 1);
  }

  onNextPage(): void {
    if (this.disabled || this.atLastPage) return;
    this.nextPageNavigate.emit();
    this.goToPage(this.safeCurrentPage + 1);
  }

  onLastPage(): void {
    if (this.disabled || this.atLastPage) return;
    this.lastPageNavigate.emit();
    this.goToPage(this.safeTotalPages);
  }

  onPageInputChange(value: string): void {
    this.pageInputValue = value.replace(/[^\d]/g, "");
  }

  commitPageInput(): void {
    const parsed = Number.parseInt(this.pageInputValue, 10);
    if (!Number.isFinite(parsed)) {
      this.pageInputValue = String(this.safeCurrentPage);
      return;
    }
    this.goToPage(parsed);
  }

  onPageInputKeydown(event: KeyboardEvent): void {
    if (event.key === "Enter") {
      this.commitPageInput();
      (event.target as HTMLInputElement | null)?.blur();
    }
  }

  togglePerPageMenu(): void {
    if (this.disabled) return;
    this.perPageMenuOpen = !this.perPageMenuOpen;
    if (this.perPageMenuOpen) {
      this.bindOverlayRepositionListeners();
      this.scheduleOverlayPortalAndPosition();
    } else {
      this.closePerPageMenu();
    }
    this.cdr.markForCheck();
  }

  closePerPageMenu(): void {
    if (this.dropdownState !== "collapsed") return;
    this.perPageMenuOpen = false;
    this.perPageMenuPos = null;
    this.unbindOverlayRepositionListeners();
    this.cdr.markForCheck();
  }

  selectPageSize(size: number): void {
    this.pageSizeChange.emit(size);
    this.closePerPageMenu();
  }

  @HostListener("document:keydown", ["$event"])
  onDocumentKeydown(event: KeyboardEvent): void {
    if (event.key !== "Escape" || this.resolvedPerPageDropdownState === "collapsed") {
      return;
    }
    this.closePerPageMenu();
    this.perPageTrigger?.nativeElement.focus();
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMouseDown(event: MouseEvent): void {
    if (this.resolvedPerPageDropdownState === "collapsed") return;
    const target = event.target as Node | null;
    if (!target) return;
    if (this.perPageTrigger?.nativeElement.contains(target)) return;
    if (this.perPageMenu?.nativeElement.contains(target)) return;
    if ((target as HTMLElement).closest?.("[data-ids-pagination-per-page-menu]")) return;
    this.closePerPageMenu();
  }

  @HostListener("window:resize")
  @HostListener("window:scroll")
  onViewportChange(): void {
    if (this.resolvedPerPageDropdownState !== "collapsed") {
      this.syncMenuPlacement();
      this.updatePerPageMenuPos();
      this.cdr.markForCheck();
    }
  }

  private syncMenuPlacement(): void {
    if (this.dropdownState === "expanded-above") {
      this.menuPlacement = "above";
      return;
    }
    if (this.dropdownState === "expanded-below") {
      this.menuPlacement = "below";
      return;
    }

    const trigger = this.perPageTrigger?.nativeElement;
    if (!trigger) {
      this.menuPlacement = "below";
      return;
    }

    const rect = trigger.getBoundingClientRect();
    const viewportHeight = typeof window !== "undefined" ? window.innerHeight : rect.bottom + 200;
    const spaceBelow = viewportHeight - rect.bottom;
    const spaceAbove = rect.top;
    const estimatedMenuHeight = Math.max(
      this.perPageMenu?.nativeElement.offsetHeight ?? 0,
      this.safePageSizeOptions.length * 40,
    );

    this.menuPlacement =
      spaceBelow < estimatedMenuHeight && spaceAbove > spaceBelow ? "above" : "below";
  }

  private updatePerPageMenuPos(): void {
    const trigger = this.perPageTrigger?.nativeElement;
    const menu = this.perPageMenu?.nativeElement;
    if (!trigger) return;
    const rect = trigger.getBoundingClientRect();
    const width = rect.width;
    const left = rect.left;
    if (this.resolvedPerPageDropdownState === "expanded-above") {
      const menuHeight = menu?.getBoundingClientRect().height ?? 0;
      this.perPageMenuPos = { top: rect.top + 1 - menuHeight, left, width };
      return;
    }
    this.perPageMenuPos = { top: rect.top + rect.height - 1, left, width };
  }

  private portalToBody(el: HTMLElement | undefined): void {
    if (el && el.parentElement !== document.body) {
      document.body.appendChild(el);
    }
  }

  private scheduleOverlayPortalAndPosition(): void {
    requestAnimationFrame(() => {
      if (this.resolvedPerPageDropdownState === "collapsed") return;
      this.syncMenuPlacement();
      this.portalToBody(this.perPageMenu?.nativeElement);
      this.updatePerPageMenuPos();
      this.cdr.markForCheck();

      requestAnimationFrame(() => {
        if (this.resolvedPerPageDropdownState === "collapsed") return;
        this.updatePerPageMenuPos();
        this.cdr.markForCheck();
      });
    });
  }

  private bindOverlayRepositionListeners(): void {
    if (this.overlayRepositionCleanup) return;
    const onUpdate = () => {
      if (this.resolvedPerPageDropdownState === "collapsed") return;
      this.syncMenuPlacement();
      this.updatePerPageMenuPos();
      this.cdr.markForCheck();
    };
    window.addEventListener("resize", onUpdate);
    window.addEventListener("scroll", onUpdate, true);
    this.overlayRepositionCleanup = () => {
      window.removeEventListener("resize", onUpdate);
      window.removeEventListener("scroll", onUpdate, true);
      this.overlayRepositionCleanup = null;
    };
  }

  private unbindOverlayRepositionListeners(): void {
    this.overlayRepositionCleanup?.();
    this.overlayRepositionCleanup = null;
  }

  private setupResponsiveObserver(): void {
    this.resizeObserver?.disconnect();
    this.resizeObserver = undefined;

    if (this.resolvedResponsiveMode !== "auto") {
      this.collapseLevel = 0;
      return;
    }

    const root = this.rootRef?.nativeElement;
    if (!root || typeof ResizeObserver === "undefined") return;

    this.resizeObserver = new ResizeObserver(() => {
      this.collapseLevel = 0;
      this.cdr.markForCheck();
      requestAnimationFrame(() => this.checkResponsiveCollapse());
    });
    this.resizeObserver.observe(root);
  }

  private scheduleResponsiveCheck(): void {
    requestAnimationFrame(() => {
      if (this.resolvedResponsiveMode !== "auto") {
        this.collapseLevel = 0;
        this.cdr.markForCheck();
        return;
      }
      this.collapseLevel = 0;
      this.checkResponsiveCollapse();
    });
  }

  private checkResponsiveCollapse(): void {
    if (this.resolvedResponsiveMode !== "auto") return;
    const root = this.rootRef?.nativeElement;
    if (!root) return;
    if (root.scrollWidth <= root.clientWidth + 1) {
      this.cdr.markForCheck();
      return;
    }
    const order = this.resolvedCollapseOrder;
    if (this.collapseLevel < order.length) {
      this.collapseLevel += 1;
      this.cdr.markForCheck();
      requestAnimationFrame(() => this.checkResponsiveCollapse());
    }
  }
}

<nav
  #root
  class="root"
  [ngClass]="rootClass"
  aria-label="Pagination"
  data-ids="ids-pagination"
  [attr.data-background]="background"
  [attr.data-responsive-mode]="resolvedResponsiveMode"
>
  @if (renderResultsGroup) {
    <div class="resultsGroup" data-ids="ids-pagination-results">
      <span class="label">Show:</span>
      <div class="dropdownWrap">
        <button
          #perPageTrigger
          class="dropdownTrigger"
          type="button"
          [disabled]="disabled"
          aria-haspopup="listbox"
          [attr.aria-expanded]="resolvedPerPageDropdownState !== 'collapsed'"
          aria-label="Items per page"
          (click)="togglePerPageMenu()"
        >
          <span>{{ safePageSize }}</span>
          <ids-icon
            [shape]="caretIconShape"
            [size]="caretIconSize"
            variant="mask"
            [color]="caretIconColor"
          />
        </button>
      </div>
      <span class="label">per page</span>
    </div>
  }

  <div class="pageNavGroup" data-ids="ids-pagination-nav">
    @if (isSinglePage) {
      <span class="countText">{{ countText }}</span>
    } @else {
      <button
        class="iconButton"
        [class.iconButtonCollapsed]="firstLastCollapsed"
        type="button"
        [disabled]="disabled || atFirstPage"
        aria-label="First page"
        (click)="onFirstPage()"
      >
        <ids-icon
          [shape]="firstPageIconShape"
          [size]="navIconSize"
          variant="mask"
        />
      </button>
      <button
        class="iconButton"
        type="button"
        [disabled]="disabled || atFirstPage"
        aria-label="Previous page"
        (click)="onPreviousPage()"
      >
        <ids-icon
          [shape]="previousPageIconShape"
          [size]="navIconSize"
          variant="mask"
        />
      </button>
      <div class="pageInputWrap" [class.pageInputWrapCollapsed]="pageInputCollapsed">
        <input
          class="pageInput"
          [value]="pageInputValue"
          [disabled]="disabled"
          inputmode="numeric"
          aria-label="Current page"
          (input)="onPageInputChange($any($event.target).value)"
          (blur)="commitPageInput()"
          (keydown)="onPageInputKeydown($event)"
        />
      </div>
      <span class="countText">{{ countText }}</span>
      <button
        class="iconButton"
        type="button"
        [disabled]="disabled || atLastPage"
        aria-label="Next page"
        (click)="onNextPage()"
      >
        <ids-icon
          [shape]="nextPageIconShape"
          [size]="navIconSize"
          variant="mask"
        />
      </button>
      <button
        class="iconButton"
        [class.iconButtonCollapsed]="firstLastCollapsed"
        type="button"
        [disabled]="disabled || atLastPage"
        aria-label="Last page"
        (click)="onLastPage()"
      >
        <ids-icon
          [shape]="lastPageIconShape"
          [size]="navIconSize"
          variant="mask"
        />
      </button>
    }
  </div>
</nav>

@if (resolvedPerPageDropdownState !== "collapsed") {
  <ul
    #perPageMenu
    class="dropdownMenu dropdownMenuPortaled"
    [class.dropdownMenuAbove]="resolvedPerPageDropdownState === 'expanded-above'"
    [class.dropdownMenuBelow]="resolvedPerPageDropdownState === 'expanded-below'"
    data-ids-pagination-per-page-menu
    [attr.data-placement]="menuPlacement"
    [style.position]="'fixed'"
    [style.top.px]="perPageMenuPos?.top ?? 0"
    [style.left.px]="perPageMenuPos?.left ?? 0"
    [style.width.px]="perPageMenuPos?.width ?? 90"
    role="listbox"
    aria-label="Items per page options"
    (click)="$event.stopPropagation()"
  >
    @for (option of safePageSizeOptions; track option) {
      <li class="dropdownOptionWrap">
        <button
          type="button"
          role="option"
          class="dropdownOption"
          [class.dropdownOptionSelected]="option === safePageSize"
          [attr.aria-selected]="option === safePageSize"
          (click)="selectPageSize(option)"
        >
          {{ option }}
        </button>
      </li>
    }
  </ul>
}

// lib/react/ids/pagination/IdsPagination.tsx
/**
 * IDS Pagination — React implementation generated from design-spec.
 *
 * Path: `lib/react/ids/pagination`
 * Source: `components/ids/pagination/design-spec.md`
 * Theme: `components/ids-theme.css`
 *
 * Anatomy:
 *   PaginationRoot (nav)
 *     ResultsPerPageGroup?  (Show: + PerPageDropdown + per page)
 *     PageNavigationGroup
 *       FirstPageButton + PrevPageButton + PageInput + PageCountText
 *       + NextPageButton + LastPageButton
 *
 * Composition: lib `IdsIcon` for nav glyphs + per-page caret.
 * Page number is always a numeric text input (never a dropdown).
 * No @base-ui-components dependency.
 */

import React, {
  useCallback,
  useEffect,
  useId,
  useLayoutEffect,
  useRef,
  useState,
  type ComponentProps,
  type ReactElement,
} from "react";
import { createPortal } from "react-dom";
import { IdsIcon } from "../icon";
import { IdsTextBox } from "../text-box";
import styles from "./IdsPagination.module.css";

export type IdsPaginationBackground = "gray" | "white" | "none";
export type IdsPaginationResponsiveMode = "auto" | "keep-inline";
export type IdsPaginationCollapseSlot =
  | "results-per-page"
  | "page-input"
  | "first-last-buttons";

export interface IdsPaginationProps
  extends Omit<ComponentProps<"nav">, "children" | "onChange"> {
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
  pageSize?: number;
  pageSizeOptions?: number[];
  onPageSizeChange?: (size: number) => void;
  /** Default `true`. */
  showResultsPerPage?: boolean;
  /** Default `"gray"`. */
  background?: IdsPaginationBackground;
  disabled?: boolean;
  summaryFormatter?: (currentPage: number, totalPages: number) => string;
  /** Default `"auto"`. */
  responsiveMode?: IdsPaginationResponsiveMode;
  /** Default `["results-per-page"]`. */
  collapseOrder?: IdsPaginationCollapseSlot[];
}

const DEFAULT_PAGE_SIZE_OPTIONS = [25, 50, 75, 100] as const;
const DEFAULT_COLLAPSE_ORDER: IdsPaginationCollapseSlot[] = [
  "results-per-page",
];

const BACKGROUNDS = new Set<IdsPaginationBackground>([
  "gray",
  "white",
  "none",
]);
const RESPONSIVE_MODES = new Set<IdsPaginationResponsiveMode>([
  "auto",
  "keep-inline",
]);
const COLLAPSE_SLOTS = new Set<IdsPaginationCollapseSlot>([
  "results-per-page",
  "page-input",
  "first-last-buttons",
]);

type PerPageMenuPlacement = "below" | "above";
type PaginationMenuPos = { top: number; left: number; width: number };

function computePerPageMenuPos(
  trigger: HTMLElement | null,
  menu: HTMLElement | null,
  placement: PerPageMenuPlacement,
): PaginationMenuPos | null {
  if (!trigger) return null;
  const rect = trigger.getBoundingClientRect();
  const width = rect.width;
  const left = rect.left;
  if (placement === "above") {
    const menuHeight = menu?.getBoundingClientRect().height ?? 0;
    return { top: rect.top + 1 - menuHeight, left, width };
  }
  return { top: rect.top + rect.height - 1, left, width };
}

function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

function normalizePageSizeOptions(options: number[] | undefined): number[] {
  if (!options || options.length === 0) {
    return [...DEFAULT_PAGE_SIZE_OPTIONS];
  }
  const uniquePositive = Array.from(
    new Set(options.filter((value) => Number.isFinite(value) && value > 0)),
  );
  return uniquePositive.length > 0
    ? uniquePositive
    : [...DEFAULT_PAGE_SIZE_OPTIONS];
}

function resolveBackground(
  value: IdsPaginationBackground | string | undefined,
): IdsPaginationBackground {
  if (value != null && BACKGROUNDS.has(value as IdsPaginationBackground)) {
    return value as IdsPaginationBackground;
  }
  return "gray";
}

function resolveResponsiveMode(
  value: IdsPaginationResponsiveMode | string | undefined,
): IdsPaginationResponsiveMode {
  if (
    value != null &&
    RESPONSIVE_MODES.has(value as IdsPaginationResponsiveMode)
  ) {
    return value as IdsPaginationResponsiveMode;
  }
  return "auto";
}

function resolveCollapseOrder(
  value: IdsPaginationCollapseSlot[] | undefined,
): IdsPaginationCollapseSlot[] {
  if (!value || value.length === 0) return [...DEFAULT_COLLAPSE_ORDER];
  const filtered = value.filter((slot) => COLLAPSE_SLOTS.has(slot));
  return filtered.length > 0 ? filtered : [...DEFAULT_COLLAPSE_ORDER];
}

function defaultPageCountText(currentPage: number, totalPages: number): string {
  if (totalPages <= 1) return "1 page";
  return `of ${totalPages}`;
}

export function IdsPagination({
  currentPage,
  totalPages,
  onPageChange,
  pageSize,
  pageSizeOptions,
  onPageSizeChange,
  showResultsPerPage = true,
  background: backgroundProp = "gray",
  disabled = false,
  summaryFormatter,
  responsiveMode: responsiveModeProp = "auto",
  collapseOrder: collapseOrderProp,
  className,
  "aria-label": ariaLabel = "Pagination",
  ...rest
}: IdsPaginationProps): ReactElement {
  const menuId = useId();
  const rootRef = useRef<HTMLElement | null>(null);
  const triggerRef = useRef<HTMLButtonElement | null>(null);
  const menuRef = useRef<HTMLUListElement | null>(null);

  const background = resolveBackground(backgroundProp);
  const responsiveMode = resolveResponsiveMode(responsiveModeProp);
  const collapseOrder = resolveCollapseOrder(collapseOrderProp);

  const safeTotalPages = Math.max(1, totalPages);
  const safeCurrentPage = clamp(currentPage, 1, safeTotalPages);
  const safePageSizeOptions = normalizePageSizeOptions(pageSizeOptions);
  const safePageSize =
    pageSize != null && safePageSizeOptions.includes(pageSize)
      ? pageSize
      : safePageSizeOptions[0];

  const [pageInputValue, setPageInputValue] = useState(
    String(safeCurrentPage),
  );
  const [perPageMenuOpen, setPerPageMenuOpen] = useState(false);
  const [menuPlacement, setMenuPlacement] =
    useState<PerPageMenuPlacement>("below");
  const [perPageMenuPos, setPerPageMenuPos] =
    useState<PaginationMenuPos | null>(null);
  const [collapseLevel, setCollapseLevel] = useState(0);

  useEffect(() => {
    setPageInputValue(String(safeCurrentPage));
  }, [safeCurrentPage]);

  const atFirstPage = safeCurrentPage <= 1;
  const atLastPage = safeCurrentPage >= safeTotalPages;
  const isSinglePage = safeTotalPages <= 1;

  const goToPage = useCallback(
    (nextPage: number) => {
      if (disabled) return;
      const clamped = clamp(nextPage, 1, safeTotalPages);
      onPageChange(clamped);
    },
    [disabled, onPageChange, safeTotalPages],
  );

  const commitPageInput = useCallback(() => {
    const parsed = Number.parseInt(pageInputValue, 10);
    if (!Number.isFinite(parsed)) {
      setPageInputValue(String(safeCurrentPage));
      return;
    }
    goToPage(parsed);
  }, [goToPage, pageInputValue, safeCurrentPage]);

  const closePerPageMenu = useCallback(() => {
    setPerPageMenuOpen(false);
    setPerPageMenuPos(null);
  }, []);

  const syncPerPageOverlay = useCallback(() => {
    const trigger = triggerRef.current;
    if (!trigger) {
      setMenuPlacement("below");
      setPerPageMenuPos(null);
      return;
    }
    const rect = trigger.getBoundingClientRect();
    const viewportHeight =
      typeof window !== "undefined" ? window.innerHeight : rect.bottom + 200;
    const spaceBelow = viewportHeight - rect.bottom;
    const spaceAbove = rect.top;
    const estimatedMenuHeight = Math.max(
      menuRef.current?.offsetHeight ?? 0,
      safePageSizeOptions.length * 40,
    );
    const nextPlacement: PerPageMenuPlacement =
      spaceBelow < estimatedMenuHeight && spaceAbove > spaceBelow
        ? "above"
        : "below";
    setMenuPlacement(nextPlacement);
    setPerPageMenuPos(
      computePerPageMenuPos(trigger, menuRef.current, nextPlacement),
    );
  }, [safePageSizeOptions.length]);

  const togglePerPageMenu = useCallback(() => {
    if (disabled) return;
    setPerPageMenuOpen((prev) => !prev);
  }, [disabled]);

  useLayoutEffect(() => {
    if (!perPageMenuOpen) {
      setPerPageMenuPos(null);
      return;
    }
    syncPerPageOverlay();
    const frame = requestAnimationFrame(() => {
      syncPerPageOverlay();
    });
    const onReposition = () => {
      syncPerPageOverlay();
    };
    window.addEventListener("resize", onReposition);
    window.addEventListener("scroll", onReposition, true);
    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("resize", onReposition);
      window.removeEventListener("scroll", onReposition, true);
    };
  }, [perPageMenuOpen, syncPerPageOverlay]);

  useEffect(() => {
    if (!perPageMenuOpen) return;
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") {
        closePerPageMenu();
        triggerRef.current?.focus();
      }
    };
    const onPointerDown = (event: MouseEvent) => {
      const target = event.target as Node | null;
      if (!target) return;
      if (triggerRef.current?.contains(target)) return;
      if (menuRef.current?.contains(target)) return;
      closePerPageMenu();
    };
    document.addEventListener("keydown", onKeyDown);
    document.addEventListener("mousedown", onPointerDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      document.removeEventListener("mousedown", onPointerDown);
    };
  }, [closePerPageMenu, perPageMenuOpen]);

  // Responsive: reset collapse on container resize, then progressively apply
  // `collapseOrder` until content fits (spec Layout & Measurements → Responsiveness).
  useLayoutEffect(() => {
    if (responsiveMode !== "auto") {
      setCollapseLevel(0);
      return;
    }
    const root = rootRef.current;
    if (!root || typeof ResizeObserver === "undefined") return;

    const onResize = () => {
      setCollapseLevel(0);
    };
    const ro = new ResizeObserver(onResize);
    ro.observe(root);
    return () => ro.disconnect();
  }, [responsiveMode, collapseOrder, showResultsPerPage, safeTotalPages]);

  useLayoutEffect(() => {
    if (responsiveMode !== "auto") return;
    const root = rootRef.current;
    if (!root) return;
    if (root.scrollWidth <= root.clientWidth + 1) return;
    if (collapseLevel < collapseOrder.length) {
      setCollapseLevel((level) => level + 1);
    }
  }, [
    collapseLevel,
    collapseOrder,
    responsiveMode,
    showResultsPerPage,
    safeTotalPages,
    background,
    pageInputValue,
    safePageSize,
  ]);

  const collapsedSlots = new Set(collapseOrder.slice(0, collapseLevel));
  const resultsCollapsed = collapsedSlots.has("results-per-page");
  const pageInputCollapsed = collapsedSlots.has("page-input");
  const firstLastCollapsed = collapsedSlots.has("first-last-buttons");
  const renderResultsGroup = showResultsPerPage && !resultsCollapsed;

  const countText =
    summaryFormatter?.(safeCurrentPage, safeTotalPages) ??
    defaultPageCountText(safeCurrentPage, safeTotalPages);

  const rootBackgroundClass =
    background === "white"
      ? styles.rootWhite
      : background === "none"
        ? styles.rootNone
        : styles.rootGray;

  return (
    <>
      <nav
        {...rest}
        ref={rootRef}
        aria-label={ariaLabel}
        className={cx(styles.root, rootBackgroundClass, className)}
        data-ids="ids-pagination"
        data-background={background}
        data-responsive-mode={responsiveMode}
      >
        {renderResultsGroup ? (
          <div
            className={styles.resultsGroup}
            data-ids="ids-pagination-results"
          >
            <span className={styles.label}>Show:</span>
            <div className={styles.dropdownWrap}>
              <button
                ref={triggerRef}
                type="button"
                className={styles.dropdownTrigger}
                disabled={disabled}
                aria-haspopup="listbox"
                aria-expanded={perPageMenuOpen}
                aria-controls={perPageMenuOpen ? menuId : undefined}
                aria-label="Items per page"
                onClick={togglePerPageMenu}
              >
                <span>{safePageSize}</span>
                <IdsIcon
                  shape="arrow-drop-tri-caret"
                  className={styles.caretIcon}
                  size={10}
                  color="currentColor"
                  style={{ width: 10, height: 10 }}
                />
              </button>
            </div>
            <span className={styles.label}>per page</span>
          </div>
        ) : null}

        <div className={styles.pageNavGroup} data-ids="ids-pagination-nav">
          {isSinglePage ? (
            <span className={styles.countText}>{countText}</span>
          ) : (
            <>
              <button
                type="button"
                className={cx(
                  styles.iconButton,
                  firstLastCollapsed && styles.iconButtonCollapsed,
                )}
                onClick={() => goToPage(1)}
                disabled={disabled || atFirstPage}
                aria-label="First page"
              >
                <IdsIcon
                  shape="double-chev-left"
                  size={16}
                  color="currentColor"
                  style={{ width: 16, height: 16 }}
                />
              </button>
              <button
                type="button"
                className={styles.iconButton}
                onClick={() => goToPage(safeCurrentPage - 1)}
                disabled={disabled || atFirstPage}
                aria-label="Previous page"
              >
                <IdsIcon
                  shape="chev-left"
                  size={16}
                  color="currentColor"
                  style={{ width: 16, height: 16 }}
                />
              </button>
              <div
                className={cx(
                  styles.pageInput,
                  pageInputCollapsed && styles.pageInputCollapsed,
                )}
                onKeyDown={(event: React.KeyboardEvent<HTMLDivElement>) => {
                  if (event.key === "Enter") {
                    commitPageInput();
                    const input =
                      event.currentTarget.querySelector(
                        '[data-ids="ids-text-box-input"]',
                      ) as HTMLInputElement | null;
                    input?.blur();
                  }
                }}
                onBlurCapture={() => {
                  commitPageInput();
                }}
              >
                <IdsTextBox
                  componentType="text-input"
                  size="small"
                  inputType="text"
                  ariaLabel="Current page"
                  value={pageInputValue}
                  showIcon={false}
                  disabled={disabled}
                  onValueChange={(value) =>
                    setPageInputValue(value.replace(/[^\d]/g, ""))
                  }
                />
              </div>
              <span className={styles.countText}>{countText}</span>
              <button
                type="button"
                className={styles.iconButton}
                onClick={() => goToPage(safeCurrentPage + 1)}
                disabled={disabled || atLastPage}
                aria-label="Next page"
              >
                <IdsIcon
                  shape="chev-right"
                  size={16}
                  color="currentColor"
                  style={{ width: 16, height: 16 }}
                />
              </button>
              <button
                type="button"
                className={cx(
                  styles.iconButton,
                  firstLastCollapsed && styles.iconButtonCollapsed,
                )}
                onClick={() => goToPage(safeTotalPages)}
                disabled={disabled || atLastPage}
                aria-label="Last page"
              >
                <IdsIcon
                  shape="double-chev-right"
                  size={16}
                  color="currentColor"
                  style={{ width: 16, height: 16 }}
                />
              </button>
            </>
          )}
        </div>
      </nav>
      {perPageMenuOpen && typeof document !== "undefined"
        ? createPortal(
            <ul
              ref={menuRef}
              id={menuId}
              className={cx(
                styles.dropdownMenu,
                styles.dropdownMenuPortaled,
                menuPlacement === "above"
                  ? styles.dropdownMenuAbove
                  : styles.dropdownMenuBelow,
              )}
              role="listbox"
              aria-label="Items per page options"
              data-ids-pagination-per-page-menu
              data-placement={menuPlacement}
              style={{
                position: "fixed",
                top: perPageMenuPos?.top ?? 0,
                left: perPageMenuPos?.left ?? 0,
                width: perPageMenuPos?.width ?? 90,
              }}
              onClick={(event) => event.stopPropagation()}
            >
              {safePageSizeOptions.map((option) => {
                const selected = option === safePageSize;
                return (
                  <li key={option} className={styles.dropdownOptionWrap}>
                    <button
                      type="button"
                      role="option"
                      aria-selected={selected}
                      className={cx(
                        styles.dropdownOption,
                        selected && styles.dropdownOptionSelected,
                      )}
                      onClick={() => {
                        onPageSizeChange?.(option);
                        closePerPageMenu();
                      }}
                    >
                      {option}
                    </button>
                  </li>
                );
              })}
            </ul>,
            document.body,
          )
        : null}
    </>
  );
}

IdsPagination.displayName = "IdsPagination";

export default IdsPagination;
