// storybook/src/components/IdsWizard.tsx
import { Dialog as BaseDialog } from "@base-ui-components/react/dialog";
import { isValidElement, type ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { Icon } from "./Icon";
import styles from "./IdsWizard.module.css";

export type IdsWizardMode = "inline" | "modal";
export type IdsWizardSize = "medium" | "large" | "x-large" | "full-screen";
export type IdsWizardStepStatus = "none" | "success" | "warning" | "error";

export interface IdsWizardFooterButtons {
  showCancel?: boolean;
  showPrevious?: boolean;
  primaryLabel?: string;
}

export interface IdsWizardContext {
  currentStepId?: string;
}

export interface IdsWizardStep {
  id: string;
  label: string;
  pageTitle?: string;
  content?: ReactNode;
  status?: IdsWizardStepStatus;
  statusIconSlug?: string | null;
  isVisible?: boolean | ((ctx: IdsWizardContext) => boolean);
  children?: IdsWizardStep[];
  footerButtons?: IdsWizardFooterButtons;
  primaryDisabled?: boolean;
}

export interface IdsWizardEventPayload {
  stepId: string;
  parentStepId?: string;
  stepIndex: number;
  substepIndex?: number;
  stepCode: string;
}

export interface IdsWizardProps {
  mode?: IdsWizardMode;
  size?: IdsWizardSize;
  title: string;
  steps: IdsWizardStep[];
  initialStepId?: string;
  showCloseButton?: boolean;
  isPrimaryEnabled?: boolean | ((ctx: IdsWizardContext) => boolean);
  onCancel?: (event: IdsWizardEventPayload) => void;
  onPrevious?: (event: IdsWizardEventPayload) => void;
  onNext?: (event: IdsWizardEventPayload) => void;
  onFinish?: (event: IdsWizardEventPayload) => void;
  onStepChange?: (event: IdsWizardEventPayload) => void;
  trigger?: ReactNode;
}

interface VisibleNode {
  node: IdsWizardStep;
  parentId?: string;
  topLevelIndex: number;
  childIndex?: number;
}

interface DisplayStep {
  top: VisibleNode;
  children: VisibleNode[];
}

function toStepCode(topLevelIndex: number, childIndex?: number): string {
  if (childIndex == null) return String(topLevelIndex + 1);
  const letter = String.fromCharCode("a".charCodeAt(0) + childIndex);
  return `${topLevelIndex + 1}${letter}`;
}

function resolveVisible(step: IdsWizardStep, ctx: IdsWizardContext): boolean {
  if (typeof step.isVisible === "function") return step.isVisible(ctx);
  if (typeof step.isVisible === "boolean") return step.isVisible;
  return true;
}

function flattenVisible(steps: IdsWizardStep[], ctx: IdsWizardContext): { display: DisplayStep[]; leaves: VisibleNode[] } {
  const display: DisplayStep[] = [];
  const leaves: VisibleNode[] = [];

  steps.forEach((topStep, topIndex) => {
    if (!resolveVisible(topStep, ctx)) return;
    const topNode: VisibleNode = { node: topStep, topLevelIndex: topIndex };
    const rawChildren = topStep.children ?? [];
    const visibleChildren = rawChildren
      .filter((child) => resolveVisible(child, ctx))
      .map((child, childIndex) => ({
        node: child,
        parentId: topStep.id,
        topLevelIndex: topIndex,
        childIndex,
      }));

    display.push({ top: topNode, children: visibleChildren });

    if (visibleChildren.length > 0) {
      leaves.push(...visibleChildren);
    } else {
      leaves.push(topNode);
    }
  });

  return { display, leaves };
}

function payloadFromNode(node: VisibleNode): IdsWizardEventPayload {
  return {
    stepId: node.node.id,
    parentStepId: node.parentId,
    stepIndex: node.topLevelIndex,
    substepIndex: node.childIndex,
    stepCode: toStepCode(node.topLevelIndex, node.childIndex),
  };
}

function consolidatedStatus(step: DisplayStep): IdsWizardStepStatus {
  if (step.children.length === 0) return step.top.node.status ?? "none";
  const statuses = step.children.map((child) => child.node.status ?? "none");
  if (statuses.includes("error")) return "error";
  if (statuses.includes("warning")) return "warning";
  if (statuses.includes("success")) return "success";
  return "none";
}

function statusIcon(status: IdsWizardStepStatus): string | undefined {
  if (status === "success") return "shape-check";
  if (status === "warning") return "status-warn-tri-solid-16";
  if (status === "error") return "status-error-diamond-solid";
  return undefined;
}

function resolveStatusIcon(step: IdsWizardStep, fallbackStatus: IdsWizardStepStatus): string | undefined {
  if (step.statusIconSlug === null) return undefined;
  const explicitSlug = typeof step.statusIconSlug === "string" ? step.statusIconSlug.trim() : "";
  if (explicitSlug) return explicitSlug;
  return statusIcon(fallbackStatus);
}

export function IdsWizard({
  mode = "inline",
  size = "large",
  title,
  steps,
  initialStepId,
  showCloseButton = true,
  isPrimaryEnabled = true,
  onCancel,
  onPrevious,
  onNext,
  onFinish,
  onStepChange,
  trigger,
}: IdsWizardProps) {
  const [currentStepId, setCurrentStepId] = useState<string | undefined>(initialStepId);
  const lastStepChangeKeyRef = useRef<string>("");
  const ctx = useMemo<IdsWizardContext>(() => ({ currentStepId }), [currentStepId]);

  const { display, leaves } = useMemo(() => flattenVisible(steps, ctx), [steps, ctx]);
  const totalTopLevelSteps = display.length;

  useEffect(() => {
    if (leaves.length === 0) {
      setCurrentStepId(undefined);
      return;
    }
    const hasCurrent = currentStepId != null && leaves.some((leaf) => leaf.node.id === currentStepId);
    if (hasCurrent) return;

    const requested = initialStepId && leaves.find((leaf) => leaf.node.id === initialStepId);
    setCurrentStepId(requested?.node.id ?? leaves[0].node.id);
  }, [initialStepId, currentStepId, leaves]);

  const currentLeaf = leaves.find((leaf) => leaf.node.id === currentStepId);
  const currentIndex = currentLeaf ? leaves.findIndex((leaf) => leaf.node.id === currentLeaf.node.id) : -1;
  const isFirstLeaf = currentIndex <= 0;
  const isLastLeaf = currentIndex === leaves.length - 1 && currentIndex >= 0;

  useEffect(() => {
    if (!currentLeaf) return;
    const payload = payloadFromNode(currentLeaf);
    const key = `${payload.stepId}|${payload.stepCode}`;
    if (lastStepChangeKeyRef.current === key) return;
    lastStepChangeKeyRef.current = key;
    onStepChange?.(payload);
  }, [currentLeaf, onStepChange]);

  const resolvedPrimaryEnabled =
    typeof isPrimaryEnabled === "function"
      ? isPrimaryEnabled(ctx)
      : isPrimaryEnabled;
  const primaryEnabled = resolvedPrimaryEnabled && !currentLeaf?.node.primaryDisabled;

  const footerOverrides = currentLeaf?.node.footerButtons;
  const showCancel = footerOverrides?.showCancel ?? true;
  const showPrevious = footerOverrides?.showPrevious ?? true;
  const primaryLabel = footerOverrides?.primaryLabel ?? (isLastLeaf ? "Finish" : "Next");

  const progressLabel =
    currentLeaf && totalTopLevelSteps > 0
      ? `Step ${toStepCode(currentLeaf.topLevelIndex, currentLeaf.childIndex)} of ${totalTopLevelSteps}`
      : `Step 0 of ${totalTopLevelSteps}`;

  const goToLeaf = (leaf: VisibleNode | undefined) => {
    if (!leaf) return;
    setCurrentStepId(leaf.node.id);
  };

  const shell = (
    <section className={[styles.root, styles[size], mode === "modal" ? styles.modalRoot : ""].join(" ")}>
      <header className={styles.header}>
        <h2 className={styles.headerTitle}>{title}</h2>
        {showCloseButton ? (
          <button
            type="button"
            className={styles.closeButton}
            aria-label="Close wizard"
            onClick={() => {
              if (currentLeaf) onCancel?.(payloadFromNode(currentLeaf));
            }}
          >
            <Icon shapeName="ctrl-close-16" className={styles.closeIcon} />
          </button>
        ) : null}
      </header>

      <div className={styles.body}>
        <nav className={styles.stepsPane} aria-label="Wizard steps">
          {display.map((group) => {
            const groupHasChildren = group.children.length > 0;
            const groupStatus = consolidatedStatus(group);
            const groupIcon = resolveStatusIcon(group.top.node, groupStatus);
            const topActive =
              currentLeaf &&
              ((groupHasChildren && currentLeaf.parentId === group.top.node.id) || (!groupHasChildren && currentLeaf.node.id === group.top.node.id));

            return (
              <div key={group.top.node.id}>
                <button
                  type="button"
                  className={[styles.stepItem, topActive ? styles.stepItemActive : ""].filter(Boolean).join(" ")}
                  onClick={() => goToLeaf(groupHasChildren ? group.children[0] : group.top)}
                  aria-current={topActive ? "step" : undefined}
                >
                  <span className={styles.stepLabel}>{group.top.node.label}</span>
                  {groupIcon ? <Icon shapeName={groupIcon} className={[styles.statusIcon, styles[`status${groupStatus}`]].join(" ")} /> : null}
                </button>

                {group.children.length > 0 ? (
                  <div className={styles.substepList}>
                    {group.children.map((child) => {
                      const active = currentLeaf?.node.id === child.node.id;
                      const icon = resolveStatusIcon(child.node, child.node.status ?? "none");
                      return (
                        <button
                          key={child.node.id}
                          type="button"
                          className={[styles.substepItem, active ? styles.substepItemActive : ""].filter(Boolean).join(" ")}
                          onClick={() => goToLeaf(child)}
                          aria-current={active ? "step" : undefined}
                        >
                          <span className={styles.stepLabel}>{child.node.label}</span>
                          {icon ? <Icon shapeName={icon} className={[styles.statusIcon, styles[`status${child.node.status ?? "none"}`]].join(" ")} /> : null}
                        </button>
                      );
                    })}
                  </div>
                ) : null}
              </div>
            );
          })}
        </nav>

        <section className={styles.contentPane}>
          <div className={styles.pageTitleWrap}>
            <h3 className={styles.pageTitle}>{currentLeaf?.node.pageTitle ?? currentLeaf?.node.label ?? "Page"}</h3>
          </div>
          <div className={styles.pageContent}>
            <div className={styles.pageContentScroll}>
              {currentLeaf?.node.content ?? (
                <p className={styles.fallbackText}>No page content is defined for this step.</p>
              )}
            </div>
          </div>
          <footer className={styles.footer}>
            <span className={styles.progress}>{progressLabel}</span>
            <div className={styles.footerActions}>
              {showCancel ? (
                <button
                  type="button"
                  className={styles.secondaryButton}
                  onClick={() => {
                    if (currentLeaf) onCancel?.(payloadFromNode(currentLeaf));
                  }}
                >
                  Cancel
                </button>
              ) : null}
              {showPrevious ? (
                <button
                  type="button"
                  className={styles.secondaryButton}
                  disabled={isFirstLeaf || !currentLeaf}
                  onClick={() => {
                    const prev = currentIndex > 0 ? leaves[currentIndex - 1] : undefined;
                    goToLeaf(prev);
                    if (prev) onPrevious?.(payloadFromNode(prev));
                  }}
                >
                  Previous
                </button>
              ) : null}
              <button
                type="button"
                className={styles.primaryButton}
                disabled={!primaryEnabled || !currentLeaf}
                onClick={() => {
                  if (!currentLeaf) return;
                  if (isLastLeaf || primaryLabel.toLowerCase() === "finish") {
                    onFinish?.(payloadFromNode(currentLeaf));
                    return;
                  }
                  const next = currentIndex >= 0 ? leaves[currentIndex + 1] : undefined;
                  goToLeaf(next);
                  if (next) onNext?.(payloadFromNode(next));
                }}
              >
                {primaryLabel}
              </button>
            </div>
          </footer>
        </section>
      </div>
    </section>
  );

  if (mode === "modal") {
    const triggerElement = trigger ?? <button type="button">Open Wizard</button>;
    const triggerRender = isValidElement(triggerElement) ? triggerElement : undefined;
    return (
      <BaseDialog.Root>
        {triggerRender ? (
          <BaseDialog.Trigger className={styles.modalTriggerReset} render={triggerRender} />
        ) : (
          <BaseDialog.Trigger className={styles.modalTriggerReset}>{triggerElement}</BaseDialog.Trigger>
        )}
        <BaseDialog.Portal>
          <BaseDialog.Backdrop className={styles.backdrop} />
          <BaseDialog.Popup className={styles.modalPopup}>{shell}</BaseDialog.Popup>
        </BaseDialog.Portal>
      </BaseDialog.Root>
    );
  }

  return shell;
}

// lib/angular/ids/wizard/ids-wizard.component.ts
import {
  AfterContentInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ContentChild,
  EventEmitter,
  Input,
  OnChanges,
  OnInit,
  Output,
  SimpleChanges,
  TemplateRef,
  ViewEncapsulation,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { WIZARD_DEFAULTS } from "@component-contracts/ids/wizard.contract";
import { IdsIconComponent } from "../icon/ids-icon.component";
import { cx } from "../../shared/utils/cx";
import { IDS_WIZARD_CONTEXT, type IdsWizardRuntimeContext } from "./ids-wizard-context";
import {
  IdsWizardBodyComponent,
  IdsWizardCancelButtonComponent,
  IdsWizardCloseActionComponent,
  IdsWizardContentPaneComponent,
  IdsWizardFooterActionsComponent,
  IdsWizardFooterComponent,
  IdsWizardHeaderComponent,
  IdsWizardHeaderTitleComponent,
  IdsWizardPageContentComponent,
  IdsWizardPageTitleComponent,
  IdsWizardPreviousButtonComponent,
  IdsWizardPrimaryButtonComponent,
  IdsWizardProgressLabelComponent,
  IdsWizardStepItemComponent,
  IdsWizardStepLabelComponent,
  IdsWizardStepStatusIndicatorComponent,
  IdsWizardStepsPaneComponent,
  IdsWizardSubstepItemComponent,
  IdsWizardSubstepListComponent,
} from "./ids-wizard-slots.component";
import type {
  IdsWizardContext,
  IdsWizardDisplayStep,
  IdsWizardEventPayload,
  IdsWizardMode,
  IdsWizardSize,
  IdsWizardStepContent,
  IdsWizardStepInput,
  IdsWizardStepStatus,
  IdsWizardVisibleNode,
} from "./ids-wizard.types";
import {
  consolidatedStatus,
  flattenVisible,
  payloadFromNode,
  resolveMode,
  resolveSize,
  resolveStatusIcon,
  toStepCode,
} from "./ids-wizard.utils";

let wizardInstanceCounter = 0;

@Component({
  selector: "ids-wizard",
  standalone: true,
  imports: [
    CommonModule,
    IdsWizardHeaderComponent,
    IdsWizardHeaderTitleComponent,
    IdsWizardCloseActionComponent,
    IdsWizardBodyComponent,
    IdsWizardStepsPaneComponent,
    IdsWizardStepItemComponent,
    IdsWizardStepLabelComponent,
    IdsWizardStepStatusIndicatorComponent,
    IdsWizardSubstepListComponent,
    IdsWizardSubstepItemComponent,
    IdsWizardContentPaneComponent,
    IdsWizardPageTitleComponent,
    IdsWizardPageContentComponent,
    IdsWizardFooterComponent,
    IdsWizardProgressLabelComponent,
    IdsWizardFooterActionsComponent,
    IdsWizardCancelButtonComponent,
    IdsWizardPreviousButtonComponent,
    IdsWizardPrimaryButtonComponent,
    IdsIconComponent,
  ],
  templateUrl: "./ids-wizard.component.html",
  styleUrl: "./ids-wizard.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  encapsulation: ViewEncapsulation.None,
  providers: [{ provide: IDS_WIZARD_CONTEXT, useExisting: IdsWizardComponent }],
})
export class IdsWizardComponent implements IdsWizardRuntimeContext, OnInit, AfterContentInit, OnChanges {
  @ContentChild(IdsWizardHeaderComponent) headerSlot?: IdsWizardHeaderComponent;
  @ContentChild(IdsWizardBodyComponent) bodySlot?: IdsWizardBodyComponent;

  @Input() mode: IdsWizardMode = WIZARD_DEFAULTS.mode;
  @Input() size: IdsWizardSize = WIZARD_DEFAULTS.size;
  @Input() title = WIZARD_DEFAULTS.title;
  @Input() steps: IdsWizardStepInput[] = [];
  @Input() initialStepId?: string;
  @Input() showCloseButton = WIZARD_DEFAULTS.showCloseButton;
  @Input() isPrimaryEnabled: boolean | ((ctx: IdsWizardContext) => boolean) = true;
  @Input() className?: string;
  @Input() id?: string;

  @Output() readonly onCancel = new EventEmitter<IdsWizardEventPayload>();
  @Output() readonly onPrevious = new EventEmitter<IdsWizardEventPayload>();
  @Output() readonly onNext = new EventEmitter<IdsWizardEventPayload>();
  @Output() readonly onFinish = new EventEmitter<IdsWizardEventPayload>();
  @Output() readonly onStepChange = new EventEmitter<IdsWizardEventPayload>();

  readonly generatedId = `ids-wizard-${++wizardInstanceCounter}`;

  currentStepId?: string;
  display: IdsWizardDisplayStep[] = [];
  leaves: IdsWizardVisibleNode[] = [];
  currentLeaf?: IdsWizardVisibleNode;
  hasCompoundSlots = false;
  private lastStepChangeKey = "";

  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnInit(): void {
    this.syncCurrentLeaf();
  }

  ngAfterContentInit(): void {
    this.hasCompoundSlots = Boolean(this.headerSlot || this.bodySlot);
    this.syncCurrentLeaf();
    this.cdr.markForCheck();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["steps"] || changes["initialStepId"] || changes["mode"] || changes["size"]) {
      this.syncCurrentLeaf();
    }
  }

  get rootId(): string {
    return this.id || this.generatedId;
  }

  get titleId(): string {
    return `${this.rootId}-title`;
  }

  get resolvedMode(): IdsWizardMode {
    return resolveMode(this.mode);
  }

  get resolvedSize(): IdsWizardSize {
    return resolveSize(this.size);
  }

  get wizardCtx(): IdsWizardContext {
    return { currentStepId: this.currentStepId };
  }

  get currentIndex(): number {
    if (!this.currentLeaf) {
      return -1;
    }
    return this.leaves.findIndex((leaf) => leaf.node.id === this.currentLeaf?.node.id);
  }

  get isFirstLeaf(): boolean {
    return this.currentIndex <= 0;
  }

  get isLastLeaf(): boolean {
    return this.currentIndex === this.leaves.length - 1 && this.currentIndex >= 0;
  }

  get currentPayload(): IdsWizardEventPayload | null {
    return this.currentLeaf ? payloadFromNode(this.currentLeaf) : null;
  }

  get primaryEnabled(): boolean {
    const resolved =
      typeof this.isPrimaryEnabled === "function"
        ? this.isPrimaryEnabled(this.wizardCtx)
        : this.isPrimaryEnabled;
    return Boolean(resolved && this.currentLeaf);
  }

  get footerOverrides() {
    return this.currentLeaf?.node.footerButtons;
  }

  get showCancel(): boolean {
    return this.footerOverrides?.showCancel ?? true;
  }

  get showPrevious(): boolean {
    return this.footerOverrides?.showPrevious ?? true;
  }

  get primaryLabel(): string {
    return this.footerOverrides?.primaryLabel ?? (this.isLastLeaf ? "Finish" : "Next");
  }

  get progressLabel(): string {
    const total = this.display.length;
    if (this.currentLeaf && total > 0) {
      return `Step ${toStepCode(this.currentLeaf.topLevelIndex, this.currentLeaf.childIndex)} of ${total}`;
    }
    return `Step 0 of ${total}`;
  }

  get showClose(): boolean {
    return this.resolvedMode === "modal" ? true : this.showCloseButton;
  }

  get pageTitle(): string {
    return this.currentLeaf?.node.pageTitle ?? this.currentLeaf?.node.label ?? "Page";
  }

  get pageContent(): IdsWizardStepContent | undefined {
    return this.currentLeaf?.node.content;
  }

  get wizardClass(): string {
    return cx(
      "ids-wizard",
      `ids-wizard--${this.resolvedSize}`,
      this.resolvedMode === "modal" ? "ids-wizard--modal" : "",
      this.className,
    );
  }

  isTemplateRef(value: IdsWizardStepContent | undefined): value is TemplateRef<unknown> {
    return value instanceof TemplateRef;
  }

  groupStatus(group: IdsWizardDisplayStep): IdsWizardStepStatus {
    return consolidatedStatus(group);
  }

  groupIcon(group: IdsWizardDisplayStep): string | undefined {
    return resolveStatusIcon(group.top.node, this.groupStatus(group));
  }

  groupLeafStatus(group: IdsWizardDisplayStep): IdsWizardStepStatus {
    return group.children.length > 0
      ? this.groupStatus(group)
      : (group.top.node.status ?? "none");
  }

  isGroupActive(group: IdsWizardDisplayStep): boolean {
    if (!this.currentLeaf) {
      return false;
    }
    const groupHasChildren = group.children.length > 0;
    return (
      (groupHasChildren && this.currentLeaf.parentId === group.top.node.id) ||
      (!groupHasChildren && this.currentLeaf.node.id === group.top.node.id)
    );
  }

  isChildActive(child: IdsWizardVisibleNode): boolean {
    return this.currentLeaf?.node.id === child.node.id;
  }

  childIcon(child: IdsWizardVisibleNode): string | undefined {
    return resolveStatusIcon(child.node, child.node.status ?? "none");
  }

  onGroupSelect(group: IdsWizardDisplayStep): void {
    const groupHasChildren = group.children.length > 0;
    this.goToLeaf(groupHasChildren ? group.children[0] : group.top);
  }

  goToLeaf(leaf: IdsWizardVisibleNode | undefined): void {
    if (!leaf) {
      return;
    }
    if (leaf.node.id === this.currentStepId) {
      return;
    }
    this.currentStepId = leaf.node.id;
    this.currentLeaf = leaf;
    this.notifyStepChange(leaf);
    this.cdr.markForCheck();
  }

  cancel(): void {
    if (this.currentPayload) {
      this.onCancel.emit(this.currentPayload);
    }
  }

  goPrevious(): void {
    if (this.currentIndex <= 0) {
      return;
    }
    const prev = this.leaves[this.currentIndex - 1];
    this.goToLeaf(prev);
    if (prev) {
      this.onPrevious.emit(payloadFromNode(prev));
    }
  }

  goNextOrFinish(): void {
    if (!this.currentLeaf || !this.currentPayload) {
      return;
    }
    const label = String(this.primaryLabel).toLowerCase();
    if (this.isLastLeaf || label === "finish") {
      this.onFinish.emit(this.currentPayload);
      return;
    }
    const next = this.leaves[this.currentIndex + 1];
    this.goToLeaf(next);
    if (next) {
      this.onNext.emit(payloadFromNode(next));
    }
  }

  private notifyStepChange(leaf: IdsWizardVisibleNode): void {
    const payload = payloadFromNode(leaf);
    const key = `${payload.stepId}|${payload.stepCode}`;
    if (this.lastStepChangeKey === key) {
      return;
    }
    this.lastStepChangeKey = key;
    this.onStepChange.emit(payload);
  }

  private syncCurrentLeaf(): void {
    const { display, leaves } = flattenVisible(this.steps ?? [], this.wizardCtx);
    this.display = display;
    this.leaves = leaves;

    if (leaves.length === 0) {
      this.currentStepId = undefined;
      this.currentLeaf = undefined;
      return;
    }

    const hasCurrent =
      this.currentStepId != null && leaves.some((leaf) => leaf.node.id === this.currentStepId);
    if (hasCurrent) {
      this.currentLeaf = leaves.find((leaf) => leaf.node.id === this.currentStepId);
      return;
    }

    const requested = this.initialStepId
      ? leaves.find((leaf) => leaf.node.id === this.initialStepId)
      : undefined;
    const nextLeaf = requested ?? leaves[0];
    this.currentStepId = nextLeaf.node.id;
    this.currentLeaf = nextLeaf;
    this.notifyStepChange(nextLeaf);
  }
}

@if (resolvedMode === "modal") {
  <div class="ids-wizard-overlay">
    <ng-container *ngTemplateOutlet="shell" />
  </div>
} @else {
  <ng-container *ngTemplateOutlet="shell" />
}

<ng-template #shell>
  <section
    [id]="rootId"
    [class]="wizardClass"
    [attr.role]="resolvedMode === 'modal' ? 'dialog' : 'region'"
    [attr.aria-modal]="resolvedMode === 'modal' ? 'true' : null"
    [attr.aria-labelledby]="titleId"
  >
    @if (hasCompoundSlots) {
      <ng-content />
    } @else {
      <ids-wizard-header>
        <ids-wizard-header-title>{{ title }}</ids-wizard-header-title>
        @if (showClose) {
          <ids-wizard-close-action />
        }
      </ids-wizard-header>

      <ids-wizard-body>
        <ids-wizard-steps-pane>
          @for (group of display; track group.top.node.id) {
            <div>
              <ids-wizard-step-item
                [active]="isGroupActive(group)"
                [status]="groupLeafStatus(group)"
                [hasChildren]="group.children.length > 0"
                (click)="onGroupSelect(group)"
              >
                @if (group.children.length > 0) {
                  <ids-icon
                    className="ids-wizard-step-expand-icon"
                    shapeName="chev-up-thick"
                    [size]="12"
                  />
                }
                <ids-wizard-step-label>{{ group.top.node.label }}</ids-wizard-step-label>
                <ids-wizard-step-status-indicator
                  [status]="groupLeafStatus(group)"
                  [shape]="groupIcon(group)"
                  align="end"
                />
              </ids-wizard-step-item>

              @if (group.children.length > 0) {
                <ids-wizard-substep-list>
                  @for (child of group.children; track child.node.id) {
                    <ids-wizard-substep-item
                      [active]="isChildActive(child)"
                      [status]="child.node.status ?? 'none'"
                      (click)="goToLeaf(child)"
                    >
                      <ids-wizard-step-label>{{ child.node.label }}</ids-wizard-step-label>
                      <ids-wizard-step-status-indicator
                        [status]="child.node.status ?? 'none'"
                        [shape]="childIcon(child)"
                        align="after-label"
                      />
                    </ids-wizard-substep-item>
                  }
                </ids-wizard-substep-list>
              }
            </div>
          }
        </ids-wizard-steps-pane>

        <ids-wizard-content-pane>
          <ids-wizard-page-title>{{ pageTitle }}</ids-wizard-page-title>
          <ids-wizard-page-content>
            @if (isTemplateRef(pageContent)) {
              <ng-container *ngTemplateOutlet="pageContent" />
            } @else if (pageContent) {
              {{ pageContent }}
            } @else {
              <p class="ids-wizard-page-content-fallback">
                No page content is defined for this step.
              </p>
            }
          </ids-wizard-page-content>
          <ids-wizard-footer>
            <ids-wizard-progress-label />
            <ids-wizard-footer-actions>
              @if (showCancel) {
                <ids-wizard-cancel-button />
              }
              @if (showPrevious) {
                <ids-wizard-previous-button />
              }
              <ids-wizard-primary-button />
            </ids-wizard-footer-actions>
          </ids-wizard-footer>
        </ids-wizard-content-pane>
      </ids-wizard-body>
    }
  </section>
</ng-template>
