// storybook/src/components/IdsTimePicker.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Button } from "./Button";
import { Icon } from "./Icon";
import styles from "./IdsTimePicker.module.css";

export interface IdsTimePickerProps {
  value?: string | null;
  onChange?: (value: string | null) => void;
  size?: "large" | "small";
  placeholder?: string;
  label?: string;
  required?: boolean;
  formatHint?: string;
  clockType?: "12h" | "24h";
  showSeconds?: boolean;
  disabled?: boolean;
  error?: boolean;
  errorMessage?: string;
  forceOpen?: boolean;
}

type Period = "AM" | "PM";

function pad2(n: number) {
  return String(n).padStart(2, "0");
}

function parseTime12(value: string): { hour: number; minute: number; second: number; period: Period } | null {
  const m = value.trim().match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?\s*(AM|PM)$/i);
  if (!m) return null;
  const hour = Number(m[1]);
  const minute = Number(m[2]);
  const second = m[3] ? Number(m[3]) : 0;
  const period = m[4].toUpperCase() as Period;
  if (hour < 1 || hour > 12 || minute > 59 || second > 59) return null;
  return { hour, minute, second, period };
}

function parseTime24(value: string): { hour: number; minute: number; second: number } | null {
  const m = value.trim().match(/^(\d{1,2}):(\d{2})(?::(\d{2}))?$/);
  if (!m) return null;
  const hour = Number(m[1]);
  const minute = Number(m[2]);
  const second = m[3] ? Number(m[3]) : 0;
  if (hour > 23 || minute > 59 || second > 59) return null;
  return { hour, minute, second };
}

function formatTime12(hour: number, minute: number, second: number, period: Period, showSeconds: boolean) {
  const base = `${hour}:${pad2(minute)}`;
  const withSec = showSeconds ? `${base}:${pad2(second)}` : base;
  return `${withSec} ${period}`;
}

function formatTime24(hour: number, minute: number, second: number, showSeconds: boolean) {
  const base = `${pad2(hour)}:${pad2(minute)}`;
  return showSeconds ? `${base}:${pad2(second)}` : base;
}

function TimeColumn({
  label,
  display,
  onUp,
  onDown,
  disabled,
}: {
  label: string;
  display: string;
  onUp: () => void;
  onDown: () => void;
  disabled?: boolean;
}) {
  return (
    <div className={styles.timeColumn} role="group" aria-label={label}>
      <button type="button" className={`${styles.arrowBtn} ${styles.arrowUp}`} onClick={onUp} disabled={disabled} aria-label={`Increase ${label}`}>
        <Icon shapeName="arrow-tri-down-solid" color="var(--color-icon-gray-neutral-base)" style={{ width: 10, height: 10 }} />
      </button>
      <div className={styles.valueCell} aria-live="polite">
        {display}
      </div>
      <button type="button" className={styles.arrowBtn} onClick={onDown} disabled={disabled} aria-label={`Decrease ${label}`}>
        <Icon shapeName="arrow-tri-down-solid" color="var(--color-icon-gray-neutral-base)" style={{ width: 10, height: 10 }} />
      </button>
    </div>
  );
}

export function IdsTimePicker({
  value = null,
  onChange,
  size = "large",
  placeholder = "HH:MM AM/PM",
  label,
  required = false,
  formatHint = "HH:MM AM/PM",
  clockType = "12h",
  showSeconds = false,
  disabled = false,
  error = false,
  errorMessage,
  forceOpen,
}: IdsTimePickerProps) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [mouseActivated, setMouseActivated] = useState(false);
  const [open, setOpen] = useState(forceOpen ?? false);
  const [inputText, setInputText] = useState(value ?? "");

  const defaults12 = { hour: 9, minute: 30, second: 0, period: "PM" as Period };
  const defaults24 = { hour: 13, minute: 30, second: 0 };

  const [hour12, setHour12] = useState(defaults12.hour);
  const [minute, setMinute] = useState(defaults12.minute);
  const [second, setSecond] = useState(0);
  const [period, setPeriod] = useState<Period>(defaults12.period);
  const [hour24, setHour24] = useState(defaults24.hour);

  useEffect(() => {
    if (value !== undefined && value !== null) {
      setInputText(value);
      if (clockType === "12h") {
        const p = parseTime12(value);
        if (p) {
          setHour12(p.hour);
          setMinute(p.minute);
          setSecond(p.second);
          setPeriod(p.period);
        }
      } else {
        const p = parseTime24(value);
        if (p) {
          setHour24(p.hour);
          setMinute(p.minute);
          setSecond(p.second);
        }
      }
    }
  }, [value, clockType]);

  useEffect(() => {
    if (forceOpen !== undefined) setOpen(forceOpen);
  }, [forceOpen]);

  const formatted = useMemo(() => {
    if (clockType === "12h") return formatTime12(hour12, minute, second, period, showSeconds);
    return formatTime24(hour24, minute, second, showSeconds);
  }, [clockType, hour12, hour24, minute, second, period, showSeconds]);

  const commit = useCallback(
    (text: string) => {
      setInputText(text);
      onChange?.(text || null);
    },
    [onChange],
  );

  const applyFromColumns = useCallback(() => {
    commit(formatted);
  }, [commit, formatted]);

  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (rootRef.current && !rootRef.current.contains(e.target as Node)) {
        setOpen(false);
        applyFromColumns();
      }
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [open, applyFromColumns]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Escape" && open) {
      setOpen(false);
      applyFromColumns();
    }
  };

  const wrap = (n: number, min: number, max: number) => {
    if (n > max) return min;
    if (n < min) return max;
    return n;
  };

  const fieldClasses = [
    styles.fieldContainer,
    size === "large" ? styles.sizeLarge : styles.sizeSmall,
    disabled ? styles.disabled : "",
    error ? styles.error : "",
    open ? styles.open : "",
    mouseActivated ? styles.mouseActivated : "",
  ]
    .filter(Boolean)
    .join(" ");

  const showFormatHint = formatHint !== "" && !error;
  const inputFilled = inputText.trim().length > 0;

  return (
    <div className={styles.root} ref={rootRef} onKeyDown={handleKeyDown}>
      {label && (
        <div className={`${styles.label}${size === "small" ? ` ${styles.labelSmall}` : ""}`}>
          <div className={styles.labelInner}>
            <span className={styles.labelText}>{label}</span>
            {required && <span className={styles.labelRequired}>*</span>}
          </div>
        </div>
      )}
      <div className={styles.fieldGroup}>
        <div className={styles.positionWrapper}>
          <div className={fieldClasses}>
          <input
            type="text"
            className={`${styles.textInput} ${inputFilled ? styles.filled : ""}`}
            placeholder={placeholder}
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            onMouseDown={() => setMouseActivated(true)}
            onBlur={() => {
              setMouseActivated(false);
              if (inputText.trim()) commit(inputText.trim());
            }}
            disabled={disabled}
            aria-label={label || "Time"}
          />
          <Button
            type="button"
            variant="tertiary"
            size={size === "large" ? "lg" : "md"}
            iconOnly
            icon={<Icon shapeName="time-clock-16" style={{ width: 16, height: 16 }} />}
            onMouseDown={() => {
              if (!disabled) {
                window.getSelection()?.removeAllRanges();
              }
            }}
            onClick={() => {
              if (!disabled) {
                setOpen((v) => !v);
              }
            }}
            disabled={disabled}
            aria-label="Open time picker"
            aria-expanded={open}
            className={styles.clockButton}
          />
        </div>

        {open && !disabled && (
          <div
            className={`${styles.timePopup} ${clockType === "24h" && !showSeconds ? styles.widePadding : ""}`}
            role="dialog"
            aria-modal="true"
            aria-label="Choose time"
          >
            {clockType === "12h" ? (
              <>
                <TimeColumn
                  label="Hour"
                  display={String(hour12)}
                  disabled={disabled}
                  onUp={() => setHour12((h) => wrap(h + 1, 1, 12))}
                  onDown={() => setHour12((h) => wrap(h - 1, 1, 12))}
                />
                <TimeColumn
                  label="Minute"
                  display={pad2(minute)}
                  disabled={disabled}
                  onUp={() => setMinute((m) => wrap(m + 1, 0, 59))}
                  onDown={() => setMinute((m) => wrap(m - 1, 0, 59))}
                />
                {showSeconds && (
                  <TimeColumn
                    label="Second"
                    display={pad2(second)}
                    disabled={disabled}
                    onUp={() => setSecond((s) => wrap(s + 1, 0, 59))}
                    onDown={() => setSecond((s) => wrap(s - 1, 0, 59))}
                  />
                )}
                <TimeColumn
                  label="AM or PM"
                  display={period}
                  disabled={disabled}
                  onUp={() => setPeriod((p) => (p === "AM" ? "PM" : "AM"))}
                  onDown={() => setPeriod((p) => (p === "AM" ? "PM" : "AM"))}
                />
              </>
            ) : (
              <>
                <TimeColumn
                  label="Hour"
                  display={String(hour24)}
                  disabled={disabled}
                  onUp={() => setHour24((h) => wrap(h + 1, 0, 23))}
                  onDown={() => setHour24((h) => wrap(h - 1, 0, 23))}
                />
                <TimeColumn
                  label="Minute"
                  display={pad2(minute)}
                  disabled={disabled}
                  onUp={() => setMinute((m) => wrap(m + 1, 0, 59))}
                  onDown={() => setMinute((m) => wrap(m - 1, 0, 59))}
                />
                {showSeconds && (
                  <TimeColumn
                    label="Second"
                    display={pad2(second)}
                    disabled={disabled}
                    onUp={() => setSecond((s) => wrap(s + 1, 0, 59))}
                    onDown={() => setSecond((s) => wrap(s - 1, 0, 59))}
                  />
                )}
              </>
            )}
          </div>
        )}
        </div>

        {error && errorMessage ? (
          <div className={styles.errorMessage} role="alert">
            <Icon shapeName="status-critical-square-solid" variant="img" style={{ width: 16, height: 16 }} />
            <span>{errorMessage}</span>
          </div>
        ) : (
          showFormatHint && <span className={styles.formatHint}>{formatHint}</span>
        )}
      </div>
    </div>
  );
}

// lib/angular/ids/time-picker/ids-time-picker.component.ts
/**
 * IDS Time Picker — Angular port of `lib/react/ids/time-picker`.
 * Source: `components/ids/time-picker/design-spec.md`
 */
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
  ViewChild,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  TIME_PICKER_SPEC_ACCURATE_DEFAULTS,
  type TimePickerClockType,
  type TimePickerSize,
} from "@component-contracts/ids/time-picker.contract";
import { IdsIconComponent } from "../icon/ids-icon.component";
import { cx } from "../../shared/utils/cx";
import {
  formatTime12,
  formatTime24,
  pad2,
  parseTime12,
  parseTime24,
  wrapValue,
  type TimePeriod,
} from "./ids-time-picker.utils";

@Component({
  selector: "ids-time-picker",
  standalone: true,
  imports: [CommonModule, IdsIconComponent],
  templateUrl: "./ids-time-picker.component.html",
  styleUrl: "./ids-time-picker.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsTimePickerComponent implements OnChanges {
  @Input() value: string | null = null;
  @Input() size: TimePickerSize = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.size;
  @Input() placeholder = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.placeholder;
  @Input() label?: string;
  @Input() required = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.required;
  @Input() formatHint: string = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.formatHint;
  @Input() clockType: TimePickerClockType = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.clockType;
  @Input() showSeconds = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.showSeconds;
  @Input() disabled = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.disabled;
  @Input() error = TIME_PICKER_SPEC_ACCURATE_DEFAULTS.error;
  @Input() errorMessage?: string;
  @Input() forceOpen?: boolean;

  @Output() readonly onChange = new EventEmitter<string | null>();

  @ViewChild("rootRef") rootRef?: ElementRef<HTMLElement>;

  mouseActivated = false;
  open = this.forceOpen ?? false;
  inputText = this.value ?? "";
  hour12 = 9;
  minute = 30;
  second = 0;
  period: TimePeriod = "PM";
  hour24 = 13;

  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"] || changes["clockType"]) {
      if (this.value !== undefined && this.value !== null) {
        this.inputText = this.value;
        if (this.clockType === "12h") {
          const parsed = parseTime12(this.value);
          if (parsed) {
            this.hour12 = parsed.hour;
            this.minute = parsed.minute;
            this.second = parsed.second;
            this.period = parsed.period;
          }
        } else {
          const parsed = parseTime24(this.value);
          if (parsed) {
            this.hour24 = parsed.hour;
            this.minute = parsed.minute;
            this.second = parsed.second;
          }
        }
      }
    }
    if (changes["forceOpen"] && this.forceOpen === true) {
      this.open = true;
    }
  }

  get formatted(): string {
    if (this.clockType === "12h") {
      return formatTime12(this.hour12, this.minute, this.second, this.period, this.showSeconds);
    }
    return formatTime24(this.hour24, this.minute, this.second, this.showSeconds);
  }

  get fieldClasses(): string {
    return cx(
      "fieldContainer",
      this.size === "large" ? "sizeLarge" : "sizeSmall",
      this.disabled && "disabled",
      this.error && "error",
      this.open && "open",
      this.mouseActivated && "mouseActivated",
    );
  }

  get showFormatHint(): boolean {
    return this.formatHint !== "" && !this.error;
  }

  get inputFilled(): boolean {
    return this.inputText.trim().length > 0;
  }

  get hourDisplay(): string {
    return this.clockType === "12h" ? String(this.hour12) : String(this.hour24);
  }

  commit(text: string): void {
    this.inputText = text;
    this.onChange.emit(text || null);
  }

  applyFromColumns(): void {
    this.commit(this.formatted);
  }

  handleRootKeyDown(event: KeyboardEvent): void {
    if (event.key === "Escape" && this.open) {
      this.open = false;
      this.applyFromColumns();
    }
  }

  onInput(event: Event): void {
    this.inputText = (event.target as HTMLInputElement).value;
  }

  onInputBlur(): void {
    this.mouseActivated = false;
    if (this.inputText.trim()) this.commit(this.inputText.trim());
  }

  toggleOpen(event?: Event): void {
    event?.stopPropagation();
    if (this.disabled || this.forceOpen === true) return;
    this.open = !this.open;
    this.cdr.markForCheck();
  }

  onClockMouseDown(event: Event): void {
    event.stopPropagation();
    if (!this.disabled) {
      window.getSelection()?.removeAllRanges();
    }
  }

  bumpHour(delta: number): void {
    if (this.clockType === "12h") {
      this.hour12 = wrapValue(this.hour12 + delta, 1, 12);
    } else {
      this.hour24 = wrapValue(this.hour24 + delta, 0, 23);
    }
  }

  bumpMinute(delta: number): void {
    this.minute = wrapValue(this.minute + delta, 0, 59);
  }

  bumpSecond(delta: number): void {
    this.second = wrapValue(this.second + delta, 0, 59);
  }

  togglePeriod(): void {
    this.period = this.period === "AM" ? "PM" : "AM";
  }

  pad2(n: number): string {
    return pad2(n);
  }

  @HostListener("document:mousedown", ["$event"])
  onDocumentMouseDown(event: MouseEvent): void {
    if (!this.open || this.forceOpen === true) return;
    if (this.rootRef?.nativeElement.contains(event.target as Node)) return;
    this.open = false;
    this.applyFromColumns();
    this.cdr.markForCheck();
  }
}

<div class="root" #rootRef (keydown)="handleRootKeyDown($event)">
  @if (label) {
    <div class="label" [class.labelSmall]="size === 'small'">
      <div class="labelInner">
        <span class="labelText">{{ label }}</span>
        @if (required) {
          <span class="labelRequired">*</span>
        }
      </div>
    </div>
  }
  <div class="fieldGroup">
    <div class="positionWrapper">
      <div [class]="fieldClasses">
        <input
          type="text"
          class="textInput"
          [class.filled]="inputFilled"
          [placeholder]="placeholder"
          [value]="inputText"
          [disabled]="disabled"
          [attr.aria-label]="label || 'Time'"
          (input)="onInput($event)"
          (mousedown)="mouseActivated = true"
          (blur)="onInputBlur()"
        />
        <button
          type="button"
          class="clockIconBtn"
          [disabled]="disabled"
          aria-label="Open time picker"
          [attr.aria-expanded]="open"
          (mousedown)="onClockMouseDown($event)"
          (click)="toggleOpen($event)"
        >
          <ids-icon shape="time-clock-16" [size]="16" />
        </button>
      </div>

      @if (open && !disabled) {
        <div
          class="timePopup"
          [class.widePadding]="clockType === '24h' && !showSeconds"
          role="dialog"
          aria-modal="true"
          aria-label="Choose time"
        >
          <div class="timeColumn" role="group" aria-label="Hour">
            <button
              type="button"
              class="arrowBtn arrowUp"
              [disabled]="disabled"
              aria-label="Increase Hour"
              (click)="bumpHour(1)"
            >
              <ids-icon
                shape="arrow-tri-down-solid"
                color="var(--color-icon-gray-neutral-base)"
                [size]="10"
              />
            </button>
            <div class="valueCell" aria-live="polite">{{ hourDisplay }}</div>
            <button
              type="button"
              class="arrowBtn"
              [disabled]="disabled"
              aria-label="Decrease Hour"
              (click)="bumpHour(-1)"
            >
              <ids-icon
                shape="arrow-tri-down-solid"
                color="var(--color-icon-gray-neutral-base)"
                [size]="10"
              />
            </button>
          </div>
          <div class="timeColumn" role="group" aria-label="Minute">
            <button
              type="button"
              class="arrowBtn arrowUp"
              [disabled]="disabled"
              aria-label="Increase Minute"
              (click)="bumpMinute(1)"
            >
              <ids-icon
                shape="arrow-tri-down-solid"
                color="var(--color-icon-gray-neutral-base)"
                [size]="10"
              />
            </button>
            <div class="valueCell" aria-live="polite">{{ pad2(minute) }}</div>
            <button
              type="button"
              class="arrowBtn"
              [disabled]="disabled"
              aria-label="Decrease Minute"
              (click)="bumpMinute(-1)"
            >
              <ids-icon
                shape="arrow-tri-down-solid"
                color="var(--color-icon-gray-neutral-base)"
                [size]="10"
              />
            </button>
          </div>
          @if (showSeconds) {
            <div class="timeColumn" role="group" aria-label="Second">
              <button
                type="button"
                class="arrowBtn arrowUp"
                [disabled]="disabled"
                aria-label="Increase Second"
                (click)="bumpSecond(1)"
              >
                <ids-icon
                  shape="arrow-tri-down-solid"
                  color="var(--color-icon-gray-neutral-base)"
                  [size]="10"
                />
              </button>
              <div class="valueCell" aria-live="polite">{{ pad2(second) }}</div>
              <button
                type="button"
                class="arrowBtn"
                [disabled]="disabled"
                aria-label="Decrease Second"
                (click)="bumpSecond(-1)"
              >
                <ids-icon
                  shape="arrow-tri-down-solid"
                  color="var(--color-icon-gray-neutral-base)"
                  [size]="10"
                />
              </button>
            </div>
          }
          @if (clockType === "12h") {
            <div class="timeColumn" role="group" aria-label="AM or PM">
              <button
                type="button"
                class="arrowBtn arrowUp"
                [disabled]="disabled"
                aria-label="Increase AM or PM"
                (click)="togglePeriod()"
              >
                <ids-icon
                  shape="arrow-tri-down-solid"
                  color="var(--color-icon-gray-neutral-base)"
                  [size]="10"
                />
              </button>
              <div class="valueCell" aria-live="polite">{{ period }}</div>
              <button
                type="button"
                class="arrowBtn"
                [disabled]="disabled"
                aria-label="Decrease AM or PM"
                (click)="togglePeriod()"
              >
                <ids-icon
                  shape="arrow-tri-down-solid"
                  color="var(--color-icon-gray-neutral-base)"
                  [size]="10"
                />
              </button>
            </div>
          }
        </div>
      }
    </div>

    @if (error && errorMessage) {
      <div class="errorMessage" role="alert">
        <ids-icon shape="status-critical-square-solid" variant="img" [size]="16" />
        <span>{{ errorMessage }}</span>
      </div>
    } @else if (showFormatHint) {
      <span class="formatHint">{{ formatHint }}</span>
    }
  </div>
</div>
