// lib/angular/ids/dropdown/ids-dropdown-trigger-shell.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";
import { IdsIconComponent } from "../icon/ids-icon.component";
import type { IdsDropdownSize } from "./ids-dropdown.types";

@Component({
  selector: "ids-dropdown-trigger-shell",
  standalone: true,
  imports: [IdsIconComponent],
  templateUrl: "./ids-dropdown-trigger-shell.component.html",
  styleUrl: "./ids-dropdown-trigger-shell.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[attr.data-popup-open]": "null",
  },
})
export class IdsDropdownTriggerShellComponent {
  @Input() size: IdsDropdownSize = "large";
  @Input() disabled = false;
  @Input() error = false;
  /** Demo-only: simulates Figma hover border. */
  @Input() hover = false;
  /** Demo-only: keyboard focus ring. */
  @Input() focusVisible = false;
}

<div
  class="field"
  [attr.data-size]="size === 'small' ? 'small' : null"
  [attr.data-disabled]="disabled || null"
  [attr.data-error]="error || null"
  [attr.data-hover]="hover || null"
  [attr.data-focus]="focusVisible || null"
>
  <div class="main">
    <ng-content />
  </div>
  <span class="caret-wrap" aria-hidden="true">
    <ids-icon shapeName="arrow-drop-tri-caret" [size]="10" />
  </span>
</div>

// storybook/src/components/IdsDropdownTriggerShell.tsx
import type { ReactNode } from "react";
import { Icon } from "./Icon";
import styles from "./IdsDropdownTriggerShell.module.css";

export type IdsDropdownTriggerSize = "small" | "large";

export interface IdsDropdownTriggerShellProps {
  size?: IdsDropdownTriggerSize;
  disabled?: boolean;
  error?: boolean;
  /** Demo-only: simulates Figma hover border (`var(--color-border-strong)`). */
  hover?: boolean;
  /** Demo-only: keyboard focus ring (`outline-offset: 5px`). */
  focusVisible?: boolean;
  left: ReactNode;
}

export function IdsDropdownTriggerShell({
  size = "large",
  disabled = false,
  error = false,
  hover = false,
  focusVisible = false,
  left,
}: IdsDropdownTriggerShellProps) {
  return (
    <div
      className={styles.field}
      data-size={size === "small" ? "small" : undefined}
      data-disabled={disabled || undefined}
      data-error={error || undefined}
      data-hover={hover || undefined}
      data-focus={focusVisible || undefined}
    >
      <div className={styles.main}>{left}</div>
      <span className={styles.caretWrap} aria-hidden>
        <Icon shapeName="arrow-drop-tri-caret" style={{ width: 10, height: 10 }} />
      </span>
    </div>
  );
}
