// storybook-angular/src/components/ids-pagination/ids-pagination.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  OnChanges,
  OnDestroy,
  Output,
  ViewChild,
} from "@angular/core";
import { NgClass } from "@angular/common";
import {
  PAGINATION_SPEC_ACCURATE_DEFAULTS,
  type IdsPaginationBackground,
  type IdsPaginationDropdownState,
} from "@component-contracts/ids/pagination.contract";
import { IdsIconComponent } from "../ids-icon/ids-icon.component";

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

function normalizePositiveOptions(options: number[]): number[] {
  const uniquePositive = Array.from(
    new Set(options.filter((value) => Number.isFinite(value) && value > 0)),
  );
  return uniquePositive.length > 0 ? uniquePositive : [25, 50, 75, 100];
}

type PaginationMenuPos = { top: number; left: number; width: number };

@Component({
  selector: "ids-pagination",
  standalone: true,
  imports: [NgClass, IdsIconComponent],
  templateUrl: "./ids-pagination.component.html",
  styleUrl: "./ids-pagination.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsPaginationComponent implements OnChanges, OnDestroy {
  readonly navIconSize = 16;
  readonly caretIconSize = 10;

  @ViewChild("perPageTrigger") perPageTrigger?: ElementRef<HTMLButtonElement>;
  @ViewChild("perPageMenuLayer") perPageMenuLayer?: ElementRef<HTMLElement>;
  @ViewChild("pageOffsetTrigger") pageOffsetTrigger?: ElementRef<HTMLButtonElement>;
  @ViewChild("pageOffsetMenuLayer") pageOffsetMenuLayer?: ElementRef<HTMLElement>;

  @Input() currentPage = PAGINATION_SPEC_ACCURATE_DEFAULTS.currentPage;
  @Input() totalPages = PAGINATION_SPEC_ACCURATE_DEFAULTS.totalPages;
  @Input() pageSize = PAGINATION_SPEC_ACCURATE_DEFAULTS.pageSize;
  @Input() pageSizeOptions: number[] = [
    ...PAGINATION_SPEC_ACCURATE_DEFAULTS.pageSizeOptions,
  ];
  @Input() pageOffsetOptions: number[] | null = null;
  @Input() showPerPage = PAGINATION_SPEC_ACCURATE_DEFAULTS.showPerPage;
  @Input() showFirstLast = PAGINATION_SPEC_ACCURATE_DEFAULTS.showFirstLast;
  @Input() showPageOffset = PAGINATION_SPEC_ACCURATE_DEFAULTS.showPageOffset;
  @Input() dropdownState: IdsPaginationDropdownState =
    PAGINATION_SPEC_ACCURATE_DEFAULTS.dropdownState;
  @Input() pageOffsetDropdownState: IdsPaginationDropdownState =
    PAGINATION_SPEC_ACCURATE_DEFAULTS.pageOffsetDropdownState;
  @Input() background: IdsPaginationBackground =
    PAGINATION_SPEC_ACCURATE_DEFAULTS.background;
  @Input() embeddedInDatagrid = false;
  @Input() disabled = PAGINATION_SPEC_ACCURATE_DEFAULTS.disabled;

  @Output() readonly pageChange = new EventEmitter<number>();
  @Output() readonly pageSizeChange = new EventEmitter<number>();
  @Output() readonly firstPageNavigate = new EventEmitter<void>();
  @Output() readonly previousPageNavigate = new EventEmitter<void>();
  @Output() readonly nextPageNavigate = new EventEmitter<void>();
  @Output() readonly lastPageNavigate = new EventEmitter<void>();

  perPageMenuOpen = false;
  pageOffsetMenuOpen = false;
  pageInputValue = String(this.currentPage);
  perPageMenuPos: PaginationMenuPos | null = null;
  pageOffsetMenuPos: PaginationMenuPos | null = null;

  private overlayRepositionCleanup: (() => void) | null = null;

  constructor(private readonly cdr: ChangeDetectorRef) {}

  get safeTotalPages(): number {
    return Math.max(1, this.totalPages);
  }

  get safeCurrentPage(): number {
    return clamp(this.currentPage, 1, this.safeTotalPages);
  }

  get safePageSizeOptions(): number[] {
    return normalizePositiveOptions(this.pageSizeOptions);
  }

  get safePageSize(): number {
    return this.safePageSizeOptions.includes(this.pageSize)
      ? this.pageSize
      : this.safePageSizeOptions[0];
  }

  get offsetOptions(): number[] {
    if (this.pageOffsetOptions && this.pageOffsetOptions.length > 0) {
      return normalizePositiveOptions(this.pageOffsetOptions).map((value) =>
        clamp(value, 1, this.safeTotalPages),
      );
    }
    return Array.from({ length: this.safeTotalPages }, (_, index) => index + 1);
  }

  get atFirstPage(): boolean {
    return this.safeCurrentPage <= 1;
  }

  get atLastPage(): boolean {
    return this.safeCurrentPage >= this.safeTotalPages;
  }

  get resolvedPerPageDropdownState(): IdsPaginationDropdownState {
    if (this.dropdownState !== "collapsed") {
      return this.dropdownState;
    }
    return this.perPageMenuOpen ? "expanded-below" : "collapsed";
  }

  get resolvedPageOffsetDropdownState(): IdsPaginationDropdownState {
    if (this.pageOffsetDropdownState !== "collapsed") {
      return this.pageOffsetDropdownState;
    }
    return this.pageOffsetMenuOpen ? "expanded-below" : "collapsed";
  }

  get rootClass(): Record<string, boolean> {
    return {
      rootWhite: this.background === "white",
      rootNone: this.background === "none",
      rootGray: this.background === "gray",
      rootEmbedded: this.embeddedInDatagrid,
    };
  }

  ngOnChanges(): void {
    this.pageInputValue = String(this.safeCurrentPage);
    if (this.resolvedPerPageDropdownState !== "collapsed") {
      this.bindOverlayRepositionListeners();
      this.scheduleOverlayPortalAndPosition("perPage");
    }
    if (this.resolvedPageOffsetDropdownState !== "collapsed") {
      this.bindOverlayRepositionListeners();
      this.scheduleOverlayPortalAndPosition("pageOffset");
    }
  }

  ngOnDestroy(): void {
    this.unbindOverlayRepositionListeners();
  }

  goToPage(nextPage: number): void {
    if (this.disabled) return;
    const clamped = clamp(nextPage, 1, this.safeTotalPages);
    this.pageInputValue = String(clamped);
    this.pageChange.emit(clamped);
  }

  onFirstPage(): void {
    if (this.disabled || this.atFirstPage) return;
    this.firstPageNavigate.emit();
    this.goToPage(1);
  }

  onPreviousPage(): void {
    if (this.disabled || this.atFirstPage) return;
    this.previousPageNavigate.emit();
    this.goToPage(this.safeCurrentPage - 1);
  }

  onNextPage(): void {
    if (this.disabled || this.atLastPage) return;
    this.nextPageNavigate.emit();
    this.goToPage(this.safeCurrentPage + 1);
  }

  onLastPage(): void {
    if (this.disabled || this.atLastPage) return;
    this.lastPageNavigate.emit();
    this.goToPage(this.safeTotalPages);
  }

  onPageInputChange(value: string): void {
    this.pageInputValue = value.replace(/[^\d]/g, "");
  }

  commitPageInput(): void {
    const parsed = Number.parseInt(this.pageInputValue, 10);
    if (!Number.isFinite(parsed)) {
      this.pageInputValue = String(this.safeCurrentPage);
      return;
    }
    this.goToPage(parsed);
  }

  onPageInputKeydown(event: KeyboardEvent): void {
    if (event.key === "Enter") {
      this.commitPageInput();
      (event.target as HTMLInputElement | null)?.blur();
    }
  }

  togglePerPageMenu(): void {
    if (this.disabled) return;
    this.closePageOffsetMenu();
    this.perPageMenuOpen = !this.perPageMenuOpen;
    if (this.perPageMenuOpen) {
      this.bindOverlayRepositionListeners();
      this.scheduleOverlayPortalAndPosition("perPage");
    } else {
      this.closePerPageMenu();
    }
    this.cdr.markForCheck();
  }

  closePerPageMenu(): void {
    this.perPageMenuOpen = false;
    this.perPageMenuPos = null;
    if (this.resolvedPageOffsetDropdownState === "collapsed") {
      this.unbindOverlayRepositionListeners();
    }
    this.cdr.markForCheck();
  }

  selectPageSize(size: number): void {
    this.pageSizeChange.emit(size);
    this.closePerPageMenu();
  }

  togglePageOffsetMenu(): void {
    if (this.disabled) return;
    this.closePerPageMenu();
    this.pageOffsetMenuOpen = !this.pageOffsetMenuOpen;
    if (this.pageOffsetMenuOpen) {
      this.bindOverlayRepositionListeners();
      this.scheduleOverlayPortalAndPosition("pageOffset");
    } else {
      this.closePageOffsetMenu();
    }
    this.cdr.markForCheck();
  }

  closePageOffsetMenu(): void {
    this.pageOffsetMenuOpen = false;
    this.pageOffsetMenuPos = null;
    if (this.resolvedPerPageDropdownState === "collapsed") {
      this.unbindOverlayRepositionListeners();
    }
    this.cdr.markForCheck();
  }

  selectPageOffset(page: number): void {
    this.goToPage(page);
    this.closePageOffsetMenu();
  }

  onPerPageTriggerBlur(event: FocusEvent): void {
    const nextTarget = event.relatedTarget as HTMLElement | null;
    if (nextTarget?.closest("[data-ids-pagination-per-page-menu]")) return;
    this.closePerPageMenu();
  }

  onPageOffsetTriggerBlur(event: FocusEvent): void {
    const nextTarget = event.relatedTarget as HTMLElement | null;
    if (nextTarget?.closest("[data-ids-pagination-page-offset-menu]")) return;
    this.closePageOffsetMenu();
  }

  @HostListener("window:resize")
  @HostListener("window:scroll")
  onViewportChange(): void {
    if (this.resolvedPerPageDropdownState !== "collapsed") {
      this.updatePerPageMenuPos();
    }
    if (this.resolvedPageOffsetDropdownState !== "collapsed") {
      this.updatePageOffsetMenuPos();
    }
    this.cdr.markForCheck();
  }

  private updatePerPageMenuPos(): void {
    const trigger = this.perPageTrigger?.nativeElement;
    const menu = this.perPageMenuLayer?.nativeElement;
    if (!trigger) return;
    const rect = trigger.getBoundingClientRect();
    const width = rect.width;
    const left = rect.left;
    if (this.resolvedPerPageDropdownState === "expanded-above") {
      const menuHeight = menu?.getBoundingClientRect().height ?? 0;
      this.perPageMenuPos = { top: rect.top + 1 - menuHeight, left, width };
      return;
    }
    this.perPageMenuPos = { top: rect.top + rect.height - 1, left, width };
  }

  private updatePageOffsetMenuPos(): void {
    const trigger = this.pageOffsetTrigger?.nativeElement;
    const menu = this.pageOffsetMenuLayer?.nativeElement;
    if (!trigger) return;
    const rect = trigger.getBoundingClientRect();
    const width = rect.width;
    const left = rect.left;
    if (this.resolvedPageOffsetDropdownState === "expanded-above") {
      const menuHeight = menu?.getBoundingClientRect().height ?? 0;
      this.pageOffsetMenuPos = { top: rect.top + 1 - menuHeight, left, width };
      return;
    }
    this.pageOffsetMenuPos = { top: rect.top + rect.height - 1, left, width };
  }

  private portalToBody(el: HTMLElement | undefined): void {
    if (el && el.parentElement !== document.body) {
      document.body.appendChild(el);
    }
  }

  private scheduleOverlayPortalAndPosition(kind: "perPage" | "pageOffset"): void {
    requestAnimationFrame(() => {
      if (kind === "perPage" && this.resolvedPerPageDropdownState === "collapsed") return;
      if (kind === "pageOffset" && this.resolvedPageOffsetDropdownState === "collapsed") return;

      if (kind === "perPage") {
        this.portalToBody(this.perPageMenuLayer?.nativeElement);
        this.updatePerPageMenuPos();
      } else {
        this.portalToBody(this.pageOffsetMenuLayer?.nativeElement);
        this.updatePageOffsetMenuPos();
      }
      this.cdr.markForCheck();

      requestAnimationFrame(() => {
        if (kind === "perPage" && this.resolvedPerPageDropdownState === "collapsed") return;
        if (kind === "pageOffset" && this.resolvedPageOffsetDropdownState === "collapsed") return;
        if (kind === "perPage") {
          this.updatePerPageMenuPos();
        } else {
          this.updatePageOffsetMenuPos();
        }
        this.cdr.markForCheck();
      });
    });
  }

  private bindOverlayRepositionListeners(): void {
    if (this.overlayRepositionCleanup) return;
    const onUpdate = () => {
      let changed = false;
      if (this.resolvedPerPageDropdownState !== "collapsed") {
        this.updatePerPageMenuPos();
        changed = true;
      }
      if (this.resolvedPageOffsetDropdownState !== "collapsed") {
        this.updatePageOffsetMenuPos();
        changed = true;
      }
      if (changed) this.cdr.markForCheck();
    };
    window.addEventListener("resize", onUpdate);
    window.addEventListener("scroll", onUpdate, true);
    this.overlayRepositionCleanup = () => {
      window.removeEventListener("resize", onUpdate);
      window.removeEventListener("scroll", onUpdate, true);
      this.overlayRepositionCleanup = null;
    };
  }

  private unbindOverlayRepositionListeners(): void {
    this.overlayRepositionCleanup?.();
    this.overlayRepositionCleanup = null;
  }
}

<nav class="root" [ngClass]="rootClass" aria-label="Pagination">
  @if (showPerPage) {
    <div class="resultsGroup">
      <span class="label">Show:</span>
      <div class="dropdownWrap">
        <button
          #perPageTrigger
          class="dropdownTrigger"
          type="button"
          [disabled]="disabled"
          aria-haspopup="listbox"
          [attr.aria-expanded]="resolvedPerPageDropdownState !== 'collapsed'"
          aria-label="Items per page"
          (click)="togglePerPageMenu()"
          (blur)="onPerPageTriggerBlur($event)"
        >
          <span>{{ safePageSize }}</span>
          <ids-icon
            shapeName="arrow-drop-tri-caret"
            className="caretIcon"
            [size]="caretIconSize"
            variant="mask"
          />
        </button>
      </div>
      <span class="label">per page</span>
    </div>
  } @else {
    <span></span>
  }

  <div class="pageNavGroup">
    @if (safeTotalPages <= 1) {
      <span class="countText">1 page</span>
    } @else {
      @if (showFirstLast) {
        <button
          class="iconButton"
          type="button"
          [disabled]="disabled || atFirstPage"
          aria-label="First page"
          (click)="onFirstPage()"
        >
          <ids-icon
            shapeName="double-chev-left"
            className="navIcon"
            [size]="navIconSize"
            variant="mask"
          />
        </button>
      }
      <button
        class="iconButton"
        type="button"
        [disabled]="disabled || atFirstPage"
        aria-label="Previous page"
        (click)="onPreviousPage()"
      >
        <ids-icon
          shapeName="chev-left"
          className="navIcon"
          [size]="navIconSize"
          variant="mask"
        />
      </button>
      @if (showPageOffset) {
        <div class="pageOffsetWrap">
          <button
            #pageOffsetTrigger
            class="pageOffsetTrigger"
            type="button"
            [disabled]="disabled"
            aria-haspopup="listbox"
            [attr.aria-expanded]="resolvedPageOffsetDropdownState !== 'collapsed'"
            aria-label="Page offset"
            (click)="togglePageOffsetMenu()"
            (blur)="onPageOffsetTriggerBlur($event)"
          >
            <span>{{ safeCurrentPage }}</span>
            <ids-icon
              shapeName="arrow-drop-tri-caret"
              className="pageOffsetCaretIcon"
              [size]="caretIconSize"
              variant="mask"
            />
          </button>
        </div>
      } @else {
        <div class="pageInputWrap">
          <input
            class="pageInput"
            [value]="pageInputValue"
            aria-label="Current page"
            (input)="onPageInputChange($any($event.target).value)"
            (blur)="commitPageInput()"
            (keydown)="onPageInputKeydown($event)"
          />
        </div>
      }
      <span class="countText">of {{ safeTotalPages }}</span>
      <button
        class="iconButton"
        type="button"
        [disabled]="disabled || atLastPage"
        aria-label="Next page"
        (click)="onNextPage()"
      >
        <ids-icon
          shapeName="chev-right"
          className="navIcon"
          [size]="navIconSize"
          variant="mask"
        />
      </button>
      @if (showFirstLast) {
        <button
          class="iconButton"
          type="button"
          [disabled]="disabled || atLastPage"
          aria-label="Last page"
          (click)="onLastPage()"
        >
          <ids-icon
            shapeName="double-chev-right"
            className="navIcon"
            [size]="navIconSize"
            variant="mask"
          />
        </button>
      }
    }
  </div>
</nav>

@if (resolvedPerPageDropdownState !== "collapsed") {
  <ul
    #perPageMenuLayer
    class="dropdownMenu dropdownMenuPortaled"
    [class.dropdownMenuAbove]="resolvedPerPageDropdownState === 'expanded-above'"
    [class.dropdownMenuBelow]="resolvedPerPageDropdownState === 'expanded-below'"
    data-ids-pagination-per-page-menu
    [style.position]="'fixed'"
    [style.top.px]="perPageMenuPos?.top ?? 0"
    [style.left.px]="perPageMenuPos?.left ?? 0"
    [style.width.px]="perPageMenuPos?.width ?? 90"
    role="listbox"
    aria-label="Items per page options"
    (click)="$event.stopPropagation()"
  >
    @for (option of safePageSizeOptions; track option) {
      <li class="dropdownOptionWrap">
        <button
          type="button"
          role="option"
          class="dropdownOption"
          [class.dropdownOptionSelected]="option === safePageSize"
          [attr.aria-selected]="option === safePageSize"
          (click)="selectPageSize(option)"
        >
          {{ option }}
        </button>
      </li>
    }
  </ul>
}

@if (resolvedPageOffsetDropdownState !== "collapsed") {
  <ul
    #pageOffsetMenuLayer
    class="pageOffsetMenu pageOffsetMenuPortaled"
    [class.pageOffsetMenuAbove]="resolvedPageOffsetDropdownState === 'expanded-above'"
    [class.pageOffsetMenuBelow]="resolvedPageOffsetDropdownState === 'expanded-below'"
    data-ids-pagination-page-offset-menu
    [style.position]="'fixed'"
    [style.top.px]="pageOffsetMenuPos?.top ?? 0"
    [style.left.px]="pageOffsetMenuPos?.left ?? 0"
    [style.width.px]="pageOffsetMenuPos?.width ?? 40"
    role="listbox"
    aria-label="Page offsets"
    (click)="$event.stopPropagation()"
  >
    @for (pageOffset of offsetOptions; track pageOffset) {
      <li class="pageOffsetOptionWrap">
        <button
          type="button"
          role="option"
          class="pageOffsetOption"
          [class.pageOffsetOptionSelected]="pageOffset === safeCurrentPage"
          [attr.aria-selected]="pageOffset === safeCurrentPage"
          (click)="selectPageOffset(pageOffset)"
        >
          {{ pageOffset }}
        </button>
      </li>
    }
  </ul>
}

// storybook/src/components/IdsPagination.tsx
import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type ComponentProps,
} from "react";
import { createPortal } from "react-dom";
import { Icon } from "./Icon";
import styles from "./IdsPagination.module.css";

export type IdsPaginationDropdownState =
  | "collapsed"
  | "expanded-below"
  | "expanded-above";
export type IdsPaginationBackground = "none" | "gray" | "white";

const CARET_ICON_SIZE = { width: 10, height: 10 } as const;
const NAV_ICON_SIZE = { width: 16, height: 16 } as const;

export interface IdsPaginationProps extends ComponentProps<"nav"> {
  currentPage: number;
  totalPages: number;
  onPageChange?: (page: number) => void;
  onPageSizeChange?: (size: number) => void;
  onFirstPageNavigate?: () => void;
  onPreviousPageNavigate?: () => void;
  onNextPageNavigate?: () => void;
  onLastPageNavigate?: () => void;
  pageSize?: number;
  pageSizeOptions?: number[];
  onPageSizeChange?: (size: number) => void;
  showPerPage?: boolean;
  showFirstLast?: boolean;
  showPageOffset?: boolean;
  pageOffsetOptions?: number[];
  dropdownState?: IdsPaginationDropdownState;
  pageOffsetDropdownState?: IdsPaginationDropdownState;
  background?: IdsPaginationBackground;
  embeddedInDatagrid?: boolean;
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(Math.max(value, min), max);
}

function normalizePageSizeOptions(options: number[]): number[] {
  const uniquePositive = Array.from(
    new Set(options.filter((value) => Number.isFinite(value) && value > 0)),
  );
  return uniquePositive.length > 0 ? uniquePositive : [25, 50, 75, 100];
}

type PaginationMenuPos = { top: number; left: number; width: number };

function computeMenuPos(
  trigger: HTMLElement | null,
  menu: HTMLElement | null,
  placement: Exclude<IdsPaginationDropdownState, "collapsed">,
): PaginationMenuPos | null {
  if (!trigger) return null;
  const rect = trigger.getBoundingClientRect();
  const width = rect.width;
  const left = rect.left;
  if (placement === "expanded-above") {
    const menuHeight = menu?.getBoundingClientRect().height ?? 0;
    return { top: rect.top + 1 - menuHeight, left, width };
  }
  return { top: rect.top + rect.height - 1, left, width };
}

function usePortaledMenuPosition(
  open: boolean,
  placement: IdsPaginationDropdownState,
  triggerRef: React.RefObject<HTMLElement | null>,
  menuRef: React.RefObject<HTMLElement | null>,
): PaginationMenuPos | null {
  const [pos, setPos] = useState<PaginationMenuPos | null>(null);

  useEffect(() => {
    if (!open || placement === "collapsed") {
      setPos(null);
      return;
    }

    const update = () => {
      const next = computeMenuPos(
        triggerRef.current,
        menuRef.current,
        placement,
      );
      setPos(next);
    };

    update();
    const frame = requestAnimationFrame(() => {
      update();
    });
    window.addEventListener("resize", update);
    window.addEventListener("scroll", update, true);
    return () => {
      cancelAnimationFrame(frame);
      window.removeEventListener("resize", update);
      window.removeEventListener("scroll", update, true);
    };
  }, [menuRef, open, placement, triggerRef]);

  return pos;
}

export function IdsPagination({
  currentPage,
  totalPages,
  onPageChange,
  onPageSizeChange,
  onFirstPageNavigate,
  onPreviousPageNavigate,
  onNextPageNavigate,
  onLastPageNavigate,
  pageSize = 25,
  pageSizeOptions = [25, 50, 75, 100],
  showPerPage = true,
  showFirstLast = true,
  showPageOffset = false,
  pageOffsetOptions,
  dropdownState = "collapsed",
  pageOffsetDropdownState = "collapsed",
  background = "gray",
  embeddedInDatagrid = false,
  className,
  ...rest
}: IdsPaginationProps) {
  const pageOffsetRef = useRef<HTMLButtonElement | null>(null);
  const perPageTriggerRef = useRef<HTMLButtonElement | null>(null);
  const perPageMenuRef = useRef<HTMLUListElement | null>(null);
  const pageOffsetMenuRef = useRef<HTMLUListElement | null>(null);
  const safeTotalPages = Math.max(1, totalPages);
  const controlledCurrentPage = clamp(currentPage, 1, safeTotalPages);
  const safePageSizeOptions = normalizePageSizeOptions(pageSizeOptions);
  const safePageSize = safePageSizeOptions.includes(pageSize)
    ? pageSize
    : safePageSizeOptions[0];
  const offsetOptions = useMemo(
    () =>
      pageOffsetOptions && pageOffsetOptions.length > 0
        ? normalizePageSizeOptions(pageOffsetOptions).map((value) =>
            clamp(value, 1, safeTotalPages),
          )
        : Array.from({ length: safeTotalPages }, (_, index) => index + 1),
    [pageOffsetOptions, safeTotalPages],
  );
  const [internalPage, setInternalPage] = useState(controlledCurrentPage);
  const [pageInputValue, setPageInputValue] = useState(
    String(controlledCurrentPage),
  );
  const [perPageMenuOpen, setPerPageMenuOpen] = useState(false);
  const [pageOffsetMenuOpen, setPageOffsetMenuOpen] = useState(false);
  const resolvedPerPageDropdownState =
    dropdownState !== "collapsed"
      ? dropdownState
      : perPageMenuOpen
        ? "expanded-below"
        : "collapsed";
  const safeCurrentPage = onPageChange ? controlledCurrentPage : internalPage;
  const resolvedPageOffsetDropdownState =
    pageOffsetDropdownState !== "collapsed"
      ? pageOffsetDropdownState
      : pageOffsetMenuOpen
        ? "expanded-below"
        : "collapsed";
  const perPageMenuPos = usePortaledMenuPosition(
    resolvedPerPageDropdownState !== "collapsed",
    resolvedPerPageDropdownState,
    perPageTriggerRef,
    perPageMenuRef,
  );
  const pageOffsetMenuPos = usePortaledMenuPosition(
    resolvedPageOffsetDropdownState !== "collapsed",
    resolvedPageOffsetDropdownState,
    pageOffsetRef,
    pageOffsetMenuRef,
  );

  useEffect(() => {
    if (onPageChange) return;
    setInternalPage(controlledCurrentPage);
  }, [controlledCurrentPage, onPageChange]);

  useEffect(() => {
    setPageInputValue(String(safeCurrentPage));
  }, [safeCurrentPage]);

  const atFirstPage = safeCurrentPage <= 1;
  const atLastPage = safeCurrentPage >= safeTotalPages;

  const goToPage = (nextPage: number) => {
    const clamped = clamp(nextPage, 1, safeTotalPages);
    if (onPageChange) {
      onPageChange(clamped);
      return;
    }
    setInternalPage(clamped);
  };

  const commitPageInput = () => {
    const parsed = Number.parseInt(pageInputValue, 10);
    if (!Number.isFinite(parsed)) {
      setPageInputValue(String(safeCurrentPage));
      return;
    }
    goToPage(parsed);
  };

  const togglePageOffsetMenu = () => {
    closePerPageMenu();
    setPageOffsetMenuOpen((prev) => !prev);
  };

  const closePageOffsetMenu = () => {
    setPageOffsetMenuOpen(false);
  };

  const togglePerPageMenu = () => {
    closePageOffsetMenu();
    setPerPageMenuOpen((prev) => !prev);
  };

  const closePerPageMenu = () => {
    setPerPageMenuOpen(false);
  };

  return (
    <>
    <nav
      aria-label="Pagination"
      className={[
        styles.root,
        background === "white"
          ? styles.rootWhite
          : background === "none"
            ? styles.rootNone
            : styles.rootGray,
        embeddedInDatagrid ? styles.rootEmbedded : "",
        className,
      ]
        .filter(Boolean)
        .join(" ")}
      {...rest}
    >
      {showPerPage ? (
        <div className={styles.resultsGroup}>
          <span className={styles.label}>Show:</span>
          <div className={styles.dropdownWrap}>
            <button
              ref={perPageTriggerRef}
              className={styles.dropdownTrigger}
              type="button"
              aria-haspopup="listbox"
              aria-expanded={resolvedPerPageDropdownState !== "collapsed"}
              aria-label="Items per page"
              onClick={togglePerPageMenu}
              onBlur={(event) => {
                const nextTarget = event.relatedTarget as Node | null;
                if (nextTarget?.closest("[data-ids-pagination-per-page-menu]")) return;
                closePerPageMenu();
              }}
            >
              <span>{safePageSize}</span>
              <Icon
                shapeName="arrow-drop-tri-caret"
                className={styles.caretIcon}
                style={CARET_ICON_SIZE}
              />
            </button>
          </div>
          <span className={styles.label}>per page</span>
        </div>
      ) : (
        <span />
      )}

      <div className={styles.pageNavGroup}>
        {safeTotalPages <= 1 ? (
          <span className={styles.countText}>1 page</span>
        ) : (
          <>
            {showFirstLast ? (
              <button
                className={styles.iconButton}
                type="button"
                onClick={() => {
                  onFirstPageNavigate?.();
                  goToPage(1);
                }}
                disabled={atFirstPage}
                aria-label="First page"
              >
                <Icon
                  shapeName="double-chev-left"
                  className={styles.navIcon}
                  style={NAV_ICON_SIZE}
                />
              </button>
            ) : null}
            <button
              className={styles.iconButton}
              type="button"
              onClick={() => {
                onPreviousPageNavigate?.();
                goToPage(safeCurrentPage - 1);
              }}
              disabled={atFirstPage}
              aria-label="Previous page"
            >
              <Icon
                shapeName="chev-left"
                className={styles.navIcon}
                style={NAV_ICON_SIZE}
              />
            </button>
            {showPageOffset ? (
              <div className={styles.pageOffsetWrap}>
                <button
                  ref={pageOffsetRef}
                  className={styles.pageOffsetTrigger}
                  type="button"
                  aria-haspopup="listbox"
                  aria-expanded={
                    resolvedPageOffsetDropdownState !== "collapsed"
                  }
                  aria-label="Page offset"
                  onClick={togglePageOffsetMenu}
                  onBlur={(event) => {
                    const nextTarget = event.relatedTarget as Node | null;
                    if (nextTarget?.closest("[data-ids-pagination-page-offset-menu]"))
                      return;
                    closePageOffsetMenu();
                  }}
                >
                  <span>{safeCurrentPage}</span>
                  <Icon
                    shapeName="arrow-drop-tri-caret"
                    className={styles.pageOffsetCaretIcon}
                    style={CARET_ICON_SIZE}
                  />
                </button>
              </div>
            ) : (
              <div className={styles.pageInputWrap}>
                <input
                  className={styles.pageInput}
                  value={pageInputValue}
                  onChange={(event) =>
                    setPageInputValue(event.target.value.replace(/[^\d]/g, ""))
                  }
                  onBlur={commitPageInput}
                  onKeyDown={(event) => {
                    if (event.key === "Enter") {
                      commitPageInput();
                      event.currentTarget.blur();
                    }
                  }}
                  aria-label="Current page"
                />
              </div>
            )}
            <span className={styles.countText}>of {safeTotalPages}</span>
            <button
              className={styles.iconButton}
              type="button"
              onClick={() => {
                onNextPageNavigate?.();
                goToPage(safeCurrentPage + 1);
              }}
              disabled={atLastPage}
              aria-label="Next page"
            >
              <Icon
                shapeName="chev-right"
                className={styles.navIcon}
                style={NAV_ICON_SIZE}
              />
            </button>
            {showFirstLast ? (
              <button
                className={styles.iconButton}
                type="button"
                onClick={() => {
                  onLastPageNavigate?.();
                  goToPage(safeTotalPages);
                }}
                disabled={atLastPage}
                aria-label="Last page"
              >
                <Icon
                  shapeName="double-chev-right"
                  className={styles.navIcon}
                  style={NAV_ICON_SIZE}
                />
              </button>
            ) : null}
          </>
        )}
      </div>
    </nav>
    {resolvedPerPageDropdownState !== "collapsed" &&
    typeof document !== "undefined"
      ? createPortal(
          <ul
            ref={perPageMenuRef}
            className={[
              styles.dropdownMenu,
              styles.dropdownMenuPortaled,
              resolvedPerPageDropdownState === "expanded-above"
                ? styles.dropdownMenuAbove
                : styles.dropdownMenuBelow,
            ]
              .filter(Boolean)
              .join(" ")}
            data-ids-pagination-per-page-menu
            style={{
              position: "fixed",
              top: perPageMenuPos?.top ?? 0,
              left: perPageMenuPos?.left ?? 0,
              width: perPageMenuPos?.width ?? 90,
            }}
            role="listbox"
            aria-label="Items per page options"
            onClick={(event) => event.stopPropagation()}
          >
            {safePageSizeOptions.map((option) => {
              const selected = option === safePageSize;
              return (
                <li key={option} className={styles.dropdownOptionWrap}>
                  <button
                    type="button"
                    role="option"
                    aria-selected={selected}
                    className={[
                      styles.dropdownOption,
                      selected ? styles.dropdownOptionSelected : "",
                    ]
                      .filter(Boolean)
                      .join(" ")}
                    onClick={() => {
                      onPageSizeChange?.(option);
                      closePerPageMenu();
                    }}
                  >
                    {option}
                  </button>
                </li>
              );
            })}
          </ul>,
          document.body,
        )
      : null}
    {resolvedPageOffsetDropdownState !== "collapsed" &&
    typeof document !== "undefined"
      ? createPortal(
          <ul
            ref={pageOffsetMenuRef}
            className={[
              styles.pageOffsetMenu,
              styles.pageOffsetMenuPortaled,
              resolvedPageOffsetDropdownState === "expanded-above"
                ? styles.pageOffsetMenuAbove
                : styles.pageOffsetMenuBelow,
            ]
              .filter(Boolean)
              .join(" ")}
            data-ids-pagination-page-offset-menu
            style={{
              position: "fixed",
              top: pageOffsetMenuPos?.top ?? 0,
              left: pageOffsetMenuPos?.left ?? 0,
              width: pageOffsetMenuPos?.width ?? 40,
            }}
            role="listbox"
            aria-label="Page offsets"
            onClick={(event) => event.stopPropagation()}
          >
            {offsetOptions.map((pageOffset) => {
              const selected = pageOffset === safeCurrentPage;
              return (
                <li key={pageOffset} className={styles.pageOffsetOptionWrap}>
                  <button
                    type="button"
                    role="option"
                    aria-selected={selected}
                    className={[
                      styles.pageOffsetOption,
                      selected ? styles.pageOffsetOptionSelected : "",
                    ]
                      .filter(Boolean)
                      .join(" ")}
                    onClick={() => {
                      goToPage(pageOffset);
                      closePageOffsetMenu();
                    }}
                  >
                    {pageOffset}
                  </button>
                </li>
              );
            })}
          </ul>,
          document.body,
        )
      : null}
    </>
  );
}
