// storybook-angular/src/components/ids-text-box/ids-text-box.component.ts
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  EventEmitter,
  Input,
  OnChanges,
  Output,
  SimpleChanges,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  TEXT_BOX_SPEC_ACCURATE_DEFAULTS,
  type TextBoxComponentType,
  type TextBoxSize,
  type TextBoxState,
} from "@component-contracts/ids/text-box.contract";
import { IdsIconComponent } from "../ids-icon/ids-icon.component";

type FocusModality = "keyboard" | "pointer";

@Component({
  selector: "ids-text-box",
  standalone: true,
  imports: [CommonModule, IdsIconComponent],
  templateUrl: "./ids-text-box.component.html",
  styleUrl: "./ids-text-box.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class IdsTextBoxComponent implements OnChanges {
  @Input() componentType: TextBoxComponentType =
    TEXT_BOX_SPEC_ACCURATE_DEFAULTS.componentType;
  @Input() size: TextBoxSize = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.size;
  /** Demo/testing override — runtime interaction still applies when not forced. */
  @Input() state: TextBoxState = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.state;
  @Input() placeholder = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.placeholder;
  @Input() value?: string;
  @Input() defaultValue = "";
  @Input() disabled = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.disabled;
  @Input() invalid = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.invalid;
  @Input() helperText = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.helperText;
  @Input() errorText = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.errorText;
  @Input() showHelperText = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.showHelperText;
  @Input() showIcon = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.showIcon;
  @Input() iconName = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.iconName;
  @Input() id?: string;
  @Input() name?: string;
  @Input() rows = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.rows;
  @Input() inputType = TEXT_BOX_SPEC_ACCURATE_DEFAULTS.inputType;
  @Input() ariaLabel?: string;
  @Input() ariaDescribedBy?: string;

  @Output() readonly valueChange = new EventEmitter<string>();

  focusModality: FocusModality = "pointer";
  isFocused = false;
  private internalValue = "";
  private generatedId = `ids-text-box-${Math.random().toString(36).slice(2, 9)}`;

  constructor(private readonly cdr: ChangeDetectorRef) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["defaultValue"] && this.value === undefined && !changes["defaultValue"].firstChange) {
      this.internalValue = this.defaultValue;
    }
    if (changes["defaultValue"]?.firstChange && this.value === undefined) {
      this.internalValue = this.defaultValue;
    }
  }

  get resolvedId(): string {
    return this.id ?? this.generatedId;
  }

  get helperId(): string {
    return `${this.resolvedId}-help`;
  }

  get computedInvalid(): boolean {
    return this.invalid || this.state === "error";
  }

  get visualState(): TextBoxState {
    if (this.disabled) {
      return "disabled";
    }
    if (this.computedInvalid) {
      return "error";
    }
    return this.state;
  }

  get shouldRenderHelper(): boolean {
    return this.showHelperText && (this.computedInvalid || Boolean(this.helperText));
  }

  get helperCopy(): string {
    return this.computedInvalid ? this.errorText : this.helperText;
  }

  get resolvedValue(): string {
    return this.value ?? this.internalValue;
  }

  get isTextArea(): boolean {
    return this.componentType === "text-area";
  }

  get describedBy(): string | undefined {
    if (this.shouldRenderHelper) {
      return this.ariaDescribedBy ?? this.helperId;
    }
    return this.ariaDescribedBy;
  }

  onPointerDown(): void {
    this.focusModality = "pointer";
  }

  onKeyDown(event: KeyboardEvent): void {
    if (event.key === "Tab") {
      this.focusModality = "keyboard";
    }
  }

  onFocus(): void {
    this.isFocused = true;
    this.cdr.markForCheck();
  }

  onBlur(): void {
    this.isFocused = false;
    this.cdr.markForCheck();
  }

  onInput(event: Event): void {
    const next = (event.target as HTMLInputElement | HTMLTextAreaElement).value;
    if (this.value === undefined) {
      this.internalValue = next;
    }
    this.valueChange.emit(next);
  }
}

<div class="ids-text-box">
  <div
    class="ids-text-box__control"
    [class.ids-text-box__control--large]="!isTextArea && size === 'large'"
    [class.ids-text-box__control--small]="!isTextArea && size === 'small'"
    [class.ids-text-box__control--text-area]="isTextArea"
    [attr.data-state]="visualState"
    [attr.data-focus-modality]="focusModality"
    [attr.data-focused]="isFocused ? '' : null"
    (pointerdown)="onPointerDown()"
  >
    @if (isTextArea) {
      <textarea
        class="ids-text-box__value"
        [id]="resolvedId"
        [name]="name"
        [rows]="rows"
        [placeholder]="placeholder"
        [disabled]="disabled"
        [value]="resolvedValue"
        [attr.aria-label]="ariaLabel || null"
        [attr.aria-invalid]="computedInvalid ? 'true' : 'false'"
        [attr.aria-describedby]="describedBy || null"
        (keydown)="onKeyDown($event)"
        (focus)="onFocus()"
        (blur)="onBlur()"
        (input)="onInput($event)"
      ></textarea>
    } @else {
      <input
        class="ids-text-box__value"
        [id]="resolvedId"
        [name]="name"
        [type]="inputType"
        [placeholder]="placeholder"
        [disabled]="disabled"
        [value]="resolvedValue"
        [attr.aria-label]="ariaLabel || null"
        [attr.aria-invalid]="computedInvalid ? 'true' : 'false'"
        [attr.aria-describedby]="describedBy || null"
        (keydown)="onKeyDown($event)"
        (focus)="onFocus()"
        (blur)="onBlur()"
        (input)="onInput($event)"
      />
    }

    @if (showIcon) {
      <ids-icon
        [shapeName]="iconName"
        variant="img"
        className="ids-text-box__suffix-icon"
        [size]="16"
      />
    }
  </div>

  @if (shouldRenderHelper) {
    <div class="ids-text-box__helper-row" [id]="helperId">
      @if (computedInvalid) {
        <ids-icon
          shapeName="status-critical-square-solid"
          variant="img"
          className="ids-text-box__error-icon"
          [size]="16"
        />
      }
      <p
        class="ids-text-box__helper-copy"
        [class.ids-text-box__helper-copy--error]="computedInvalid"
      >
        {{ helperCopy }}
      </p>
    </div>
  }
</div>

// storybook/src/components/IdsTextBox.tsx
import type { ChangeEvent } from "react";
import { useId, useState } from "react";
import styles from "./IdsTextBox.module.css";

const iconUrlBySlug: Record<string, string> = (() => {
  const modules = import.meta.glob<string>("../../../assets/icons/*.svg", {
    eager: true,
    query: "?url",
    import: "default",
  });
  const out: Record<string, string> = {};
  for (const path of Object.keys(modules)) {
    const file = path.replace(/^.*\/([^/]+)\.svg$/, "$1");
    if (file && modules[path] != null) out[file] = modules[path] as string;
  }
  return out;
})();

function resolveIconUrl(shapeName: string): string | undefined {
  if (!/^[a-z0-9-]+$/.test(shapeName)) return undefined;
  return iconUrlBySlug[shapeName];
}

function handleKeyboardModality(event: { key: string }, setFocusModality: (mode: "keyboard") => void) {
  if (event.key === "Tab") {
    setFocusModality("keyboard");
  }
}

export type IdsTextBoxType = "text-input" | "text-area";
export type IdsTextBoxSize = "large" | "small";
export type IdsTextBoxState =
  | "default"
  | "hover"
  | "selected"
  | "focus"
  | "disabled"
  | "error";

export interface IdsTextBoxProps {
  componentType?: IdsTextBoxType;
  size?: IdsTextBoxSize;
  state?: IdsTextBoxState;
  placeholder?: string;
  value?: string;
  defaultValue?: string;
  disabled?: boolean;
  invalid?: boolean;
  helperText?: string;
  errorText?: string;
  showHelperText?: boolean;
  showIcon?: boolean;
  iconName?: string;
  id?: string;
  name?: string;
  rows?: number;
  inputType?: string;
  ariaLabel?: string;
  ariaDescribedBy?: string;
  onValueChange?: (value: string) => void;
}

export function IdsTextBox({
  componentType = "text-input",
  size = "large",
  state = "default",
  placeholder = "Placeholder Text",
  value,
  defaultValue,
  disabled = false,
  invalid = false,
  helperText = "Helper text",
  errorText = "Error message",
  showHelperText = true,
  showIcon = true,
  iconName = "mail",
  id,
  name,
  rows = 4,
  inputType = "text",
  ariaLabel,
  ariaDescribedBy,
  onValueChange,
}: IdsTextBoxProps) {
  const [focusModality, setFocusModality] = useState<"keyboard" | "pointer">("pointer");
  const generatedId = useId();
  const inputId = id ?? generatedId;
  const helperId = `${inputId}-help`;
  const computedInvalid = invalid || state === "error";
  const visualState: IdsTextBoxState = disabled
    ? "disabled"
    : computedInvalid
      ? "error"
      : state;
  const shouldRenderHelper = showHelperText && (computedInvalid || Boolean(helperText));
  const helperCopy = computedInvalid ? errorText : helperText;
  const suffixIconUrl = showIcon ? resolveIconUrl(iconName) : undefined;
  const errorIconUrl = resolveIconUrl("status-critical-square-solid");

  const commonProps = {
    id: inputId,
    name,
    placeholder,
    disabled,
    value,
    defaultValue,
    "aria-label": ariaLabel,
    "aria-invalid": computedInvalid ? "true" : "false",
    "aria-describedby": shouldRenderHelper ? ariaDescribedBy ?? helperId : ariaDescribedBy,
    onChange: (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      onValueChange?.(event.target.value);
    },
  };

  return (
    <div className={styles.root}>
      <div
        className={[
          styles.control,
          componentType === "text-area" ? styles.textArea : styles[size],
        ].join(" ")}
        data-state={visualState}
        data-focus-modality={focusModality}
        onPointerDownCapture={() => setFocusModality("pointer")}
      >
        {componentType === "text-area" ? (
          <textarea
            className={styles.value}
            rows={rows}
            onKeyDownCapture={(event) => handleKeyboardModality(event, setFocusModality)}
            {...commonProps}
          />
        ) : (
          <input
            className={styles.value}
            type={inputType}
            onKeyDownCapture={(event) => handleKeyboardModality(event, setFocusModality)}
            {...commonProps}
          />
        )}
        {suffixIconUrl ? <img src={suffixIconUrl} alt="" aria-hidden="true" className={styles.suffixIcon} /> : null}
      </div>

      {shouldRenderHelper ? (
        <div className={styles.helperRow} id={helperId}>
          {computedInvalid && errorIconUrl ? (
            <img src={errorIconUrl} alt="" aria-hidden="true" className={styles.errorIcon} />
          ) : null}
          <p className={computedInvalid ? styles.errorText : styles.helperText}>{helperCopy}</p>
        </div>
      ) : null}
    </div>
  );
}
